### ISSUE TITLE
update letsencrypt certs

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#1015]
Your certificate (or certificates) for the names listed below will expire in 9 days (on 13 Mar 21 15:54 +0000). Please make sure to renew your certificate before then, or visitors to your website will encounter errors.

amun.moc.thoth-station.ninja
amun.stage.thoth-station.ninja
api.moc.test.thoth-station.ninja
api.moc.thoth-station.ninja
isis.moc.thoth-station.ninja
isis.stage.thoth-station.ninja
isis.test.thoth-station.ninja
management.stage.thoth-station.ninja
management.test.thoth-station.ninja
pgweb.moc.thoth-station.ninja
pgweb.stage.thoth-station.ninja
pgweb.test.thoth-station.ninja
stage.thoth-station.ninja
test.thoth-station.ninja

/sig devops
/priority critical-urgent
/assign @harshad16

**Comment by harshad16** [comment]
we can delete the following one from routes.
api.moc.test.thoth-station.ninja
isis.moc.thoth-station.ninja
isis.stage.thoth-station.ninja
isis.test.thoth-station.ninja

**Comment by goern** [comment]
sefkeht-abwy-chatbot.thoth-station.ninja needs an update too
