### ISSUE TITLE
mi-scheduler cronjob not refreshing after merge

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/thoth-application#1036]
**Describe the bug**
After a PR is merged (e.g. #1034) the mi-scheduler cronjob in `thoth-test-core` (and probably also in other namespaces) on `ocp4` was not refreshed (the age of the cronjob was not updated, meaning the cronjob was not refreshed)

Probably an issue within `argocd`

**Screenshots**
![Screenshot from 2021-03-08 12-22-54](https://user-images.githubusercontent.com/46632404/110319850-bbe2cd80-800f-11eb-80a2-06c531873d96.png)

**Comment by harshad16** [comment]
This is fixed with https://github.com/AICoE/aicoe-cd/commit/3eb43a1e5e49428d4955cccb03eaee42c6d5946b.
closing the issue.
