### ISSUE TITLE
kafka is not available

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#1043]
**Describe the bug**
`%3|1615369332.972|FAIL|rdkafka#producer-1| [thrd:ssl://odh-message-bus-kafka-bootstrap-opf-kafka.apps.cnv.massop]: ssl://odh-message-bus-kafka-bootstrap-opf-kafka.apps.cnv.massopen.cloud:443/bootstrap: Failed to resolve 'odh-message-bus-kafka-bootstrap-opf-kafka.apps.cnv.massopen.cloud:443': Name or service not known (after 5009ms in state CONNECT, 14 identical error(s) suppressed)
`

/label deployment_name/moc
/kind bug

**To Reproduce**
1. Go to https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/thoth-frontend-prod/pods/user-api-1-zcpp5/logs

**Expected behavior**
no error ;)

**Comment by goern** [comment]
https://status.thoth-station.ninja/incidents/442de333

**Comment by harshad16** [comment]
This was fixed with this: https://github.com/thoth-station/thoth-application/commit/e3c16f2e26fec563aaef12614a870ccc0730ae7d
Thank you for opening the issue.
