### ISSUE TITLE
document how to reconfigure a new github access token

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#1063]
**Is your feature request related to a problem? Please describe.**
If the GitHub access token gets reissued by GitHub, it must be configured to be accessible to thoth, sesheta and kebechet services.

**Describe the solution you'd like**
Document.

**Describe alternatives you've considered**
none.

**Additional context**
N/A

**Comment by harshad16** [comment]
we manage token in openshift secret objects, which in kept along in the git vcs with encryption. 
If a github access token is updated or new token is requested then we would normally update the token in secret which inturn get propagated to deployed system. 
Is this brief information , what we are looking for? should we update this more elaborately ?
