### ISSUE TITLE
thoth station dashboards are empty in cnv-prod

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#1065]
**Describe the bug**
thoth station dashboards are empty in cnv-prod

**To Reproduce**
1. Go for example to https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/d/dd5ddeda417f2083b1b0526b222609dfcf1145be/thoth-knowledge-graph-content-metrics?orgId=1&refresh=30s

**Expected behavior**
thoth station dashboards are full of data

**Screenshots**

**Additional context**

**Comment by harshad16** [comment]
This issue is fixed now and all the dashboards can be seen.
