### ISSUE TITLE
label_sync config is misisng

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#1100]
**Describe the bug**
`{"component":"label_sync","error":"open /etc/config/labels_aicoe-aiops.yaml: no such file or directory","file":"label_sync/main.go:727","func":"main.main","level":"fatal","msg":"failed to load --config=/etc/config/labels_aicoe-aiops.yaml","severity":"fatal","time":"2021-03-24T07:48:25Z"}`

**To Reproduce**
1. Go to https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/opf-ci-prow/pods/label-sync-aicoe-aiops-1616572020-rgszc/logs

**Expected behavior**
rc=0

**Additional context**
looks like the yaml is simply missing at https://github.com/thoth-station/thoth-application/tree/master/prow/overlays/cnv-prod

/assign @tumido 
/sig devops

**Comment by tumido** [comment]
@goern I don't think the file is missing from there. Does it have to be synced somewhere?

https://github.com/thoth-station/thoth-application/blob/master/prow/overlays/cnv-prod/labels_aicoe-aiops.yaml

**Comment by tumido** [comment]
@goern any update to this? I don't think there's anything missing in this repo. Did I forgot to include the file anywhere?
