### ISSUE TITLE
deploy prow test-pods namespace configuration

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#1101]
**Is your feature request related to a problem? Please describe.**
please deploy https://github.com/thoth-station/thoth-application/blob/master/prow/overlays/cnv-prod-test-pods/kustomization.yaml to https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/opf-ci-test-pods/pods

**Additional context**
This is to separate out the pods run by prow jobs, and the prow software itself...

/assign @tumido 
/sig devops

**Comment by tumido** [comment]
@goern https://github.com/operate-first/argocd-apps/pull/120 should do the job
