### ISSUE TITLE
User API autoscaler

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#111]
**Is your feature request related to a problem? Please describe.**

As reported originally in https://github.com/thoth-station/user-api/issues/739 we could configure autoscaler for user API.

**Describe the solution you'd like**

Configure autoscaler so that user API is automatically scaled up if too many requests are made at the same time. As a start, we can use CPU utilization and observe how the API works. Later, we can utilize metrics, such as the number of connections to scale the replicas up/down.

**Describe alternatives you've considered**

Have constantly scaled multiple user API replicas, but that does not scale automatically based on load.

**Additional context**

https://docs.openshift.com/container-platform/3.9/dev_guide/pod_autoscaling.html
https://github.com/thoth-station/user-api/issues/739

**Comment by VannTen** [comment]
from my experience, web server like load scaling on cpu usage is not super reliable. Scaling on requests rate is probably a better idea, and the metrics is probably already available from whatever python webserver implementation.

**Comment by harshad16** [comment]
**Acceptance criteria**
- [ ] Check for custom metrics adapter on the cluster.  
- [ ] We can use the HTTP metrics from user-api usage and plug that in horizontal auto scaler
- [ ] create a panel in grafana dashboard for user-api instances.

**Resource**
- https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-metrics-apis
- https://docs.openshift.com/container-platform/4.11/nodes/pods/nodes-pods-autoscaling-custom.html

story points: 3pt
