### ISSUE TITLE
pypi release via the aicoe-ci is failing

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#1113]
**Describe the bug**
we use aicoe-ci for releasing python module to pypi , however the aicoe-ci is having issue lately releasing the apps.
the logs shows connection timeout, however pypi services are up. 

**To Reproduce**
1. Try release of python module
2. Head to the dashboard
3. See error

**Expected behavior**
successful upload to pypi.

**Comment by harshad16** [comment]
Found out that the task of releasing module to pypi is failing on the operate-first cluster and has no issues on the PSI cluster.
Will contact operate-first team to help us with this.

**Comment by harshad16** [comment]
The working is going on the operate-first side.
As we dont want the developer to get into annual work too much
the current solution is that we have added the stage deployment of the pipeline enabled on all thoth module which needs pypi release.

**Comment by goern** [comment]
@harshad16 can this be closed? is there techdebt created?

**Comment by goern** [comment]
@harshad16 feel free to re-open if the problem still persists.

/close

**Comment by harshad16** [comment]
> feel free to re-open if the problem still persists.

This is fixed. Thanks for closing it.
