### ISSUE TITLE
RFE: ODH z-stream sync job for Operate First - delete branch after merge

### ISSUE THREAD

**Issue by tumido** [thoth-station/thoth-application#1151]
**Is your feature request related to a problem? Please describe.**
First of all, let me tell you, I love this z-stream release PR feature! I think there's just one tiny bit that can be improved: The bot is opening a PR from a branch in the upstream repo. That is fine. I just think it should do a cleanup after the PR is merged. 

**Describe the solution you'd like**
Once the ODH Z-stream PR is merged, delete the PR branch

**Describe alternatives you've considered**
Right now we have to delete the branches manually,

It may be possible to set this up using branch protection or something in Prow maybe? I don't know, but maybe we don't have to reinvent a wheel here again.

**Additional context**
https://github.com/operate-first/apps/pull/505
https://github.com/operate-first/apps/branches
![image](https://user-images.githubusercontent.com/7453394/114148866-88e76e80-991a-11eb-8fd8-b77ab030549a.png)

/cc @harshad16

**Comment by goern** [comment]
Done we have a sesheta feature doing this?

**Comment by goern** [comment]
actually Kebechet update branches as also not updated

/label triage/needs-information

**Comment by harshad16** [comment]
This is great, we dont need to reinven the wheel , github has this feature itself 
https://docs.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches

please set this up and let us know if that helps

**Comment by tumido** [comment]
@harshad16 I don't think we want that feature to be enabled. I'm I'm not mistaken, that also deletes the branches on the forks, doesn't it? We don't want that. Sometimes we have deployments dependent on fork branches and so on. I'd leave the delete on the individual contributors, I don't want to enforce it on them for their fork repos.

The only thing I'd like to enforce is to have a clean and tidy upstream branch structure.

**Comment by tumido** [comment]
Btw, for example [dependabot](https://dependabot.com/) deletes a branch after its pr is merged automatically, I think that's a neat feature that it cleans after itself.

**Comment by goern** [comment]
/remove-lifecycle rotten
/lifecycle frozen

@fridex I think there is a related PR with kebechet?!

**Comment by harshad16** [comment]
> /remove-lifecycle rotten
> /lifecycle frozen
> 
>  I think there is a related PR with kebechet?!

This is related to the aicoe-ci , i will be adding it soon.

**Comment by goern** [comment]
> > /remove-lifecycle rotten
> > /lifecycle frozen
> > I think there is a related PR with kebechet?!
> 
> This is related to the aicoe-ci , i will be adding it soon.

ja right, I think deleting of branches should not be done by CI but by a Bot, wdyt?

**Comment by tumido** [comment]
I think it's easier to do this via a bot - since it can have a webhook listener for a PR merge. Then it's just a single API call.
