### ISSUE TITLE
[SPIKE] Check possible integration of thoth-solver with Pulp/pulp_python

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1154]
**Is your feature request related to a problem? Please describe.**

Let's see how our integration with pulp will look like. If we decide to integrate with pulp_python, we might think of integrating thoth-solver into pulp for package data gathering (besides other integration points).

**Describe the solution you'd like**

- [x] check architecture of pulp/pulp_python and evaluate if thoth-solver can be run each time a package is uploaded
- [ ] make sure thoth-solver is run asynchronously and can aggregate data of the package uploaded (to my knowledge, pulp uses dramatiq task queue)
- [ ] make sure thoth-solver computes package data that are subsequently sent to Thoth backend

**Additional context**

Related: https://github.com/thoth-station/thoth-application/issues/1153

**Comment by goern** [comment]
@fridex what is the prio of this?

**Comment by fridex** [comment]
I would consider this low priority - we need pulp and running, we can do a spike on this or an architectural decision to make sure we integrate correctly.

**Comment by fridex** [comment]
Based on the Pulp architecture, we can start monitoring Pulp from the Thoth side rather than vice versa - at least from the beginning.
