### ISSUE TITLE
renew cert status.thoth-station.ninja

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#1155]
Your certificate (or certificates) for the names listed below will expire in 10 days (on 21 Apr 21 06:45 +0000). Please make sure to renew your certificate before then, or visitors to your web site will encounter errors.

status.thoth-station.ninja

**Comment by harshad16** [comment]
Duplicate: https://github.com/thoth-station/thoth-application/issues/1203
closing the issue.
