### ISSUE TITLE
migrate graph-backup-job to the graph namespace

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#1166]
**Is your feature request related to a problem? Please describe.**
currently the graph-backup-job is executing the frontend namespace, to have consistency, it would be better to move it to the graph namespace.

**Describe the solution you'd like**
set the argocd app to graph namespace.

**Additional context**
Test it in stage as well.

**Comment by goern** [comment]
/priority importnat-soon
/unassign harshad16

@harshad16 is this something @Gregory-Pereira can work on?

**Comment by Gregory-Pereira** [comment]
Should all the other graph-related components be migrated to the graph namespace as well (ex: graph-refresh and the graph-syncs)?

**Comment by harshad16** [comment]
> Should all the other graph-related components be migrated to the graph namespace as well (ex: graph-refresh and the graph-syncs)?

no only graph concentrated apps.
component like graph-refresh and graph-sync connect with the services application and graph, so leaving them in serving  namespace makes sense.

we would like db concentrated app to be in db namespace, only graph-backup is such app which isn't in that namespace.
