### ISSUE TITLE
missing data in thoth/data/zero-prod/

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#1171]
**Describe the bug**
missing data in `thoth/data/zero-prod/` from all components except SLO-reporter prod which is running from stage. 
Manifests for prod seems good and using `zero-prod`, also configmaps in prod environment have correct value.

**To Reproduce**
1. Check `thoth/data/zero-prod/` on s3

**Expected behavior**
Data are stored in `thoth/data/zero-prod/` for all components

**Screenshots**

**Additional context**

**Comment by goern** [comment]
Which S3 endpoint is used? What are the access details?

**Comment by harshad16** [comment]
The s3 endpoint: https://s3-openshift-storage.apps.zero.massopen.cloud 
Please check the cerds in the core/overalay/zero-prod/secrets.yaml

**Comment by pacospace** [comment]
We can close this :)
