### ISSUE TITLE
Review all log configs and turn off json logging

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#1179]
As a Thoth Ops,
I want all logs to be NOT json formatted
so that I can read them a little easier

**Acceptance Criteria**
- [ ] logging default it text, not json 
- [ ] logging format is configurable via `.thoth.yaml`

/kind feature
/sig devops

**Comment by fridex** [comment]
Do we want to have this configurable in one place (thoth's config map) so that we can eventually turn on JSON logging if centralized logging will be present for the whole application (or disable it only for the test environment)?

**Comment by goern** [comment]
@fridex ja, sounds good, I updated the description, feel free to do so too ;)
