### ISSUE TITLE
ArgoCD did not sync slo-reporter-stage-prod after changes

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#1184]
**Describe the bug**
ArgoCD did not sync slo-reporter-stage-prod after changes https://github.com/thoth-station/thoth-application/pull/1173/files

**To Reproduce**
1. Check SLO reporter in aicoe-prod-bots on ocp4 cluster

**Expected behavior**
CM and Secret are updated.

**Screenshots**

**Additional context**

**Comment by pacospace** [comment]
> /kind bug
> /assign @tumido
> /label triage/needs-information

ocp4 is also maintained by ArgoCD on zero cluster?

**Comment by tumido** [comment]
@pacospace you're right, Operate First ArgoCD **doesn't** manage ocp4.

I don't even have access to your apps in the AICoE's Argo CD. Maybe @HumairAK can help?

**Comment by HumairAK** [comment]
The error is: 

```
ComparisonError: rpc error: code = Unknown desc = `kustomize build /tmp/https:__github.com_thoth-station_thoth-application/slo-reporter/overlays/zero-prod-ocp4-stage --enable_alpha_plugins` failed exit status 1: Error: failure in plugin configured via /tmp/kust-plugin-config-916241556; exit status 1: exit status 1
```

Can you confirm that you can build these manifests locally without issues?

**Comment by harshad16** [comment]
The manifests build in local, the secrets seem to be an issue here.
we have pr to update it, hopefully, that would fix this.
if not, we would have more information on the issue then.

**Comment by harshad16** [comment]
The issues seem to be resolved with the secrets update.
![prod-slo](https://user-images.githubusercontent.com/14028058/115561115-3fd0dc00-a283-11eb-8c54-f78e3401ea37.png)

Thanks for helping out everyone.
closing the issue, please reopen if you feel something is missing.
