### ISSUE TITLE
RFE: ODH z-stream sync job for Operate First - raise issue on failure and enable retriggering

### ISSUE THREAD

**Issue by tumido** [thoth-station/thoth-application#1195]
**Is your feature request related to a problem? Please describe.**
Sometimes it may happen that the job fails. Like today when we had a bug in the executed script.

**Describe the solution you'd like**
It would be nice if the bot can file an issue for us if such failure happens so we are aware of it.

It would be also nice if we can retrigger the updater via chat-ops in the issue. Something like `/retrigger` (similar to Prow's `/retest` message)

**Describe alternatives you've considered**
Monitoring ODH releases ourselves and checking if there's a PR created by the bot.

**Additional context**
https://github.com/operate-first/apps/pull/556

**Comment by harshad16** [comment]
This is no longer needed.
Operate-first has forked odh-manifests and maintain each version separately.
https://github.com/operate-first/odh-manifests

The z-stream sync job doesn't update anything in apps repo.
closing this issue.
Feel free to open if required in future.
