### ISSUE TITLE
RFE: ODH z-stream sync job for Operate First - please include changelogs from ODH verbatim

### ISSUE THREAD

**Issue by tumido** [thoth-station/thoth-application#1196]
**Is your feature request related to a problem? Please describe.**
We got caught by a surprise by some changes in ODH lately. Would it be possible to include their changelogs verbatim in the PR description please? 

**Describe the solution you'd like**
Pull changelogs from:
https://github.com/opendatahub-io/opendatahub-operator/releases
https://github.com/opendatahub-io/odh-manifests/releases

**Describe alternatives you've considered**
Remember to do it manually every time...

**Additional context**
https://github.com/opendatahub-io/odh-manifests/issues/412

**Comment by fridex** [comment]
@tumido you can adjust `.thoth.yaml` and provide `changelog_smart: false` in version manager to turn off smart changelogs and keep changelog verbatim:

https://github.com/thoth-station/kebechet/blob/c80d31428a00aadfda1179c633393959cc65bcc1/kebechet/managers/version/README.rst#generating-smart-release-logs

**Comment by tumido** [comment]
@fridex i don't think that would help, this is not a regular release pipeline. This pipeline is opening PRs like this https://github.com/operate-first/apps/pull/611 

basically upgrading operate first kfdef repo pointers based on releases in ODH repos - and I'd like to know the ODH changelog in the PR description in operate first...
