### ISSUE TITLE
Reduce the ttl for the workflow in thoth-backend-prod

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#1202]
**Describe the bug**
The workflow pods are staying on the namespace thoth-backend-prod, and hold the cpus 

![](https://files.slack.com/files-pri/T01SKMNPRUG-F020R0QPUSU/image.png)

we should reduce the TTL for the pods, to reduce the number of CPUs we hold.

**Comment by fridex** [comment]
> we should reduce the TTL for the pods, to reduce the number of CPUs we hold.

I think the TTL strategy cleans pods. Once a pod finishes, it should not occupy CPU. We keep pods for logs that are available to users.

**Comment by fridex** [comment]
BTW we should use logs that can be stored on ceph by argo using `archiveLogs: true`. That way we can provide logs to users for longer period of time and garbage collect pods sooner.

**Comment by harshad16** [comment]
I completely agree that the CPU is not occupied after the pods completion. However it seems from the cluster , the resource pressure can be observed, intuition is request resource is still considered by the cluster (not really sure on this part).
https://github.com/operate-first/support/issues/223
I have switched on the archivelogs for us and reduce the ttl. Also we would have logs from loki stagging (as that is set as well).
