### ISSUE TITLE
document method how to announce which data is available

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#1235]
**Is your feature request related to a problem? Please describe.**
As a Thoth User,
I want to read up on
or I want to get notified
so that I know which data sets the Thoth services work with

**Describe the solution you'd like**

[ ] Discuss this on Thoth Tech.

/triage needs-information
/kind feature
/sig user-experience

**Comment by fridex** [comment]
We already do so - see the release meeting notes.
