### ISSUE TITLE
Unable to submit cron workflows from Argo UI

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1248]
**Describe the bug**

I'm unable to submit a cron workflow via Argo UI. argo CLI client works

**To Reproduce**
1. Create a cron workflow, you can use an example in argo workflow docs: https://argoproj.github.io/argo-workflows/cron-workflows/
2. Go to Argo UI
3. Click on "Cron Workflows"
4. Select the newly created cron workflow
5. Click on the "+ Submit button"
6. See "Internal error" reported in Argo UI

**Expected behavior**

Argo UI can submit argo workflows.

**Additional context**

Not sure if this is a permission issue, if so, we do not need this capability in argo ui (when authentication is turned off).

**Comment by goern** [comment]
any update in this?

**Comment by harshad16** [comment]
need to bring this lifecycle in upcoming sprints

**Comment by harshad16** [comment]
This function is working in the prod and stage.
All required roles and role-bindings are in place
the UI list the created Cron workflow on the cron workflow list.
Thanks for opening the issue.
