### ISSUE TITLE
wait container fails when a cron workflow is created

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1249]
**Describe the bug**

`wait` container fails in cron workflow

```
time="2021-05-07T12:15:48.531Z" level=fatal msg="pods \"prescriptions-gh-release-notes-sx4f5\" is forbidden: User \"system:serviceaccount:thoth-test-core:default\" cannot get resource \"pods\" in API group \"\" in the namespace \"thoth-test-core\"\ngithub.com/argoproj/argo/errors.Wrap\n\t/go/src/github.com/argoproj/argo/errors/errors.go:88\ngithub.com/argoproj/argo/errors.InternalWrapError\n\t/go/src/github.com/argoproj/argo/errors/errors.go:71\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).getPod\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:655\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).GetMainContainerStatus\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:727\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).GetMainContainerID\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:744\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).CaptureScriptExitCode\n\t/go/src/github.com/argoproj/argo...
```

**To Reproduce**
1. Create a cron workfllow prescriptions-gh-release-notes
2. Check wait container (it will terminate after some time with the error shown above)
4. See the error

**Expected behavior**

`wait` container should wait until the `main` container finishes.

**Comment by fridex** [comment]
I will soon provide a reproducer for this.

**Comment by fridex** [comment]
> I will soon provide a reproducer for this.

https://github.com/thoth-station/thoth-application/pull/1250/ can be used as a reproducer

**Comment by harshad16** [comment]
This is PR had solved this issue: https://github.com/thoth-station/thoth-application/pull/1724
forgot to attach this issue to the pr.
closing the issue, as we had already tested this.
