### ISSUE TITLE
Expose information about available packages in Python

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1280]
**Is your feature request related to a problem? Please describe.**

In Python, it is not always clear what packages a Python artifact exposes. It would be great if we have a mechanism to show what Python packages are available in a certain Python package release.

**Describe the solution you'd like**

- [x] extend thoth-solver so that it computes information about packages available - https://github.com/thoth-station/solver/pull/701
- [x] adjust syncing logic of thoth-solver results to have package information available in the database in the queryable form
   - [x] adjust also database schema
- [ ] expose information about Python imports on user-api

It might be good to start with a root package for simplicity - that is probably the most wanted use-case.

Later, other client tools can integrate - such as jupyterlab-requirements (https://github.com/thoth-station/jupyterlab-requirements/issues/270)

**Comment by goern** [comment]
@fridex what is the priority of this?

**Comment by fridex** [comment]
This is @tlegen-k's intern project description.

**Comment by codificat** [comment]
As per today's review, this is already implemented
/close
Thanks!
