### ISSUE TITLE
Onboard OSPO

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#1283]
Onboard the OSPO team to utilize Thoth Services.

- [ ]  Provide help with setup Kebechet
- [ ]  Provide help with setup AICoE-CI
- [ ]  Provide help with onboarding on prow.

**Comment by harshad16** [comment]
We had a call with OSPO team they would like to use our services. 
Thanks, @oindrillac for setting the call-up.

**Comment by cdolfi** [comment]
https://github.com/OSAS/sandiego link to repo. Let me know if anyone else needs access

**Comment by goern** [comment]
> https://github.com/OSAS/sandiego link to repo. Let me know if anyone else needs access

/me
