### ISSUE TITLE
Verify consistency of producing data in prod for advises

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1331]
**Describe the bug**

This is not really a bug, but rather a tracker to make sure our data are consistent and can be used to serve their purpose in prod environment:

- [ ] make sure all the solvers are in version >=1.8.0
- [ ] make sure all the runtime environments we want to recommend have the corresponding solver installed (https://github.com/thoth-station/thoth-application/blob/master/docs/thoth_s2i_procedure.md)
- [ ] make sure package-releases job is running (not a hard requirement, they can be suspended anytime the system will recover its state)
- [ ] make sure graph-refresh job is running (not a hard requirement, they can be suspended anytime the system will recover its state)
- [ ] make sure https://github.com/thoth-station/storages/issues/2308 is fixed and new management-api, graph-sync is available in deployment to trigger "force" sync logic
- [ ] **make sure investigator is scheduling solvers and revsolvers (!!! this is a hard requirement to keep deployment up2date)**

The system can recover from failures (e.g. ceph is down, postgres is down, ...) but the requirement for the system when it is up (or is brought up) is the fact investigator is scheduling solver and revsolver based on messages seen in the system. If solvers or revsolvers are not scheduled, the corresponding message should not be acked (I think we have this in place CC @KPostOffice).

**Comment by KPostOffice** [comment]
> The system can recover from failures (e.g. ceph is down, postgres is down, ...) but the requirement for the system when it is up (or is brought up) is the fact investigator is scheduling solver and revsolver based on messages seen in the system. If solvers or revsolvers are not scheduled, the corresponding message should not be acked (I think we have this in place CC @KPostOffice).

@fridex Yes, this is in place. https://github.com/thoth-station/investigator/blob/9419a514d8f20f8eed326c5821696d6ea44bd103/thoth/investigator/common.py#L286 and if message raises exception we do not ack

**Comment by fridex** [comment]
> > The system can recover from failures (e.g. ceph is down, postgres is down, ...) but the requirement for the system when it is up (or is brought up) is the fact investigator is scheduling solver and revsolver based on messages seen in the system. If solvers or revsolvers are not scheduled, the corresponding message should not be acked (I think we have this in place CC @KPostOffice).
> 
> @fridex Yes, this is in place. https://github.com/thoth-station/investigator/blob/9419a514d8f20f8eed326c5821696d6ea44bd103/thoth/investigator/common.py#L286 and if message raises exception we do not ack

Awesome, thanks Kevin. 👍🏻

**Comment by fridex** [comment]
We are ingesting data in the stage which will be pushed to the prod environment. Hence, closing this issue.

/close
