### ISSUE TITLE
Automated Go Build Releases 

### ISSUE THREAD

**Issue by HumairAK** [thoth-station/thoth-application#1362]
Relevant: https://github.com/operate-first/opfcli/issues/5

**Describe the solution you'd like**

We have go code [here](https://github.com/operate-first/opfcli). For this, we would like to automatically generate a new release (with a binary build) when we push a new tag. 

**Describe alternatives you've considered**

We have considered using Go Actions to accomplish this, but since rest of our ci is configured via thoth/prow tooling, we feel it would be better to be consistent here.

**Comment by HumairAK** [comment]
This issue is a bit blocking, and we are considering how to accomplish this in a timely fashion, we are thinking the following: 

1. if this is a simple task w/ documentation, we can do this if we can be pointed to the right locations/docs etc. 
2. we can wait for someone from thoth team to do this, but in the interim we can implement a go action and use that while we wait

wdyt?

**Comment by harshad16** [comment]
Goals:


Reference:
1. https://github.com/operate-first/opfcli/blob/main/.github/workflows/release.yml
2. https://github.com/operate-first/opfcli/tree/v0.1

**Comment by goern** [comment]
@Gregory-Pereira please label accordingly if you are working on an issue

/lifecycle active
