### ISSUE TITLE
mi-scheduler failed job logs not kept

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/thoth-application#144]
**Describe the bug**
Newest logs for mi-scheduler jobs are not kept.

**To Reproduce**
1. Log into the psi cluster and use the 'thoth-test-core' namespace

2. `$ oc logs mi-scheduler <TAB autocompletion>`
`mi-scheduler-1594983600-vznq5  mi-scheduler-1594987200-kcxds`

3. The `mi-scheduler-1594983600-vznq5` is nearly week old, the second one is unable to be retrieved.
(the jobs are being launched every hour)

**Expected behavior**
According to setup, last 4 logs of failed jobs should be kept https://github.com/thoth-station/thoth-application/blob/2f7b1c17b33369d8ec060b3c5464903862b91c73/mi-scheduler/base/cronjob.yaml#L13

**Comment by goern** [comment]
@KPostOffice

**Comment by xtuchyna** [comment]
Something was fixed in Openshift, seems like everything works rn and the logs are being kept. Closing the issue
