### ISSUE TITLE
how to decrypt?

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#1513]
While doing a `` I encountered `Error: trouble converting file './secrets.enc.yaml' to a resource: trouble decrypting file ./secrets.enc.yaml: Error getting data key: 0 successful groups required, got 0`.

How do I decrypt? Which keys are required?

My key `34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34` is listed in https://github.com/thoth-station/thoth-application/blob/master/.sops.yaml its expiration date is 2022-04-14. I assume all this is good. Which key server is used by ksops to get keys?

/kind question

**Comment by harshad16** [comment]
while trying to encrypt, this shows up: 
```
Could not generate data key: [failed to encrypt new data key with master key "34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34": could not encrypt data key with PGP key: golang.org/x/crypto/openpgp error: key with fingerprint 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34 is not available in keyring and could not be retrieved from keyserver; GPG binary error: exit status 2]
```

seems like sops keyserver is to be updated.

**Comment by goern** [comment]
I have reset the expire data and send the key to that key server, could you please try again?

**Comment by harshad16** [comment]
It works now, I can update all the secrets.

**Comment by goern** [comment]
thx!!
