### ISSUE TITLE
Provide information interesting to users on status.thoth-station.ninja

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1561]
**Describe the bug**

As a Thoth user, I would like to know if Thoth is up and the service is usable. As of now, we provide the following information to users:

![Screenshot_2021-06-04_09-34-22](https://user-images.githubusercontent.com/880687/120764006-10ff8400-c518-11eb-9496-9294d47653c8.png)

If I take a look at other status pages, such as:

* https://www.githubstatus.com/
* https://status.gitlab.com/

... and others, they provide information to users so that users know if they can use the service. Any background aggregation/task info is not provided - it can be confusing to users.

**Expected behavior**

I tried to address this issue in https://github.com/thoth-station/statusfy/pull/1 but it looks like it was not propagated to the status page.

**Comment by goern** [comment]
@fridex please check the current state at https://status.thoth-station.ninja/

**Comment by fridex** [comment]
What about including also build analysis, and container image analysis?

**Comment by fridex** [comment]
As we have students working on Amun, it might be also a good idea to include Amun there.

**Comment by goern** [comment]
ja sure, the PR you send was good, I think I just mis-rebased it locally.... go ahead and add what you think is useful

**Comment by fridex** [comment]
Looking at the other status pages, we should probably have features we provide to users rather than having components stated.
