### ISSUE TITLE
Store GitHub targets more specifically, more scalabe

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/thoth-application#1630]
**User story**

As a `mi` dataset requester,
I want to specify github target and its entities,
so that I can simply make PR to the global configmap that will have it registered.

**Additional context**
When aggregating data for `mi` repositories (either for general `mi` inspection or a `kebechet` oriented analysis), the repositories and organization names are stored here https://github.com/thoth-station/thoth-application/blob/master/mi-scheduler/base/configmaps.yaml

However, this is not scalable and user-specific, because everything is stored inside the comma-sep styled string (it is then parsed in `mi-scheduler`). This also does not allow to specify entity individually for repo/org.

With recent changes to the `schedule` method in `common` for `mi` it is possible to specify repos with specific entities, so the only thing remains to store the list of tuples [ (repo/ord, entities), ... ] to the json file and load it as a configmap.
 

**Acceptance Criteria**
- [ ] Migrate the current configmap to `json` file.
- [ ] Load json file into the into the mi-workflows cronjob as a configmap ref
- [ ] Check that mi schedules all the specific workflows correctly

**Linked epics / issues**
https://github.com/thoth-station/mi-scheduler/pull/139

**Comment by goern** [comment]
Why not create a config file that is read by MI and processed by a method. The config file would be an input the method, the purpose of the method is to create a dict, the dict is what MI should aggregate...

```
aggregate:
  - "org1/repo1": [ "PR", "issue" ]
  - "org1/repo2": [ "PR, issue" ]
  - "org1/repo3": ["PR"]
  - "org2/repo1: ["PR", "issue"]
  - "org2/repo2": ["PR"]
```

The config for this could look like:
```
aggregate:
  orgs:
    - "org1"
    - "org2"
  entities:
    - PR
    - issue
  excludeRepos:
    - repo3
  repos:
    - org1/repo3:
    - org2/repo2
    entities:
      - PR
```

pretty much like what Tide is doing at https://github.com/thoth-station/thoth-application/blob/master/prow/overlays/cnv-prod/config.yaml#L162

**Comment by goern** [comment]
@xtuchyna are you working on this? if so, please lifecycle it, and set a prio

/priority backlog

**Comment by codificat** [comment]
> /priority-important soon

I will take that as
/triage accepted
