### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1653]
**Is your feature request related to a problem? Please describe.**

$SUBJ for all the repos in the organization.

**Comment by goern** [comment]
+1 I thin github has a copy-n-paste doc on how to do it

/priority important-soon

**Comment by fridex** [comment]
Maybe this one? https://github.com/github/renaming#renaming-existing-branches

**Comment by fridex** [comment]
- [ ] pick one repo and test all the integrations (aicoe-ci, kebechet, ...)
- [ ] if all goes well with integration, rename remaining repositories in thoth-station org
