### ISSUE TITLE
hardware endpoint delivers broken data

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#1662]
**Describe the bug**
`curl -X GET "https://api.moc.thoth-station.ninja/api/v1/hardware" -H  "accept: application/json"` delivered some broken data

**To Reproduce**
1. `curl -X GET "https://api.moc.thoth-station.ninja/api/v1/hardware" -H  "accept: application/json"`

**Comment by fridex** [comment]
This endpoint just gets what hardware configurations are available in the database. As we do not have many, it returns only few results (values set to `null` for unknown entries). Is there any other requirement for the endpoint?

Anyway, I wonder if we want to support such an endpoint on user-api and have this information exposed to users.
