### ISSUE TITLE
activeDeadlineSeconds

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/thoth-application#1664]
**Related dependencies**
Related to #1663 

**Description**
When specifying timeout for workflows for `mi-scheduler`, I first tried to do it under the `spec` and `mi-workflow` template scope
( https://github.com/thoth-station/thoth-application/blob/d381a0cda6c597a4c9c012fbb89e28f06c5ce8f9/mi-scheduler/base/argo-workflows/mi-workflow-template.yaml#L11 and https://github.com/thoth-station/thoth-application/blob/d381a0cda6c597a4c9c012fbb89e28f06c5ce8f9/mi-scheduler/base/argo-workflows/mi-workflow-template.yaml#L15 )

however, this did not work and the only right way was to do it under the `analyse` step declaration https://github.com/thoth-station/thoth-application/blob/d381a0cda6c597a4c9c012fbb89e28f06c5ce8f9/mi-scheduler/base/argo-workflows/mi-workflow-template.yaml#L40 

/kind documentation

**Comment by goern** [comment]
@xtuchyna what is the status of this?

/remove-triage needs-information

**Comment by goern** [comment]
@xtuchyna are you working on this? if so, please lifecycle it, and set a prio

/priority backlog

**Comment by xtuchyna** [comment]
This was already added. Closing
