### ISSUE TITLE
GitHub team permission assignments sync

### ISSUE THREAD

**Issue by tumido** [thoth-station/thoth-application#1703]
**Is your feature request related to a problem? Please describe.**
When a new repo is created in an org, I'd like it to be seeded with team membership - like granting sourceops admin permissions and some other team write permissions etc.

**Describe the solution you'd like**
Something that would execute a script when new repo is created, fetching data from some config.

**Describe alternatives you've considered**

My current workaround syncing all repos at once:
```
#!/bin/sh

CREDS="tumido:TOKEN"
ORG=$1
TEAM=$2
ROLE=$3

ALL_REPOS=`curl -s -u "$CREDS" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/$ORG/repos?per_page=1000 | jq -r .[].full_name`

echo "'$TEAM' is assigned '$ROLE' on:"

for repo in $ALL_REPOS; do
    curl -s -u "$CREDS" -X PUT -d "{\"permission\": \"$ROLE\"}" https://api.github.com/orgs/$ORG/teams/$TEAM/repos/$repo
    echo "- $repo'"
done
```

like: 
```
$ ./seed_membership.sh operate-first sourceops admin
'sourceops' is assigned 'admin' on:
- operate-first/continuous-deployment'
- operate-first/operate-first.github.io'
...

$ ./seed_membership.sh operate-first contributors-core triage
'contributors-core' is assigned 'triage' on:
- operate-first/continuous-deployment'
...

$ ./seed_membership.sh operate-first custodians push
'custodians' is assigned 'push' on:
- operate-first/continuous-deployment'
- operate-first/operate-first.github.io'
```

**Additional context**
New repo was created and sesheta didn't have access to it.

**Comment by tumido** [comment]
btw, this seems to be a chicken and egg problem, since the automation would need to have access to the repo to set the access to the repo though :smile:

**Comment by tumido** [comment]
Probably related to: https://github.com/thoth-station/thoth-application/pull/1510

**Comment by goern** [comment]
@tumido can we close this with the use of paribolos?

**Comment by tumido** [comment]
yes, we can close this one. Peribolos is what we need :slightly_smiling_face:
