### ISSUE TITLE
Automatically delete branches created by Kebechet update

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1722]
**Describe the bug**

As a user of Thoth, I would like to have branches created by Kebechet on automatic package updates (known as `kebechet-automatic-update`) automatically deleted. Otherwise, next pull requests with package updates won't be created.

**To Reproduce**
1. See https://github.com/thoth-station/prescriptions-gh-release-notes-job/pull/18

**Expected behavior**

Delete `kebechet-automatic-update` branch automatically once a pull request from this branch is merged.

**Comment by fridex** [comment]
CC @harshad16 is this something CI can do for us?

In another case, we could extend kebechet logic to detect merged PRs and delete the branch.

**Comment by harshad16** [comment]
yes frido, we can have this in ci 
will add it this sprint

**Comment by fridex** [comment]
> yes frido, we can have this in ci
> will add it this sprint

Awesome, thanks 👍🏻

**Comment by goern** [comment]
As Kebechet created the branch, should it be responsible for cleanup after the PR got merged? Doing it via CI feels wrong, as CI should not maintain source?!
