### ISSUE TITLE
Retrieve a list of packages that were submitted to Thoth

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1763]
**Is your feature request related to a problem? Please describe.**

As an operator of Thoth, I would like to get a list of packages that were submitted to Thoth with an advice request.

**Describe the solution you'd like**

- iterate over adviser documents stored on Ceph and obtain a list of packages from Pipfile
- check this for prod/stage/prod environments

**Comment by fridex** [comment]
Later, this can be extended so that we do package usage analyses.

**Comment by pacospace** [comment]
is ok to have a notebook here? and is this required https://github.com/thoth-station/reporter/issues/218?

**Comment by fridex** [comment]
> is ok to have a notebook here and derive the initial list of packages? and is this required or duplicate of this [thoth-station/reporter#218](https://github.com/thoth-station/reporter/issues/218)?

This is about aggregating direct dependencies from Pipfile that were submitted to thoth so we can support #1764. It can be turned into a notebook if you want 👍🏻

**Comment by pacospace** [comment]
> > is ok to have a notebook here and derive the initial list of packages? and is this required or duplicate of this [thoth-station/reporter#218](https://github.com/thoth-station/reporter/issues/218)?
> 
> This is about aggregating direct dependencies from Pipfile that were submitted to thoth so we can support #1764. It can be turned into a notebook if you want 👍🏻

Sure! I think we can resue notebook in thoth-station/datasets for this and provide the list of packages. 

Should we place the list in init-job and add an env variable to select a list of packages, either the data-science pacakges (https://github.com/thoth-station/init-job/blob/master/hundredsDatasciencePackages.yaml) or the new one called `thothMostUsedPackages.yaml`

**Comment by fridex** [comment]
> Should we place the list in init-job and add an env variable to select a list of packages, either the data-science pacakges (https://github.com/thoth-station/init-job/blob/master/hundredsDatasciencePackages.yaml) or the new one called `thothMostUsedPackages.yaml`

I would wait for the ingestion - we might adjust the data science packages listing, but maybe an additional configuration of the system will be required to make sure we have the correct packages listed.

**Comment by harshad16** [comment]
We currently  run init-job via workflow, in where we select which all workflows to execute, like
- schema initial 
- data science package solver schedule.

how about we have multiple lists for different thoth deployment environment 
and configure them via this option of selecting different workflow.

For example, if an environment doesn't require, 100datasciencpackaeg
on deployment, we would deselect that from init-job workflows.
wdyt ?

**Comment by fridex** [comment]
Handled in https://github.com/thoth-station/thoth-application/issues/1764

/close
