### ISSUE TITLE
Start ingestion in stage for relevant packages

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1764]
**Is your feature request related to a problem? Please describe.**

To support our planned efforts, we should start (re)ingestion in stage environment.

**Describe the solution you'd like**

- [x] aggregate packages that should be ingested
  - [x] aggregate ODH packages - https://github.com/fridex/devnull/blob/master/rhods_nb_packages.txt
  - [x] ray packages - https://github.com/fridex/devnull/blob/master/ray_pkgs.txt
  - [x] aggregate packages from adviser requests done to the stage system- https://github.com/thoth-station/thoth-application/issues/1763
- [x] create backup of the current stage database
  - [x] make sure the backup is moved out of the standard location so that graph-backup-job does not delete it when new dumps are created
- [x] announce this procedure on chat (outage)
- [x] ~~put maintenance announcement on https://status.thoth-station.ninja/~~
- [x] scale user-api to 0 to make sure no requests are comming to the system
- [x] turn off ingestion, make sure queues are empty and no workflows are scheduled
- [x] make sure only ubi8-py38 solver is enabled
- [x] clear stage database content
- [x] initialize database schema schema 
- [x] install [solver rules](https://github.com/thoth-station/init-job/blob/master/solver_rules.json)
- [x] make sure [hundreds data science packages](https://github.com/thoth-station/init-job/blob/master/hundredsDatasciencePackages.yaml) are **NOT** scheduled for solving
- [x] scale user-api up to 1
- [x] schedule solving packages for ubi8-py38
- [x] schedule solving packages for fedora-34-py39 (after ubi8-py38 is solved)
- [x] make sure the system is up

**Comment by codificat** [comment]
From today's call: this is essentially done.
It would be valuable to document all this, for which a new issue will be created.
Keeping this open until everything is verified and the follow-up issue exists

**Comment by goern** [comment]
can this be closed?

**Comment by fridex** [comment]
+1, I think this can be closed

/close
