### ISSUE TITLE
schema update blocked due backoff limit reached.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#1766]
**Describe the bug**
we have been trying to update the graph db schema, to upgrade the alembic version along with the update of the schema.
It would the alerts which are getting prompted due to the schema difference.

The method to do the schema update is to schedule the graph-schema-update job from management-api.

Scheduling the graph-schema-update job in prod cluster result in `Job has reached the specified backoff limit`

**Comment by harshad16** [comment]
This is work in progress, we have been trying to fix this.
Had experimented with the backofflimit and activedeadlineSeconds params, however that didn't help much.
Notice that the db size has grown due to this.
As we don't want to disrupt the prod environment.

we have moved the fixing to stage environment.
Have scheduled the job: https://console-openshift-console.apps.ocp4.prod.psi.redhat.com/k8s/ns/thoth-infra-stage/jobs/graph-update-schema-210628053107-4ac901e8f9df32ae
will monitor it and then advance to prod.

**Comment by fridex** [comment]
Is there any exception reported? Or is this solely issue caused by a timeout as the job is running too long?

**Comment by harshad16** [comment]
There was no exception reported.
just the backofflimit reached error on the job description can be seen
on further investigation, it was found that the alembic update were causing data increase and decrease
the update job was terminating and getting retriggered, which caused the fluctuation.
more details:
https://chat.google.com/room/AAAAVjnVXFk/0vZpjizM0fs

**Comment by harshad16** [comment]
This was fixed by separating the alembic version and updated the database.
Thanks for everyone's help.
