### ISSUE TITLE
Use Python package index labels to support resolution engine decisions

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1767]
**Is your feature request related to a problem? Please describe.**

As Thoth, I would like use labels available on Python package indexes provide by Pulp to automatically adjust resolution process based on the labels associated with the package index.

An example can be a Python package index that has AVX2 enabled builds. In such a case, Thoth can automatically detect this index and, based on labels associated with this index, suggest using AVX2 enabled builds of Python packages published there (if CPU used supports AVX2).

**Describe the solution you'd like**

- extend the database schema and associate labels with Python package indexes
- extend pulp-pypi-sync-job to store labels associated with the package index
- unify the labelling system - propose "standardized labels" that would be used on package indexes and on the resolution engine side

**Comment by goern** [comment]
@fridex is this a feature we want to push? or just leave it in the backlog?

**Comment by fridex** [comment]
Let's keep in in the backlog. We do not have many packages on the Pulp instance yet to support this.
