### ISSUE TITLE
Document authenticated/non authenticated workflows and the requirement for a token, have a ADR like doc

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#1787]
**Is your feature request related to a problem? Please describe.**
As Thoth User/Developer,

I would like to know more about authenticated/non authenticated workflows and the requirement for a token

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Related-To: https://github.com/thoth-station/thoth-application/issues/1112

**Comment by fridex** [comment]
Related information can be found in https://www.youtube.com/watch?v=Nvu5MsUG7L4
