### ISSUE TITLE
[2pt] Provide a mechanism to label container images produced by AICoE-CI/Thoth

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1788]
**Is your feature request related to a problem? Please describe.**

As Thoth, I would like to resolve software specific for container images (runtime environments) as produced by AICoE-CI/Thoth. To support this, we need to have a mechanism that can inject container image information into the container image itself.

As of now, we use environment variables `THOTH_S2I_NAME`/`THOTH_S2I_VERSION` and `IMAGE_NAME`/`IMAGE_TAG` to propagate container image information. Let's sync on what these environment variables should hold and how they will be handled/injected during the build process so that resolver can guide on software packages resolved specifically for these runtime environments (container images).

- [x] consolidate what `THOTH_S2I_NAME`/`THOTH_S2I_VERSION`/`IMAGE_NAME`/`IMAGE_TAG` hold and their semantics 
- [x] capture thoth base image used in environment variables - capture thoth base image name+version/tag https://github.com/thoth-station/s2i-thoth/blob/master/ubi8-py38/Dockerfile#L6-L7
- [x] if the image is an extension to a thoth base image, capture its name and version/tag besides thoth base image information in environment variables https://github.com/AICoE/aicoe-ci/pull/173
- [ ] add predictable stack name and version as a label/ENV
- [x] the build container images should be analyzed by Thoth on management API on each release https://github.com/AICoE/aicoe-ci/pull/173
- [x] consolidate how the version information is injected into container images https://github.com/thoth-station/storages/blob/1ce78b4870397517080f7026c15fd01f0e8cdccc/thoth/storages/graph/postgres.py#L5688

**Describe the solution you'd like**

Pass container image name and container image version (tag) in container images produced so that Thoth can give guidance on these runtime environments.

**Comment by fridex** [comment]
This one is already implemented on the backend side. Once container images built by AICoE-CI provide ``THOTH_S2I_NAME`` and ``THOTH_S2I_VERSION`` the backend will automatically use this information.

**Comment by goern** [comment]
any updates on this? do we consider it done?

**Comment by harshad16** [comment]
/remove-lifecycle frozen 
This currently been a tracker issue.

**Comment by harshad16** [comment]
The issue is resolved with the part executed in s2i-thoth, management-api, package-extraction and thoth-storages.
closing the issue.
