### ISSUE TITLE
Yanked releases support

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1795]
**Is your feature request related to a problem? Please describe.**

As a consumer of Thoth services, I would like to make sure versions that I am using are not yanked on PyPI.

**Describe the solution you'd like**

Implement a yanked release support.

**Comment by goern** [comment]
Shall this be a `thamos` feature, Tekton task? part of GitHub App and PR comment?

**Comment by fridex** [comment]
> Shall this be a `thamos` feature, Tekton task? part of GitHub App and PR comment?

A periodic job run in the backend that checks yanked releases on PyPI and marks them in the database as yanked so we do not recommend them (unless stated explicitly in direct dependencies listing).

**Comment by harshad16** [comment]
it can be a part of package-update

**Comment by goern** [comment]
@fridex is this a feature we want for an MVP?
