### ISSUE TITLE
investigator message metrics exporter in thoth-infra-prod is not scraped

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#1805]
**Describe the bug**
investigator message metrics exporter in thoth-infra-prod is not scraped

**To Reproduce**
1. Go to http://investigator-message-metrics-thoth-infra-prod.apps.zero.massopen.cloud/metrics and check for metric called `message_count_by_version_total`
2. Go to Prometheus prod and check for the same metric.

In alternative check targets and verify that the target route for investigator message metrics is missing.

![Screenshot from 2021-07-07 09-47-16](https://user-images.githubusercontent.com/27498679/124720381-63153a00-df08-11eb-851d-4225e96bbfd4.png)

**Expected behavior**
Metrics are scraped by Prometheus

**Screenshots**
n/a

**Additional context**
For Metrics that are present in both endpoints we need to make sure that not both, and esp not the one having 0, get into Grafana. This could be done using the right labels on the dashboard query.

**Comment by harshad16** [comment]
Fixed with this commit https://github.com/thoth-station/thoth-application/commit/a0042bf71ef91463318b81b643f5b0019ab84f51
Metric is now available http://prometheus-portal-thoth-infra-prod.apps.zero.massopen.cloud/targets
Thanks for the issue.
