### ISSUE TITLE
Make ingesting "unsolved" packages configurable

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1823]
**Is your feature request related to a problem? Please describe.**

As a Thoth administrator, I would like to adjust what packages are ingested into the system. As of now, we automatically analyze packages that are not solved yet in "unsolved" workflow. To have more fine-grained control on which packages can be recommended by the system, we should have the automatic ingestion of unsolved packages configurable.

**Describe the solution you'd like**

Create a configmap entry that can turn off or on ingestion of unsolved packages.

**Comment by fridex** [comment]
It would be great to have this available to make sure we analyze only packages we want to have analyzed and the system will keep up with releases.

/priority important-soon

**Comment by harshad16** [comment]
already implemented in solver rules

**Comment by fridex** [comment]
See docs: https://thoth-station.ninja/docs/developers/adviser/deployment.html#configuring-solver-rules

/cloes
