### ISSUE TITLE
reconfigure triage-party routes

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#1827]
**Is your feature request related to a problem? Please describe.**
Reconfigure triage-parts routes to
- [ ] increase timeout to 45sec, see https://docs.openshift.com/container-platform/4.7/networking/routes/route-configuration.html#nw-route-specific-annotations_route-configuration
- [ ] use ACME Cert management, like https://github.com/thoth-station/thoth-application/pull/1782
  
**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

/assign @Gregory-Pereira 
/milestone 2021.07.19

**Comment by Gregory-Pereira** [comment]
Routes have been annotated and code change to use TLS ACME has been done. PR coming soon.
