### ISSUE TITLE
Monitor `mi` workflows

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/thoth-application#1839]
**Is your feature request related to a problem? Please describe.**
Whenever all the workflows finish, I would like to see how much of them passed and how much of them failed. Can this be done directly via ArgoCD ? Or could this information be extracted from `workflow-controller` ?

**User story**
As a `thoth/mi` workflows maintainer,
I want to see how many workflows were finished successfully and how many of them failed,
so that I have an overall view how the data aggregation went.

**Goals**
- be able to see in instant how many workflows succeeded or failed after data extraction 
- be able to see workflow names
- Combined with https://github.com/thoth-station/thoth-application/issues/1835 this would provide a nice quick overview on data aggregation. 

**Acceptance Criteria**
- [ ] find out how metrics work and how can they be viewed / stored so that the human can easily access/read them
- [ ] define here how is it going to be accessed: ....
- [ ] look into the metrics documentation and see what attributes can be specified for workflow
- [ ] select the desired attribute: `....`
- [ ] Create PR, merge
- [ ] Launch aggregation and check metrics later

**Categorization**
/kind feature
not a spike
/kind demo

**Due date**
@goern wdyt?
/priotity important-soon

**References**
Argo worfklows metrics: https://argoproj.github.io/argo-workflows/metrics/
*adviser* example worklfow metrics: https://github.com/thoth-station/thoth-application/blob/9f2a75ca19394da2b6cdd51413da72338da45402/adviser/base/argo-workflows/advise.yaml#L9

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> Whenever all the workflows finish, I would like to see how much of them passed and how much of them failed. Can this be done directly via ArgoCD ? Or could this information be extracted from `workflow-controller` ?

Thans @xtuchyna, ArgoCD does not handle workflows, that is Argo. There are some default metrics gathered for workflows from workflow-controller by default. Then other customized ones can be introduced, see for example: https://github.com/thoth-station/thoth-application/blob/9f2a75ca19394da2b6cdd51413da72338da45402/adviser/base/argo-workflows/advise.yaml#L9

**Comment by pacospace** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > Whenever all the workflows finish, I would like to see how much of them passed and how much of them failed. Can this be done directly via ArgoCD ? Or could this information be extracted from `workflow-controller` ?
> 
> Thans @xtuchyna!
> 
> ArgoCD does not handle workflows, that is Argo. There are some default metrics gathered for workflows from workflow-controller by default. Then other customized ones can be introduced, see for example:
> 
> https://github.com/thoth-station/thoth-application/blob/9f2a75ca19394da2b6cdd51413da72338da45402/adviser/base/argo-workflows/advise.yaml#L9

@xtuchyna here docs on Argo worfklows metrics: https://argoproj.github.io/argo-workflows/metrics/

@harshad16 do we gather metrics from workflow controller in `thoth-test-core` in `zero-test`? I don't see them in https://prometheus-portal-opf-monitoring.apps.zero.massopen.cloud/graph?g0.expr=argo_workflows_count%7Bnamespace%3D%22thoth-test-core%22%7D&g0.tab=1&g0.stacked=0&g0.range_input=1h

**Comment by xtuchyna** [comment]
triage/accepted

**Comment by harshad16** [comment]
we dont gather metrics in the zero-test , if this is need we should create another process for it

**Comment by xtuchyna** [comment]
@Gkrumbach07 @goern  this could be potentially `sig/user-experience` if the metrics would be publicly available
