### ISSUE TITLE
slo-reporter stage-prod look for location of advise reporter documents which are stored in a different place

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#1843]
**Describe the bug**
slo-reporter stage-prod look for location of advise reporter documents which are stored in a different place

We are not using default thoth bucket but the one from rook in prod, should we go back to normal bucket? (see additional context below.

**To Reproduce**
1. Check SLO-reporter repo, where some tables are empty.

**Expected behavior**
Data are correctly identified by slo-repoter stage-prod.

**Screenshots**

**Additional context**
nominal prod bucket -> https://s3-openshift-storage.apps.zero.massopen.cloud/ (where SLO reporeter is looking for data)
backup for issue in Operate First Ceph -> http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local (where advise reporter prod is storing data)

**Comment by harshad16** [comment]
until we complete our data ingestion we would keep the user-api down
in return, there won't be any advice.

**Comment by pacospace** [comment]
@harshad16 can we move back to nominal prod bucket -> https://s3-openshift-storage.apps.zero.massopen.cloud/ (where SLO reporeter is looking for data) in prod?
