### ISSUE TITLE
descriptions are missing on quay.io

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#1851]
**Describe the bug**
most of the container images at https://quay.io/organization/thoth-station are missing a good description.

**To Reproduce**
1. Go to 'https://quay.io/organization/thoth-station'
2. Click on 's2i-minimal-notebook'
3. See problem

**Expected behavior**
a more meaningful description is available

Cc: @riekrh

**Comment by harshad16** [comment]
attach url of each github repo

**Comment by harshad16** [comment]
All the images under the thoth-station quay have now been added with GitHub links. 
Some of them fall under the following sets, what should we do with them?

**Not Known**:
https://quay.io/repository/thoth-station/actions-runner
https://quay.io/repository/thoth-station/adviser-cached
https://quay.io/repository/thoth-station/f31-python37
https://quay.io/repository/thoth-station/github-actions-runner
https://quay.io/repository/thoth-station/kubectl
https://quay.io/repository/thoth-station/python-36-centos7
https://quay.io/repository/thoth-station/rabbitmq
https://quay.io/repository/thoth-station/redis
https://quay.io/repository/thoth-station/workflow-reconcilers
https://quay.io/repository/thoth-station/community-tooling

**Deprecated**(source doesn't existed anymore):
https://quay.io/repository/thoth-station/s2i-thoth-f31-py37
https://quay.io/repository/thoth-station/s2i-thoth-f32-py38
https://quay.io/repository/thoth-station/solver-fedora-29-py36
https://quay.io/repository/thoth-station/solver-fedora-29-py37
https://quay.io/repository/thoth-station/solver-fedora-30-py36
https://quay.io/repository/thoth-station/solver-fedora-30-py37
https://quay.io/repository/thoth-station/solver-fedora-31-py37
https://quay.io/repository/thoth-station/solver-fedora-31-py38
https://quay.io/repository/thoth-station/solver-fedora-32-py37
https://quay.io/repository/thoth-station/solver-fedora-32-py38
https://quay.io/repository/thoth-station/thoth-ops-container
https://quay.io/repository/thoth-station/thoth-srcops
https://quay.io/repository/thoth-station/thoth-coala

**Archived**(source exists but archived):
https://quay.io/repository/thoth-station/build-analyzer
https://quay.io/repository/thoth-station/cleanup-job
https://quay.io/repository/thoth-station/graph-sync-scheduler
https://quay.io/repository/thoth-station/package-analyzer
https://quay.io/repository/thoth-station/prescriptions-gh-release-notes-job
https://quay.io/repository/thoth-station/prescription-sync-job
https://quay.io/repository/thoth-station/result-api
https://quay.io/repository/thoth-station/solver-project-url-job
https://quay.io/repository/thoth-station/thoth-pytest-f31-py37
https://quay.io/repository/thoth-station/workload-operator

cc: @goern @fridex

**Comment by fridex** [comment]
> https://quay.io/repository/thoth-station/adviser-cached

This can be removed, it was an experiment when part of the dependency graph was embedded into adviser using sqlite.

> https://quay.io/repository/thoth-station/f31-python37

This can be removed as well.

> https://quay.io/repository/thoth-station/kubectl

This one is used by Amun (ex. obtaining logs from pods):

https://github.com/thoth-station/thoth-application/blob/6fbeca08230b4cd4cbc53fe306da0832c3c6d766/amun/overlays/moc-prod/amun-api/imagestreamtag.yaml#L38

> https://quay.io/repository/thoth-station/python-36-centos7

Used in selinon-worker/selinon-api deployment. The code has not been refreshed to newer base images yet.

> https://quay.io/repository/thoth-station/rabbitmq

Used in selinon-worker/selinon-api deployment for messaging.

> https://quay.io/repository/thoth-station/redis

Used in selinon-worker/selinon-api as a database.

> https://quay.io/repository/thoth-station/workflow-reconcilers

I think this was used initially before we started proper workflows. I think it could be removed, but worth double-checking (I'm not aware it is used anywhere).

I don't know [actions-runners](https://quay.io/repository/thoth-station/actions-runner?tab=tags) - it looks like there is no content available anyway.

**Comment by harshad16** [comment]
Thanks, @fridex  for the details.
I will update the described ones in the quay.

**Comment by harshad16** [comment]
All the descriptions are updated.
This is a private image in quay thoth-station: https://quay.io/repository/thoth-station/community-tooling
which is also available in quay [open-source](https://quay.io/organization/open-services-group)
can we delete it from thoth-station? @goern

**Comment by goern** [comment]
@harshad16 ja, it must have been me creating the duplicates. thanks for cleaning up!

**Comment by harshad16** [comment]
Thanks for all the responses.
All the images now have links to their respective repos.
users can find all details on how to build, how to give feedbacks on these repos.

closing the issue and marking as done.
