### ISSUE TITLE
User-API prod is failing to due pgbouncer

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#1853]
**Describe the bug**
User-API prod is failing to due pgbouncer

**To Reproduce**
1. Run `thamos advise`

**Expected behavior**
Thamos advise submitted.

**Screenshots**
```
2021-07-23 17:43:09,681 [1145694] ERROR    thamos.config: Thoth service at 'https://api.moc.thoth-station.ninja/api/v1' is unavailable (HTTP 503)
2021-07-23 17:43:09,682 [1145694] ERROR    thamos: 503 Server Error: Service Unavailable for url: https://api.moc.thoth-station.ninja/api/v1
```

**Additional context**

**Comment by pacospace** [comment]
triage/accepted

**Comment by harshad16** [comment]
The postgresql db pod was failling in readiness , due to which the pgbouncer couldn't connect.
The restart of the postgresql showed that cluster had voulmemount issue, so interacting with opf folks to fix this.

**Comment by harshad16** [comment]
this is now fixed, this was caused by the cluster issue, especially due to network issues.

**Comment by fridex** [comment]
I see user-api up now. Thanks for the fix and work on this.

/close
