### ISSUE TITLE
thoth optionally learns from user package

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#1887]
**Is your feature request related to a problem? Please describe.**
As Thoth Maintainer,

I want to have more control on ingestion.

**Describe the solution you'd like**
when adviser fails, unsolved package messages are sent and solver scheduled (aka thoth is learning)

**Describe alternatives you've considered**
Have an env variable to optionally learn from user unsolved package.

**Additional context**

**Comment by pacospace** [comment]
@fridex do we want to set this env variable on adviser workflow side? (so the pod never starts if the condition is not met and messages are not sent) or we add this check on investigator side and we let messages come in so we can monitor them when coming from adviser workflow.

**Comment by fridex** [comment]
As you write this - do we send these messages always or only in case of authenticated requests? If we schedule the unsolved workflow only for authenticated requests, that might be good enough as we will grant only trustworthy users permissions to schedule unsolved workflow. Are these unsolved workflows statistics part of reports or metrics?

**Comment by pacospace** [comment]
> As you write this - do we send these messages always or only in case of authenticated requests? If we schedule the unsolved workflow only for authenticated requests, that might be good enough as we will grant only trustworthy users permissions to schedule unsolved workflow.

We do schedule them only for authenticated requests: https://github.com/thoth-station/thoth-application/blob/46ce9ef8aaf920dd95a786932e8f844838788060/adviser/base/openshift-templates/adviser.yaml#L283


> Are these unsolved workflows statistics part of reports or metrics?

Yes in the grafana dashboards we can see how many messages are sent from adviser workflows related to unsolved packages.

**Comment by fridex** [comment]
Oh, nice! 👍🏻 So that means we do not need to do anything on this front? :)

**Comment by pacospace** [comment]
> Oh, nice! 👍🏻 So that means we do not need to do anything on this front? :)

Thanks for the brainstorming :) 🚀
