### ISSUE TITLE
microservice deployable on op1st (or a tekton pipeline)

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#1893]
as devconf.us is happening on 2021-Sept-01 we need this tekton pipeline being ready to use on this milestone

**Comment by goern** [comment]
@tumido @KPostOffice could you please go ahead an plan this feature into a meteor notebbok builder release?

**Comment by codificat** [comment]
/remove-priority critical-urgent
per the last comment

**Comment by codificat** [comment]
This feature is the same that is described in https://github.com/AICoE/meteor-operator/issues/43, right?

**Comment by KPostOffice** [comment]
/close
Tracked elsewhere
here: https://github.com/thoth-station/core/issues/314
here: https://github.com/AICoE/meteor-operator/issues/43
