### ISSUE TITLE
package-releases job fails with DeadlineExceededJob

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1895]
**Describe the bug**

Start package-releases-job and check error: `DeadlineExceededJob was active longer than specified deadline`

**To Reproduce**
1. Start package-releases-job
2. Check job status
4. See the error as reported above

**Expected behavior**

package-releases-job should succeed

**Comment by harshad16** [comment]
Procedure to test on this:
- [ ] create a job and monitor the results
`oc create job --from=cronjob/package-releases package-release`

- check on the error log or experiment with the active deadline second.

**Comment by harshad16** [comment]
The issue happens when the call to DB is stalled
the DB issue was
![package-release](https://user-images.githubusercontent.com/14028058/144446016-2ee40f44-e966-4d17-9174-1d7418bd354b.png)
 fixed with storages releases.
