### ISSUE TITLE
alarms are not triggered in prod

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#1914]
**Describe the bug**
alarms are not triggered in prod

**To Reproduce**
1. Conditions for alarms are preesnt but no issues is opened.

**Expected behavior**
Alarms are sent to Thoth team.

**Screenshots**

**Additional context**

**Comment by codificat** [comment]
> Stale issues rot after 30d of inactivity.

except that in this case this was a bug with the bot.
/reopen
/remove-lifecycle rotten

**Comment by codificat** [comment]
/lifecycle active
according to today's call

**Comment by goern** [comment]
what is the status of this?
