### ISSUE TITLE
Security indicators workflow stuck on pending state in stage environment

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1929]
**Describe the bug**

Security indicator workflows are stuck on:
```
Unschedulable: 0/56 nodes are available: 56 pod has unbound immediate PersistentVolumeClaims.
```

Subsequently, the security indicator workflow exceeds the deadline and is deleted from the namespace.

**To Reproduce**
1. Go to the stage environment
2. Check workflows present in the namespace or schedule a new security indicator workflow
4. See the error

**Expected behavior**

Security indicators workflow should succeed.

**Additional context**

**Comment by goern** [comment]
/priority critical-urgent
/sig devops
/assign @harshad16 
/triage accepted

This seems to be an op1st cluster issue on `zero`. We should request migration of all our apps to `smaug` cluster ASAP
see https://github.com/operate-first/SRE/issues/359
