### ISSUE TITLE
Kebechet container not running in prod 

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1930]
**Describe the bug**

See the error reported:

```
Unschedulable: 0/8 nodes are available: 1 node(s) had taint {no-storage: true}, that the pod didn't tolerate, 3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 4 Insufficient cpu.
```

**To Reproduce**
0. Schedule kebechet via opening a new issues (e.g. `new patch release`)
1. Go to thoth-backend-prod
3. See the pending pod with the error reported

**Expected behavior**

Kebechet should succeed.

**Comment by goern** [comment]
/priority critical-urgent
/triage accepted
/assign @harshad16 

This seems to be an op1st cluster issue on `zero`. We should request migration of all our apps to `smaug` cluster ASAP
see operate-first/SRE#359
