### ISSUE TITLE
HTTPSConnectionPool(host='khemenu.thoth-station.ninja', port=443): Max retries exceeded with url: /api/v1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#1942]
**Describe the bug**
HTTPSConnectionPool(host='khemenu.thoth-station.ninja', port=443): Max retries exceeded with url: /api/v1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))

**To Reproduce**
1. Run thamos advise

**Expected behavior**
advise starts

**Screenshots**

**Additional context**

**Comment by harshad16** [comment]
khemenu certs update is having trouble

```
 - The following errors were reported by the server:

   Domain: khemenu.thoth-station.ninja
   Type:   dns
   Detail: DNS problem: query timed out looking up CAA for
   khemenu.thoth-station.ninja
```

**Comment by harshad16** [comment]
khemenu is attached to the zero cluster user-api , as the cluster itself isn't reachable that is causing the issue
we will check on the cluster auth fix and then re-update the certs for khemenu.

**Comment by harshad16** [comment]
We set the acme for automatic certs update for the khemenu
Also moved to the AWS cluster.
https://github.com/thoth-station/thoth-application/blob/master/user-api/overlays/aws-prod/khemenu-route.yaml

This issue shouldn't happen.
