### ISSUE TITLE
use ghproxy for aicoe/common prow jobs

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#1967]
**Is your feature request related to a problem? Please describe.**
apply https://github.com/AICoE/common/commit/a670b0e82a681d7a6132b89d990a46fc0573e00d also for postsubmit jobs

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

/priority important-soon
/assign @Gregory-Pereira

**Comment by harshad16** [comment]
Fixed with: https://github.com/AICoE/common/pull/27
Thanks :100:
