### ISSUE TITLE
migrate triage-party to rick

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#1969]
**Is your feature request related to a problem? Please describe.**
SSIA

**Describe the solution you'd like**
an additional overlay for rick...

**Describe alternatives you've considered**
none

**Additional context**
Depends-On: https://github.com/operate-first/support/issues/388

/priority critical-urgent
/assign @Gregory-Pereira

**Comment by codificat** [comment]
/triage accepted
we just discussed this during the meeting about triage - and I happily volunteered to look at it, so
/assign @codificat

**Comment by harshad16** [comment]
Lets not bring this to rick, 
we already have namespace and resource available in smaug.
lets keep it there

**Comment by codificat** [comment]
Thanks @harshad16 !

Triage party is already up and running in smaug: https://triage-party.thoth-station.ninja/

This was deployed though https://github.com/operate-first/argocd-apps/pull/205
