### ISSUE TITLE
connection issues to quay while running pipelines

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#1990]
**Describe the bug**
connection issues to quay while running pipelines

**To Reproduce**
1. Pipelines randomly fails

**Expected behavior**
Pipelines do not fails due to connection issues

**Screenshots**
![Screenshot from 2021-09-29 18-14-14](https://user-images.githubusercontent.com/27498679/135335474-0b2eb266-c641-4d89-973b-e2663fb334d1.png)

![Screenshot from 2021-09-29 21-25-48](https://user-images.githubusercontent.com/27498679/135335484-d3a486b0-186c-4fee-8ca7-f4761164ba96.png)

**Additional context**
It might be Quay or Smaug cluster.

**Comment by codificat** [comment]
This might have been related to the [DNS issues at quay.io](https://status.quay.io/incidents/bt8yqm82069z) earlier today?

The times and the symptoms (Internal Server Error, timeout) don't quite match though... but I'm just wondering if the quay.io issue description is not telling the whole story

**Comment by pacospace** [comment]
It seems back :)
