### ISSUE TITLE
[3pt] Document on the process of enlisting new repo for prow support

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#1992]
**Is your feature request related to a problem? Please describe.**
Users would like some documentation on how to enable prow to support the new repositories. 

**Acceptance criteria**
- [ ] How onboard prow on your repo or org?
- [ ] Run book of prow troubleshooting.
- [ ] Automating to run sprint of update prow.

**Comment by codificat** [comment]
> /triage accepted
> /lifecycle frozen
> /priority importent-longterm

Thanks! Just fixing a typo:

/priority important-longterm
/remove-priority important-soon

**Comment by codificat** [comment]
Maybe this should be part of operate first docs instead of thoth docs?

**Comment by harshad16** [comment]
Prow is migrated to operate-first 
closing this issue.
