### ISSUE TITLE
kafka not working in the Rick cluster

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#2003]
**Describe the bug**
test infra in rick, is not able to use kafka

```
%3|1633374535.768|FAIL|rdkafka#producer-1| [thrd:ssl://opf-kafka-kafka-bootstrap.opf-kafka.svc:9093/bootstrap]: ssl://opf-kafka-kafka-bootstrap.opf-kafka.svc:9093/bootstrap: Receive failed: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac (after 0ms in state APIVERSION_QUERY, 3 identical error(s) suppressed)
```

**Comment by harshad16** [comment]
I can take the issue, will be sending in the pull-request soon.

**Comment by harshad16** [comment]
The reason user-api is not able to function with Kafka is due to SSL authentication.
The overlays test has set Kafka usage for user-api in simple SSL, whereas rick Kafka requires user bases SSL.

creating an exclusive overlay for rick and adding required changes can fix this issue.

**Comment by goern** [comment]
it seems like the issue is still there:

`%3|1634479293.572|FAIL|rdkafka#producer-1| [thrd:ssl://opf-kafka-kafka-bootstrap.opf-kafka.svc:9093/bootstrap]: ssl://opf-kafka-kafka-bootstrap.opf-kafka.svc:9093/bootstrap: Connect to ipv4#172.30.202.142:9093 failed: Connection timed out (after 130119ms in state CONNECT, 1 identical error(s) suppressed)`

/reopen

**Comment by tumido** [comment]
cc @HumairAK @4n4nd

**Comment by goern** [comment]
what is the status of this?

**Comment by rbo** [comment]
Just an idea: Switch to the new EMEA cluster morty?

**Comment by goern** [comment]
> Just an idea: Switch to the new EMEA cluster morty?

I think that's on @harshad16 list?

/sig devops

**Comment by harshad16** [comment]
Will try to visit this issue, in this sprint cycle
and confirm on the clusters.

**Comment by harshad16** [comment]
Kafka is stable in rick cluster.
we would have a separate issue to move our workloads to morty soon.
thanks for the patience.
