### ISSUE TITLE
Create and deploy first Thoth UI page

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#2034]
**Is your feature request related to a problem? Please describe.**

I, as a user of Thoth, would like to have the ability to browse advisory results in a nice UI interface.

**Describe the solution you'd like**

- [ ] based on Gage's intern project, deploy a minimalistic example showing advisory results (obtains data from Ceph)
  - [ ] the page accepts adviser-id and visualizes results available
  - [ ] the work can be directly done based on [thoth-search web page](https://gkrumbach07.github.io/thoth-search/advise/adviser-210720144318-2db6412247a67a63) (advise results tab)

ACTIONS:
  - [ ] create a UI component (containerized) - let's pick a name for this
  - [ ] start with the "advise results" tab and extend it
  - [ ] deploy UI to our environments
  - [ ] configure pretty routes
  - [ ] link the UI in adviser results

Sources of Thoth search: https://github.com/Gkrumbach07/thoth-search

**Comment by Gkrumbach07** [comment]
- [ ] transfer ownership (@Gkrumbach07 does not have access to create a repo inside Thoth Station)
- [ ]  configure routing under /search sub-route.
- [ ]  update CI workflow to work in the new org.
