### ISSUE TITLE
Failed to pull image "image-registry.openshift-image-registry.svc:5000/thoth-middletier-stage/graph-sync-job:latest":

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#2054]
**Describe the bug**
Failed to pull image "image-registry.openshift-image-registry.svc:5000/thoth-middletier-stage/graph-sync-job:latest": 

**To Reproduce**
1. Schedule solver in ocp4-stage

**Expected behavior**
solver runs successfully

**Screenshots**
```
Failed to pull image "image-registry.openshift-image-registry.svc:5000/thoth-middletier-stage/graph-sync-job:latest": rpc error: code = Unknown desc = Error reading manifest latest in image-registry.openshift-image-registry.svc:5000/thoth-middletier-stage/graph-sync-job: unauthorized: authentication required
```

**Additional context**

**Comment by harshad16** [comment]
![solver-graph](https://user-images.githubusercontent.com/14028058/138019936-0f8e70ec-06dd-4901-ad42-c80a6d0d38dd.png)
![graph-sync](https://user-images.githubusercontent.com/14028058/138019943-39362d6b-5709-4344-821d-9dc6da359790.png)

This seems to be fixed
closing this issue.
Thanks :100:
