### ISSUE TITLE
Failed to pull image "si-bandit" in stage

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#2057]
**Describe the bug**
Failed to pull image "si-bandit" in stage

**To Reproduce**
1. Schedule securit workflow in ocp4-stage

**Expected behavior**
security workflow runs successfully

**Screenshots**
```
Failed to pull image "si-bandit": rpc error: code = Unknown desc = Error reading manifest latest in docker.io/library/si-bandit: errors: denied: requested access to the resource is denied unauthorized: authentication required
```

**Additional context**

**Comment by harshad16** [comment]
This is completed with the following changes:  https://github.com/thoth-station/thoth-application/blob/fa821a6c568a699efd97468d92384f3e1b9021c5/security-indicators/overlays/moc-prod/kustomization.yaml#L30
