### ISSUE TITLE
Prow is not functioning on some selected repos

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#2058]
**Describe the bug**
Prow does not function on some selected repos

The prow webhook is enabled on the org level of **operate-first**,
however, it is not working on the repo **operate-first.github.io**

The logs in the prow **hooks**, has logs for the repo but no error logs.

Examples:
https://github.com/operate-first/operate-first.github.io/pull/314

**Comment by harshad16** [comment]
/lifecycle frozen

havent found a solution yet. 
keeping this open for future solution.

**Comment by goern** [comment]
still valid?

**Comment by harshad16** [comment]
The repo was 5Gb in size when prow was failing, the clone on the prow job caused it.
The repo is now refactored and sized 6mb.

This is no longer valid, the prow jobs are functioning now.
