### ISSUE TITLE
sprint production release for v2021.11.08

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#2091]
Hello, Thoth-station!

This Issue would be used for the current sprint cycle production release.
By the end of the sprint cycle, we will consolidate the information of thoth-station components features upgrade and fixes in this issue.

**Comment by fridex** [comment]
**The resolution blocks using container images with a CVE if recommendation type is set to `security`**

Newly, the resolution process fails if [the recommendation type is set to security](https://thoth-station.ninja/recommendation-types/) and users use a base container image with one or multiple CVEs in RPMs. This prevents running applications in environments where security is a priority. If an RPM shipped in the base image has a CVE, the resolution process fails - similarly as the recommendation engine does it already for Python packages.

* https://github.com/thoth-station/prescriptions-refresh-job/issues/38
* https://github.com/thoth-station/prescriptions/pull/18536

**Comment by fridex** [comment]
**Providing suggestions to users based on statistics aggregated from requests done to the recommender**

As Thoth offers a community resolver available to a broad user-base, from now on it computes what software is used within the community and suggests users use:

* Popular Python packages and Python package versions (both development and default ones)
* Popular containerized environments and their versions used as a base for running the application
* Python Python versions used within the Thoth community

This allows users to use software that is used more broadly which might indicate its stability and reliability - the assumption is that software which is used more broadly and has a broad user base might be more stable and tested in different scenarios. As of now, Thoth provides only suggestions and the resolution process is not adjusted based on the data available. Data driven decisions will be available once we aggregate more data from requests done to the recommendation engine.

- https://github.com/thoth-station/prescriptions-refresh-job/issues/41
- https://github.com/thoth-station/prescriptions-refresh-job/pull/43
- https://github.com/thoth-station/thoth-station.github.io/pull/234
- https://github.com/thoth-station/prescriptions/pull/18540/

**Comment by fridex** [comment]
**Update of components required due ti schema change**

- [ ] package-update-job
- [ ] graph-refresh-job
- [ ] pulp-pypi-sync-job
- [ ] prescriptions-refresh-job
- [ ] package-releases-job
- [ ] revsolver
- [ ] graph-backup-job
- [ ] init-job
- [ ] metrics-exporter
- [ ] investigator
- [ ] adviser
- [ ] graph-sync-job
- [ ] user-api
- [ ] slo-reporter
- [ ] cve-update-job
- [ ] sync-job
- [ ] management-api

**Comment by harshad16** [comment]
we have completed the release of 2021.11.08 :tada: :confetti_ball: :partying_face: 

### Features

**Vulnerability reports for container images when containerized environments are used**

Starting this release, users get information about security-related aspects of containerized environments they use. An example can be security-related information about predictable stacks container images or s2i containers. The security information is automatically gathered using prescriptions-refresh-job from Quay security scanners (thanks to @goern for showing related Quay endpoints) and made available as prescriptions to the recommendation engine. Each time a user asks for recommendations specific to the containerized environment she/he uses, the recommendation engine notifies users about known security vulnerabilities present in the containerized environments. 

- https://github.com/thoth-station/prescriptions-refresh-job/pull/29
- https://github.com/thoth-station/core/issues/344
- https://github.com/thoth-station/prescriptions/pull/18527
- https://github.com/thoth-station/thoth-application/pull/2072
- https://github.com/thoth-station/prescriptions/pull/18535
- https://github.com/thoth-station/prescriptions-refresh-job/pull/37
- https://github.com/thoth-station/thoth-application/pull/2093

**Adviser has a more optimal search for CVE-free Python packages in users stacks**

A light adjustment in the recommendation engine makes it possible to search for packages without CVE vulnerabilities faster. The optimization lies in filtering packages with CVE much sooner in the resolution process. This applies only for resolutions that have the recommendation type set to `security`.

- https://github.com/thoth-station/adviser/pull/2148

**Providing information about CVE data freshness to users**

Starting this release, users can find timestamps related to security scanners in adviser reports. Timestamps show last updates for vulnerabilities as present in PyPA/advisory-db (for Python packages) or Quay security scanners (for containerized environments produced by Thoth team - s2i, predictable stacks, ...). The timestamp notifies users about data freshness - it states when the last sync of vulnerability databases was done (Python level as well as container image level).

- https://github.com/thoth-station/adviser/issues/2142
- https://github.com/thoth-station/adviser/pull/2150
- https://github.com/thoth-station/storages/pull/2460
- https://github.com/thoth-station/metrics-exporter/pull/784
- https://github.com/thoth-station/cve-update-job/pull/436
- https://github.com/thoth-station/metrics-exporter/pull/787

**CVE reports now link to more information about the vulnerability** 

Previously, thoth-adviser reported a generic link to a justification stating that [the given package has a security vulnerability](https://thoth-station.ninja/j/cve). Newly, the link has changed and now points users to report with more information about the given security vulnerability. The link is obtained from the corresponding CVE record in PyPA/advisory-db, the priority is given to reports linking to Red Hat websites (such as RH Bugzilla).

- https://github.com/thoth-station/cve-update-job/pull/437
- https://github.com/thoth-station/adviser/issues/2149
- https://github.com/thoth-station/storages/pull/2461
- https://github.com/thoth-station/adviser/pull/2151

**The resolution blocks using container images with a CVE if recommendation type is set to `security`**

Newly, the resolution process fails if [the recommendation type is set to security](https://thoth-station.ninja/recommendation-types/) and users use a base container image with one or multiple CVEs in RPMs. This prevents running applications in environments where security is a priority. If an RPM shipped in the base image has a CVE, the resolution process fails - similarly as the recommendation engine does it already for Python packages.

* https://github.com/thoth-station/prescriptions-refresh-job/issues/38
* https://github.com/thoth-station/prescriptions/pull/18536
* https://github.com/thoth-station/prescriptions-refresh-job/pull/40

**Providing suggestions to users based on statistics aggregated from requests done to the recommender**

As Thoth offers a community resolver available to a broad user-base, from now on it computes what software is used within the community and suggests users use:

* Popular Python packages and Python package versions (both development and default ones)
* Popular containerized environments and their versions used as a base for running the application
* Python Python versions used within the Thoth community

This allows users to use software that is used more broadly which might indicate its stability and reliability - the assumption is that software which is used more broadly and has a broad user base might be more stable and tested in different scenarios. As of now, Thoth provides only suggestions and the resolution process is not adjusted based on the data available. Data-driven decisions in the actual resolution process will be available once we aggregate more data from requests done to the recommendation engine.

- https://github.com/thoth-station/prescriptions-refresh-job/issues/41
- https://github.com/thoth-station/prescriptions-refresh-job/pull/43
- https://github.com/thoth-station/thoth-station.github.io/pull/234
- https://github.com/thoth-station/prescriptions/pull/18540/

### Component Updates

- [x] adviser: v0.47.0
  - https://github.com/thoth-station/adviser/pull/2150
  - https://github.com/thoth-station/adviser/pull/2151
  - https://github.com/thoth-station/adviser/pull/2153
  - https://github.com/thoth-station/adviser/pull/2152
  - https://github.com/thoth-station/adviser/pull/2148

- [x] kebechet: v0.16.0
  - https://github.com/thoth-station/kebechet/pull/850
  - https://github.com/thoth-station/kebechet/pull/842
  - https://github.com/thoth-station/kebechet/pull/878
  - https://github.com/thoth-station/kebechet/pull/880
  - https://github.com/thoth-station/kebechet/pull/883

- [x] prescriptions-refresh-job: v0.3.0
  - https://github.com/thoth-station/prescriptions-refresh-job/pull/40
  - https://github.com/thoth-station/prescriptions-refresh-job/pull/37
  - https://github.com/thoth-station/prescriptions-refresh-job/pull/29
  
Thanks for the amazing work everyone. :100:
