### ISSUE TITLE
Pre-commit fails due to the URL issues 

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#2111]
**Describe the bug**
Use of the ssh based URL in the pre-commit is failing on the CI checks. Which earlier use to function properly.

```
[INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: remote error: 
      The unauthenticated git protocol on port 9418 is no longer supported.
    Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

**Expected behavior**
The CI checks execute without any hindrance.

**Comment by harshad16** [comment]
GitHub has recently upgraded its clone methods for more security. 
It would no longer support the SHA-1 method.

November 2, 2021, was the deadline to switch, hence we are facing the issue.
Details: https://github.blog/2021-09-01-improving-git-protocol-security-github/#dropping-insecure-signature-algorithms

**Comment by harshad16** [comment]
Solutions:
Move away from using **ssh** type URL in the `.pre-commit-config.yaml`

**Comment by harshad16** [comment]
Please all re-configure the repo maintained by you with the above-suggested changes.

**Comment by harshad16** [comment]
Keeping this open and frozen for references.
/lifecycle frozen

**Comment by codificat** [comment]
This is an ongoing effort, but less critical, so
/remove-priority critical-urgent
/priority important-longterm

**Comment by goern** [comment]
is this still ongoing?

**Comment by harshad16** [comment]
This fixed on almost all repos.
closing this. 
thanks everyone.
