### ISSUE TITLE
promote solver-project-url-job to STAGE and PROD

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#2116]
**Is your feature request related to a problem? Please describe.**
https://github.com/thoth-station/solver-project-url-job is deployed to TEST by now, it should also run in STAGE and PROD

**Describe the solution you'd like**
extend thoth-application to have all the required overlays, reconfigure ArgoCD to deploy them

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

/priority critical-urgent
/assign @bjoernh2000

**Comment by fridex** [comment]
I think we can completely remove solver-project-url-job from the deployment and have the repository archived. The logic was extracted and is now part of `gh-link` handler in prescriptions-refresh-job where it serves its purpose well (kudos to @bjoernh2000 👍🏻 ):

https://github.com/thoth-station/prescriptions-refresh-job/blob/f8c89f34815496e867d3138d45813b6185860d62/thoth/prescriptions_refresh/handlers/gh_link.py#L1

It is more generic now - if somebody adds a new prescription for a package we hadn't in our database yet, the machinery behind prescriptions-refresh-job will obtain the GitHub link and create a prescription (also, other handlers in prescriptions-refresh-job will take GitHub link information as needed, such as GitHub release notes information).

**Comment by goern** [comment]
thanks for the update @fridex 

/close
