### ISSUE TITLE
Thoth grafana dashboards do not show any data

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#2140]
**Describe the bug**
Thoth grafana dashboards do not show any data

**To Reproduce**
1. Go to https://grafana.operate-first.cloud/d/dd5ddeda417f2083b1b0526b222609dfcf1145be/thoth-knowledge-graph-content-metrics?orgId=1&refresh=30s

**Expected behavior**
Data are visualized in Grafana dashboards

**Screenshots**

**Additional context**

**Comment by harshad16** [comment]
Thanks for the issue
@Gregory-Pereira  is working on this
https://github.com/thoth-station/thoth-application/issues/2029#issuecomment-961310030
we need to update the version of the grafana dashboards in the operate-first/apps.

@Gregory-Pereira  is taking care of that part as well

**Comment by pacospace** [comment]
> Thanks for the issue @Gregory-Pereira is working on this [#2029 (comment)](https://github.com/thoth-station/thoth-application/issues/2029#issuecomment-961310030) we need to update the version of the grafana dashboards in the operate-first/apps.
> 
> @Gregory-Pereira is taking care of that part as well

Thanks @harshad16 for the update!!
