### ISSUE TITLE
SLI/SLO grafana dashboard for smaug prod is missing

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#2161]
**Describe the bug**
SLI/SLO grafana dashboard for smaug prod is missing

**To Reproduce**
1. Go to https://grafana.operate-first.cloud/ under thoth station folder

**Expected behavior**
SLI/SLO for prod smaug is present.

**Screenshots**

**Additional context**

**Comment by Gregory-Pereira** [comment]
Argocd displays a syncing error: 
```Get "https://api.smaug.na.operate-first.cloud:6443/version?timeout=32s": dial tcp 128.52.60.31:6443: connect: no route to host```. 

However, when I navigate to that endpoint, data shows up: 
```
{
    major: "1",
    minor: "21",
    gitVersion: "v1.21.1+38b3ecc",
    gitCommit: "38b3eccb7e23fd950b6c7b5ec1cc3075b630aac3",
    gitTreeState: "clean",
    buildDate: "2021-07-29T23:59:54Z",
    goVersion: "go1.16.6",
   compiler: "gc",
   platform: "linux/amd64"
}```. But the route shows up as `not secure` so I am guessing that its just an HTTP route instead of HTTPS.

**Comment by Gregory-Pereira** [comment]
Should we try creating a secure route for it in the `cluster-version-operator` namespace? I lack the permissions to do so.

**Comment by harshad16** [comment]
This seems to be up and available:
https://grafana.operate-first.cloud/d/ee96mo7s4buzb6lxads4aun3kpm1h9th6zxdtw7i/thoth-sli-slo?orgId=1&refresh=30s

Thanks for the efforts.
