### ISSUE TITLE
Verify migration Thoth Katacoda tutorials to new platform Instruqt

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#2162]
**Is your feature request related to a problem? Please describe.**
Related-To: https://github.com/openshift-instruqt/instruqt/issues/10

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by goern** [comment]
any updates on this? do we consider it done?

**Comment by mayaCostantini** [comment]
The tutorials are ready except for links to the OpenShift console which have to be fixed, I will check on that soon 👍🏻

**Comment by goern** [comment]
any update on this?

**Comment by blues-man** [comment]
Please verify this issue:
https://github.com/openshift-instruqt/instruqt/issues/10#issuecomment-1153814731

**Comment by mayaCostantini** [comment]
Closed by https://github.com/openshift-instruqt/instruqt/issues/10#
