### ISSUE TITLE
Logs of succesfull `mi` worklflows are not being kept

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/thoth-application#2170]
**Describe the bug**
After succesful execution of the `mi` workflow, its output is not kept. This happens regardless of the cluster and namespace.

**To Reproduce**

1. Create job (`thoth-test-core` on ocp4)
```
oc create job --from=cronjob/mi-scheduler-gh mi-gh-fri
```
2. Wait for job to schedule workflows (~20seconds) 
3. Look at the current workflow that's running, and see that if it ends, workflow log is deleted.

**Expected behavior**
Keep logs of at least last 4 succesfull workfows

**Additional context**
Log of the failed workflows (I think it's the last 4 failed wrkfls) are however, kept.

/cc @harshad16 /kind bug

**Comment by harshad16** [comment]
/triage accepted
/priority critical-urgent
/lifecycle active
/sig devops


The log archiving is turned on the test cluster.
please check the pod logs in ceph:
`aws s3 --endpoint https://s3.upshift.redhat.com/ ls s3://thoth/data/ocp4-test/argo/artifacts/`

**Comment by xtuchyna** [comment]
Tested on psi, seems like everything works fine now. thx :ship:
