### ISSUE TITLE
Thoth Knowledge graph content metrics grafana dashboard for aws prod is missing

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#2171]
**Describe the bug**
Thoth Knowledge graph content metrics grafana dashboard for aws prod is missing

**To Reproduce**
1. Go to https://grafana.operate-first.cloud/ under thoth station prod folder

**Expected behavior**
Thoth Knowledge graph content metrics for prod aws is present.

**Screenshots**

**Additional context**

**Comment by harshad16** [comment]
This is up and available now:
https://grafana.operate-first.cloud/d/ncypu0f4l9n9dh5cft7101v762b3tr2blcmalvi4/thoth-knowledge-graph-content-metrics?orgId=1&refresh=30s

thanks for the patience
