### ISSUE TITLE
Bring prow storage back to the smaug cluster

### ISSUE THREAD

**Issue by codificat** [thoth-station/thoth-application#2196]
#2184 was performed as a workaround for the issues with storage in the smaug cluster (https://github.com/operate-first/support/issues/490)

As these storage issues are resolved and storage is again available in smaug, it would be desirable to revert the change and move prow storage back to smaug, where the app is running.

I believe this should also clear the current issues with the deck component, that is currently unable to show e.g. details about tests runs.

**Comment by harshad16** [comment]
seems to be back again 
closing this.
