### ISSUE TITLE
[1pt] Handoff Prow instance manifest to operate-first

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#2198]
**Is your feature request related to a problem? Please describe.**
All Continuous integration/delivery and deployment apps are under operate-first. 
It was asked for us to hand-off prow instance to operate first, so all apps can be under one hood.

**Describe the solution you'd like**
migrate all prow manifest to operate-apps

**Acceptance criteria**
- [x] Move from thoth-application to opf/continuous-delivery or apps.
- [x] Adjust the argocd.
- [x] verfiy the state

**Comment by harshad16** [comment]
@goern I had forgotten about this.
Can you confirm is what we should be aiming to or keep it under thoth-station

**Comment by goern** [comment]
\approve :)

**Comment by codificat** [comment]
> \approve :)

Translating:
/triage accepted
/priority backlog

**Comment by harshad16** [comment]
The prow component is officially moved
closing the issue
