### ISSUE TITLE
image analysis handler for prescription-refresh-job requires access to database and ceph from the same environment

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#2232]
**Describe the bug**
Few background comments:

- Currently, the handler in prescription refresh job from image analysis accesses database and Ceph from User-API endpoint provided in CM.
- Prescription-refresh-job is scheduled to run in smaug-prod, but aicoe-ci is sending image analysis to aws-prod through management-API so all data are synced into DB and stored on Ceph in aws-prod.
- The sync from prod to stage currently considers only DB but not Ceph documents as of now, therefore if prescription-refresh-job handler runs will not find the documents required to create prescriptions
- where do we test prescription-refresh-job? test is not synced from smaug-prod or smaug-aws to my knowledge.

**Possible solutions**
1. send image analysis from aicoe-ci to smaug-prod instead of aws-prod.
2. create a sync logic from aws-prod to smaug-prod not only for database but also for ceph documents.
3. sync requirements files into DB, so that data can be retrieved without need of Ceph.
4. move prescripion-refresh-job to aws-prod.

**Additional context**
See: https://github.com/thoth-station/thoth-application/issues/2229

-

**Comment by pacospace** [comment]
1. This could be easy solution, but users in prod would lose the data that can be get with endpoints (e.g. `api/v1/container-images`)
2. this requires a bit of work and maintaining some new script which can take time anyway. It depends if there are other benefit from this.
3. this will increase size of database, probably not required because it is not providing any direct info to users directly.
4. it seems a good solution, but requires resources on aws (which is not free).

**Comment by harshad16** [comment]
Suggestions: 

* move prescriptions-refresh-job and image-analysis in the stage. 
to get all the data in one place.

**Comment by fridex** [comment]
> Suggestions:
> 
> * move prescriptions-refresh-job and image-analysis in the stage.
>   to get all the data in one place.

This will simplify how the data are managed - we can generate data in stage and move them to prod on each release.
