### ISSUE TITLE
slo-reporter in smaug-prod cannot store on Ceph

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#2259]
**Describe the bug**
slo-reporter ceph credentials in smaug-prod are invalid

**To Reproduce**
1. Check logs after slo-reporter run.

**Expected behavior**
slo-reporter smaug-prod is able to save data into Ceph smaug-prod

**Screenshots**
```
ERROR:thoth.slo_reporter:Could not store metrics on Thoth bucket on Ceph...An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS access key Id you provided does not exist in our records.
```

**Additional context**

**Comment by pacospace** [comment]
Depends-On: https://github.com/thoth-station/thoth-application/pull/2287

**Comment by codificat** [comment]
Still waiting for a fix: we need the ceph storage in smaug to come back before we can validate the status of this issue

**Comment by harshad16** [comment]
With the change of the ceph storage
https://github.com/thoth-station/thoth-application/blob/master/core/overlays/moc-prod/common/configmaps.yaml#L29

the slo-reporter is now fixed and running successfully:
https://console-openshift-console.apps.ocp4.prod.psi.redhat.com/k8s/ns/thoth-frontend-stage/pods/slo-reporter-l4txz

Thanks, everyone for working on this.
Closing the issue.
