### ISSUE TITLE
Have the data generated on the psi cluster moved on smaug under a public bucket

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/thoth-application#2262]
**Is your feature request related to a problem? Please describe.**
Have the data generated on the psi cluster stored on smaug under [Operate First Ceph public bucket](https://github.com/operate-first/apps/blob/master/docs/odh/trino/access_public_bucket.md
)

**Comment by harshad16** [comment]
Removing active
as need some guidance from @xtuchyna 
freezing this issue till then.

/lifecycle frozen

**Comment by goern** [comment]
what is the status of this issue?
