### ISSUE TITLE
Deploy and enable pulp-pypi-sync-job in stage environment

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#2269]
**Is your feature request related to a problem? Please describe.**

As we perform ingestion in the stage environment, it would be good to have pulp-pypi-sync-job enabled there so that the pulp instance is monitored for new indexes created and Thoth can analyze packages.

**Describe the solution you'd like**

Deploy pulp-pypi-sync-job to stage environment.

**Comment by harshad16** [comment]
/triage accepted

we have resources in the `aicoe-prod-bots` namespace
we can have this application deployed at that namespace.

ack?

**Comment by fridex** [comment]
The component talks directly to the database. Would it make sense to have it in the frontend namespace where other cronjobs run?

**Comment by fridex** [comment]
If the frontend namespace is too occupied, graph namespace could be also an option.

**Comment by harshad16** [comment]
yes totally we can have it in frontend namespace.
i had missed that we would need to provide the database access. 
aicoe-prod-bots is not the right namespace. 

Frontend namespace has resource to accommodate this.

**Comment by goern** [comment]
I assume its something we do this sprint? if not, please correct...

/priority critical-urgent
/milestone 2022.01.31
