### ISSUE TITLE
prescriptions-refresh-job fails to run

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#2281]
**Describe the bug**

The following error was reported by @harshad16 in deployments:

```
time="2022-01-24T19:34:09.495Z" level=error msg="cannot validate Workflow: templates.gh.tasks.gh-release-notes template reference prescriptions-refresh-gh.gh-release-notes not found" conditionType=SpecError namespace=thoth-backend-stage workflow=prescriptions-refresh
time="2022-01-24T19:34:09.495Z" level=error msg="invalid cron workflow" cronWorkflow=thoth-backend-stage/prescriptions-refresh error="cannot validate Workflow: templates.gh.tasks.gh-release-notes template reference prescriptions-refresh-gh.gh-release-notes not found"
```

**To Reproduce**
1. Run prescriptions-refresh-job
2. See the error

**Expected behavior**

prescriptions-refresh-job should be operational

**Additional context**

There might be issues with RBAC (not verified) as workflow controller is not able see referenced templates. As a fix, we can prioritize https://github.com/thoth-station/thoth-application/issues/2188 and have multiple prescription-refresh cronjobs (rather than one huge running all the handlers). This will help with maintenance and should fix the $SUBJ issue as cronworkflows that have solely one template work.

**Comment by harshad16** [comment]
Related-to: https://github.com/thoth-station/thoth-application/issues/2208

**Comment by goern** [comment]
any updates on this? do we consider it done?

**Comment by harshad16** [comment]
with the merge of #2312, we would be able to consider it done.

**Comment by fridex** [comment]
I will reopen this one to track progress. It looks like prescriptions-refresh-job is not updating the repository, let's track fix.

/reopen

**Comment by goern** [comment]
shall we target this for the next sprint/milestone?

/cc @codificat

**Comment by harshad16** [comment]
Prescription-refresh-job is set to run weekly 
it would execute tomorrow, till I remember, out of 5 workflows, 3 of them are running 
however all of the reach oom after some point of tine

we need to increase memory size
![prescriptions-refresh](https://user-images.githubusercontent.com/14028058/155989982-4407c726-040a-4fe3-8db6-c3018c914c99.png)

**Comment by fridex** [comment]
/lifecycle active
/assign @fridex 
/priority critical-urgent

Was checking the root cause, there were few patches applied to make prescriptions-refresh jobs operational. We should be pretty close to an operational solution from the deployment point of view. I will keep this open for now and update once we are done.

**Comment by fridex** [comment]
All the jobs are up and running. Some of them fail due to creds issues. Also worth keeping an eye for possible OOM. These issues can be handled separately. Thanks all involved 👍🏻 

/close
