### ISSUE TITLE
Metrics from aws-prod are not scraped

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#2288]
**Describe the bug**
Metrics from aws-prod are not scraped. This impact other components as well that require those metrics. (e.g. slo-reporter)

**To Reproduce**
1. check prod grafana dashboard with aws-balrog datasource: https://grafana.operate-first.cloud/d/ncypu0f4l9n9dh5cft7101v762b3tr2blcmalvi4/thoth-knowledge-graph-content-metrics?orgId=1&refresh=30s

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by harshad16** [comment]
![aws-pord](https://user-images.githubusercontent.com/14028058/152113035-7e84c08e-b8cc-4df1-a0a5-d79ebf4422d1.png)
can please help me recognize which metrics are we missing it, seems most of these are showing correct data.

**Comment by pacospace** [comment]
> ![aws-pord](https://user-images.githubusercontent.com/14028058/152113035-7e84c08e-b8cc-4df1-a0a5-d79ebf4422d1.png) can please help me recognize which metrics are we missing it, seems most of these are showing correct data.

When I opened this issue, all dashboard was with nan. I didn't have access to thanos balrog yet to verify that. Not sure what changed since then :D we can close this issue now then.
