### ISSUE TITLE
Metrics from investigator metrics aws prod are not available on Thanos aws prod

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#2357]
**Describe the bug**
Metrics from investigator metrics are not available on Thanos aws prod 

**To Reproduce**
1. Check `message_count_by_version_total` on https://thanos-querier-openshift-monitoring.apps.balrog.aws.operate-first.cloud/graph?g0.expr=message_count_by_version_total&g0.tab=1&g0.stacked=0&g0.range_input=1h&g0.max_source_resolution=0s&g0.deduplicate=1&g0.partial_response=0&g0.store_matches=%5B%5D

**Expected behavior**
Metrics are available on aws prod.

**Screenshots**

**Additional context**

**Comment by harshad16** [comment]
These metrics are showing up for me with visit: https://thanos-querier-openshift-monitoring.apps.balrog.aws.operate-first.cloud/graph?g0.expr=message_count_by_version_total&g0.tab=1&g0.stacked=0&g0.range_input=1h&g0.max_source_resolution=0s&g0.deduplicate=1&g0.partial_response=0&g0.store_matches=%5B%5D

![message-count](https://user-images.githubusercontent.com/14028058/154128877-5bb0ec87-86b7-4fef-93bd-9f35a37c0d3d.png)

Is something missing ?
can you provide some more details.

**Comment by pacospace** [comment]
> These metrics are showing up for me with visit: https://thanos-querier-openshift-monitoring.apps.balrog.aws.operate-first.cloud/graph?g0.expr=message_count_by_version_total&g0.tab=1&g0.stacked=0&g0.range_input=1h&g0.max_source_resolution=0s&g0.deduplicate=1&g0.partial_response=0&g0.store_matches=%5B%5D
> 
> ![message-count](https://user-images.githubusercontent.com/14028058/154128877-5bb0ec87-86b7-4fef-93bd-9f35a37c0d3d.png)
> 
> Is something missing ? can you provide some more details.

very weird I cannot see them, I open the same link and I don't have any metric:

![Screenshot from 2022-02-16 09-42-15](https://user-images.githubusercontent.com/27498679/154227546-cac8c8f2-96d3-4c2a-9925-a5daf214e5b1.png)

**Comment by harshad16** [comment]
Is it same for everyone ? @goern  @fridex can you folks also verify.

**Comment by harshad16** [comment]
This is not working for half of the team.
we need to investigate on this.

**Comment by goern** [comment]
is this an op1st problem? can we get some help from that team too?

**Comment by codificat** [comment]
Some members of the team still can not access the metrics.
/assign @VannTen 
as one of the affected to self-check - thanks. This is most likely permission configuration on operate first

**Comment by VannTen** [comment]
Hum, i think I don't have access at all to the project in question, I can't see it (or any other one, for that matter) in the openshift console (https://console-openshift-console.apps.balrog.aws.operate-first.cloud/topology/all-namespaces?view=graph)

**Comment by VannTen** [comment]
With my perms set up, I can access the metrics without problems: 
![image](https://user-images.githubusercontent.com/13346812/185090229-8a54c8d1-9967-4ad7-982f-0151823cf62a.png)

Unless there is anyone else affected we can probably close this.

**Comment by harshad16** [comment]
thank you for the confirmation.
closing the issue.
