### ISSUE TITLE
Generalized Thoth dashboards are not available on Operate First Grafana

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#2431]
**Describe the bug**
New dashboards are not available on Operate First Grafana

**To Reproduce**

**Expected behavior**
Once this PR was merged: https://github.com/operate-first/apps/pull/1639, dashboards should be created by the grafana operator

**Screenshots**

**Additional context**

**Comment by pacospace** [comment]
cc @harshad16, dashboards are available now, but under `opf-monitoring` folder and not `thoth-station` folder. How is assigned the name of the folder in grafana? @4n4nd 

![Screenshot from 2022-03-15 12-15-02](https://user-images.githubusercontent.com/27498679/158366499-172be585-2256-4b5a-85af-81fe9cf29744.png)

**Comment by harshad16** [comment]
I think we have to put the folder description in the operate-first/apps using the `customFolderName` variable.
https://github.com/grafana-operator/grafana-operator/blob/7754cd15386ff6da1e3e7b820f8baf53e6dd9356/documentation/dashboards.md#dashboard-properties
https://github.com/grafana-operator/grafana-operator/blob/eec0e7c38193526faa8011816394d748a6727cca/deploy/examples/dashboards/DashboardWithCustomFolder.yaml#L8

**Comment by pacospace** [comment]
> I think we have to put the folder description in the operate-first/apps using the `customFolderName` variable. https://github.com/grafana-operator/grafana-operator/blob/7754cd15386ff6da1e3e7b820f8baf53e6dd9356/documentation/dashboards.md#dashboard-properties https://github.com/grafana-operator/grafana-operator/blob/eec0e7c38193526faa8011816394d748a6727cca/deploy/examples/dashboards/DashboardWithCustomFolder.yaml#L8

Thanks @harshad16, I will open PR :)
