### ISSUE TITLE
Automatically bump the base image versions of components on stage

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/thoth-application#2443]
**Is your feature request related to a problem? Please describe.**
As the base image versions present on repositories are now automatically updated by `aicoe-ci` in `.aicoe-ci.yaml` files and are modified on test, it would be useful to have it also automatically updated on stage.
(For more details, see: https://github.com/thoth-station/thoth-application/issues/2393#issuecomment-1067721824).

**Describe the solution you'd like**
Modify the pipeline to make an automatic update of the base image versions for a component on stage deployment after it is updated in the corresponding repository.

**Describe alternatives you've considered**
Keep the change manual.

**Comment by fridex** [comment]
This looks like a duplicate of https://github.com/thoth-station/kebechet/issues/991 Is this related to the automatic container image bump in thoth-application we discussed earlier in https://github.com/thoth-station/kebechet/issues/991#issuecomment-1029996420 and on the tech talk?

**Comment by mayaCostantini** [comment]
@fridex You're right, this was indeed discussed in the comment you mentioned 👍🏻 We could close this issue then
