### ISSUE TITLE
Configure integration-tests for prod environment

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#2451]
**Is your feature request related to a problem? Please describe.**

As an engineer, I would like to get an overview of the current state of the prod environment so that I can be sure basic tests pass.

**Describe the solution you'd like**

Instead of running integration-tests for the smaug cluster, we could start running integration-tests for the prod deployment. Some of the tests could be turned off to make sure we do not put too much unecessary load on prod.

Related: https://github.com/thoth-station/integration-tests/issues/302

**Comment by harshad16** [comment]
This is completed and is providing results as intended.
Thanks, everyone for the efforts on this issue.
