### ISSUE TITLE
Migrate the Prometheus metrics and alerts for stage to our own clusters

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#2455]
**Is your feature request related to a problem? Please describe.**

Migrate the prometheus metrics and alerts from datahub to our own stage cluster
https://gitlab.cee.redhat.com/data-hub/dh-monitoring/-/blob/master/prometheus/prometheus.yaml#L2037

**Describe the solution you'd like**
- [x] Deploy prometheus 
- [x] scrape metrics
- [x] Deploy grafana and upload the dashboards
- [x] setup alertmanager with thoth rules

**Additional context**
- Check if PSI has openshift monitoring enabled for user.

**Comment by harshad16** [comment]
All the components are deployed on namespace: `aicoe-infra-prod`

Prometheus: http://prometheus-aicoe-infra-prod.apps.ocp4.prod.psi.redhat.com/
Pushgateway: http://pushgateway-aicoe-infra-prod.apps.ocp4.prod.psi.redhat.com/
Grafana: https://grafana-aicoe-infra-prod.apps.ocp4.prod.psi.redhat.com/

All the metrics from the thoth-station components are already being scrapped for the deployment.

**Comment by accorvin** [comment]
@harshad16 does that mean that all of the Thoth dashboards at grafana.datahub.redhat.com can be deleted?

**Comment by accorvin** [comment]
Thank you very much @harshad16!

**Comment by harshad16** [comment]
Thank you @accorvin for the services for all the past years :100:
