### ISSUE TITLE
sprint production release for v2022.04.18

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#2472]
Hello, Thoth-station!

This Issue would be used for the current sprint cycle production release.
By the end of the sprint cycle, we will consolidate the information of the thoth-station components features upgrade and fixes in this issue.

**Sprint Goals**
* strengthen SIG/WG/refinement/planning workflows - let's get a better understanding and practice wrt this
* Service Descriptions for "provide curated and trusted content sets*
* document more of the user experience aspects fo Thoth as a Service

/kind documentation
/area release-eng
/triage accepted
/priority important-soon

**Comment by fridex** [comment]
**User API drops `count` and `limit` parameters on advise endpoint**

Starting this release, user-api no longer provides count and limit as parameters on the advise endpoints. These parameters were not used. Note this is a braking change on API endpoints.

* https://github.com/thoth-station/user-api/issues/1726
* https://github.com/thoth-station/user-api/pull/1727
* https://github.com/thoth-station/thamos/pull/1099

**Comment by fridex** [comment]
**Fix scoring of the user stack supplied**

Users could be confronted with issues when adding a new package to requirements and submitting the lock file to the backend. The backend did not invalidate the lockfile sent as it no longer corresponded to the adjusted requiements.

* https://github.com/thoth-station/adviser/issues/2322
* https://github.com/thoth-station/python/pull/470

**Comment by Gkrumbach07** [comment]
**Thoth Search UI moves to Typescript and adds a advise document compare screen**
Users can now compare multiple advise documents to see the differences and similarities between them. They can access old advise documents through a local history feature added. The home page now has a button for viewing past runs.

- https://github.com/thoth-station/search/issues/60
- https://github.com/thoth-station/search/issues/64

**Comment by harshad16** [comment]
we have completed the release for v2022.04.18 :tada: :confetti_ball: :partying_face: 

### Features

**User API drops `count` and `limit` parameters on advise endpoint**

Starting this release, user-api no longer provides count and limit as parameters on the advise endpoints. These parameters were not used. Note this is a braking change on API endpoints.

* https://github.com/thoth-station/user-api/issues/1726
* https://github.com/thoth-station/user-api/pull/1727
* https://github.com/thoth-station/thamos/pull/1099

**Fix scoring of the user stack supplied**

Users could be confronted with issues when adding a new package to requirements and submitting the lock file to the backend. The backend did not invalidate the lockfile sent as it no longer corresponded to the adjusted requiements.

* https://github.com/thoth-station/adviser/issues/2322
* https://github.com/thoth-station/python/pull/470
 
**Thoth Search UI moves to Typescript and adds a advise document compare screen**
Users can now compare multiple advise documents to see the differences and similarities between them. They can access old advise documents through a local history feature added. The home page now has a button for viewing past runs.

- https://github.com/thoth-station/search/issues/60
- https://github.com/thoth-station/search/issues/64

### Component Updates

- [x] user-api: v0.35.0
  - https://github.com/thoth-station/user-api/pull/1729
  - https://github.com/thoth-station/user-api/pull/1727
  - https://github.com/thoth-station/user-api/pull/1730
  
- [x] management-api: v0.18.3
  - https://github.com/thoth-station/management-api/pull/861
  - https://github.com/thoth-station/management-api/pull/868
  - https://github.com/thoth-station/management-api/pull/875

Thanks for the amazing work everyone. :100:
