### ISSUE TITLE
start f35-py310 ingestion

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#2479]
SSIA

**Comment by harshad16** [comment]
We should wait on this.
currently there is still some of the package to be solved:https://grafana.datahub.redhat.com/dashboard/db/thoth-knowledge-graph-content-metrics?refresh=30s&orgId=1&panelId=37&fullscreen

we were blocked by: https://github.com/thoth-station/thoth-application/issues/2484
and are blocked by: https://github.com/thoth-station/thoth-application/issues/2493

**Comment by goern** [comment]
so we put it on this or the next milestone_

**Comment by goern** [comment]
@harshad16 @fridex could you create a tracker issue to outline what we need to do to get to a more stable state? what are the metrics we are using? which components need improvement?

**Comment by goern** [comment]
what is the current state of this?

**Comment by harshad16** [comment]
This PR would fix this: https://github.com/thoth-station/thoth-application/pull/2525
and it is ready for review
