### ISSUE TITLE
graph-sync image fails to pull in dependency monkey workflow

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#2488]
**Describe the bug**

As spotted by @mayaCostantini, there are issues with graph-sync image pull:

```
Back-off pulling image "image-registry.openshift-image-registry.svc:5000/thoth-amun-inspection-prod/graph-sync-job:latest"
```

**To Reproduce**
1. Go to prod and schedule dependency monkey workflow
2. See the error

![image](https://user-images.githubusercontent.com/880687/161500966-9d0e6127-ae95-4fdc-958d-cf0e8e1bf146.png)

**Comment by harshad16** [comment]
@fridex  can you share the name of the cluster.
