### ISSUE TITLE
Amun API fails to start due to config error

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#2491]
**Describe the bug**

Check amun-api in thoth-amun-api-stage repository.

**To Reproduce**
1. Go to thoth-amun-api-stage
2. Click pods and check amun-api
4. See the CreateContainerConfigError

**Expected behavior**

Amun API is up.

**Comment by mayaCostantini** [comment]
From the pod logs:

```
Error: configmap "amun" not found
```
