### ISSUE TITLE
[1pt] Add BigQuery secret to prescriptions-refresh-job workflow spec

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/thoth-application#2494]
**Is your feature request related to a problem? Please describe.**

Add the BigQuery secret generated from a new service account to run the `scorecards.py` handler for prescriptions-refresh-job.

**Comment by codificat** [comment]
/remove-sig stack-guidance
as this is about the deployment of the job

Also, this seems to be
/triage accepted
