### ISSUE TITLE
[2pt] Document for ongoing processes

### ISSUE THREAD

**Issue by meile18** [thoth-station/thoth-application#2501]
**Is your feature request related to a problem? Please describe.**

As a Thoth user, I would like to know where to find information about the ongoing process. For example, this error output: https://github.com/thoth-station/license-solver/issues/55#issuecomment-1082904414

**Comment by harshad16** [comment]
This is fixed now.
User can view aicoe-ci/build check details directly in the PR statuses.
closing the issue.
