### ISSUE TITLE
Required `pre-commit` configuration and module update 

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/thoth-application#2508]
**Problem**
For a repository to be compatible with CI pipeline, the tag of the used `pre-commit` image needs to be updated in prow config file.
On top of that, it is also useful to update pre-commit configuration alone along with the module update itself. 

Related to https://github.com/thoth-station/common/pull/1250#issuecomment-1091521330
@harshad16 

**Steps**
1. Change tags to the `v0.14.3` version for both `pre-commit` and `pytest` images in `.prow.yaml` file
example 1: https://github.com/thoth-station/mi/blob/685ca548a0095f6c6fe51c1e6ba10ee68b18dd3d/.prow.yaml#L9
example 2: https://github.com/thoth-station/mi/blob/685ca548a0095f6c6fe51c1e6ba10ee68b18dd3d/.prow.yaml#L28

2. Update pre-commit related configuration
```
$ pipenv install pre-commit==2.15.0
$ pre-commit autoupdate
```

**Acceptance Criteria**
- [ ] all CI tests for the fixing PR should pass and PR is automatically merged

**Linked epics / issues**
https://github.com/thoth-station/mi-scheduler/pull/221
https://github.com/thoth-station/mi/pull/557
https://github.com/thoth-station/storages/pull/2599
https://github.com/thoth-station/common/pull/1250/files

**Comment by mayaCostantini** [comment]
Not yet but we could integrate this into `aicoe-ci` as and trigger checks for more recent image versions for `pre-commit` and `pytest` on a pull request for example as we already do for [`.aicoe-ci.yaml` base image updates](https://github.com/AICoE/aicoe-ci/blob/master/tasks/base-image-update.yaml).

**Comment by codificat** [comment]
It's unclear to me what the goal/request for this issue would be.

Is it just to raise awareness of the need to update versions across the repos? If so, that might be addressed by some documentation, e.g. in the template project where the pre-commit template is provided.

Or is it a feature request to implement automated updates? If so, then maybe this belongs to the `aicoe-ci` repo instead?

/triage needs-information
/sig devsecops

**Comment by xtuchyna** [comment]
@codificat The goal was that this would be the tracking issue for similar problems. I think that currently every active repo should have this matter already solved, so we can close this

> It's unclear to me what the goal/request for this issue would be.
> 
> Is it just to raise awareness of the need to update versions across the repos? If so, that might be addressed by some documentation, e.g. in the template project where the pre-commit template is provided.
> 
> Or is it a feature request to implement automated updates? If so, then maybe this belongs to the `aicoe-ci` repo instead?
> 
> /triage needs-information /sig devsecops
