### ISSUE TITLE
[3pt] Create sync method in thoth-storages can randomize document listing

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#2529]
As Thoth Service Operator, I would like to have a sync method in which the thoth-storages that can randomize document listing so that we can run multiple sync jobs in parallel.

**Acceptance Criteria**

- [x] Introduce the randomize method for document listing randomize.

**Comment by Gregory-Pereira** [comment]
Addressed by: https://github.com/thoth-station/storages/pull/2625

**Comment by harshad16** [comment]
This is already worked and completed: https://github.com/thoth-station/storages/pull/2625
Thanks for the work :100:
