### ISSUE TITLE
[3pt] create sync-job cronworkflow in thoth-application

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#2530]
As a Thoth Service Operator, I would like to make sure the sync-job uses the adjusted method and we can turn the job into a cronworkflow so that data can be periodically synced into the database (multiple sync jobs can be part of the cronworkflow to support parallel syncs)

**Acceptance Criteria** 

- [ ] create a sync-job cronworklow.
- [ ] create a template of sync-job workflow

**Comment by Gregory-Pereira** [comment]
Addressed by: https://github.com/thoth-station/thoth-application/pull/2524
