### ISSUE TITLE
[3pt] create metrics for sync-job and set the requirements in manifests

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#2533]
As a Thoth Service Operator, I would like to have metrics from the sync-job so that we can create a dashboard from the syncs.

**Acceptance criteria**

- [ ] create metrics in the sync-job
- [ ] update the sync-job workflow and cronworflow to access pushgateway

**Comment by VannTen** [comment]
@harshad16 for the second point : do we need to edit the four files with worklow ? :
```shell
 ls -l sync-job/base/
total 16
-rw-r--r-- 1 max max 1192 Jul 12 14:40 cron-workflow.yaml
-rw-r--r-- 1 max max  310 Jul 12 14:40 kustomization.yaml
-rw-r--r-- 1 max max 3268 Jul 12 14:40 workflow-template.yaml
-rw-r--r-- 1 max max 2055 Jul 12 14:40 workflow.yaml
```
?
If not, which one (Argo  / openshift pipelines If I read correctly)

**Comment by harshad16** [comment]
For the second point, 
i meant to include the required env variable for the manifest files.
for example cronjob: https://github.com/thoth-station/thoth-application/blob/12677b38c63bd96e5d1de3b8591b5f67594c2323/graph-refresh/overlays/aws-prod/cronjob.yaml#L80

**Comment by VannTen** [comment]
Completed by thoth-station/sync-job#73 and #2645
