### ISSUE TITLE
[1pt] Would the team like a public test cluster?

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#2538]
Please confirm with your acknowledgement by giving :+1: or :-1: to this GitHub issue, for having a public test cluster on the op1st Morty cluster and deploy the a test environment to it via argocd

**Comment by harshad16** [comment]
As members have signed this off, we would migrate the apps for now to new cluster.
However we would wait on the use case , before turning on the dpeloyments.

**Acceptance criteria**
- [ ] Rename [overlays/rick-test](https://github.com/thoth-station/thoth-application/tree/master/core/overlays) to moc-test for all component(if present).
- [ ] Update the [path](https://github.com/operate-first/apps/blob/90bb8e035b9d8b93d50d3e6cb0bb3b22950a59e2/argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/core-test.yaml#L10) in argocd apps. 


**Additional context**
Once we have a use case turn on agrocd sync.
-  [ ]  Turn on the sync by add `thoth` in [here](https://github.com/operate-first/apps/blob/90bb8e035b9d8b93d50d3e6cb0bb3b22950a59e2/argocd/overlays/moc-infra/applications/envs/emea/morty/kustomization.yaml#L7).

**Comment by VannTen** [comment]
A question regarding this:

What's the intended usage for the test cluster exactly ? Testing current master
branch from different composents ? Dynamic environments per pull requests (like
Gitlab Review Apps) ?

**Comment by harshad16** [comment]
The attempt was to allow developer to test their pull request with CI deploy.
we dont have resource for dynamic deploy of each pull request.
However, with the recent operate-first change of path, the additional cluster is not available.

This would have to wait for availability of new clusters.
/lifecycle frozen

**Comment by harshad16** [comment]
With the current changes in the team 
the test cluster set up internally in the company would be used for future development.
closing this issue.
