### ISSUE TITLE
[spike] recent discontinuity/gap in the user-api metrics

### ISSUE THREAD

**Issue by codificat** [thoth-station/thoth-application#2540]
**Describe the bug**

I was checking the [dashboard for Thoth User API Metrics for last week](https://grafana.operate-first.cloud/d/b8d70c644a212b2708189159840d351610b7ea89/thoth-service-metrics-user-api?orgId=1&refresh=30m&var-interval=10m&var-instance=user-api-thoth-frontend-prod.apps.balrog.aws.operate-first.cloud&from=now-7d&to=now) and I saw that there is a gap of about 4 days, between Apr 26 to Apr 30

**To Reproduce**
1. Go to [the grafana dashboard for user-api metrics](https://grafana.operate-first.cloud/d/b8d70c644a212b2708189159840d351610b7ea89/thoth-service-metrics-user-api?orgId=1&refresh=30m&var-interval=10m&var-instance=user-api-thoth-frontend-prod.apps.balrog.aws.operate-first.cloud&from=now-7d&to=now)
2. Choose to view "Last 7 days" at 10min interval from the `user-api-thoth-frontend-prod.apps.balrog.aws.operate-first.cloud` instance
3. See the gap

**Expected behavior**
No gaps

**Screenshots**

![imatge](https://user-images.githubusercontent.com/709574/166264783-b96b09cb-6329-4000-9acd-7a6120fb8fe6.png)

**Comment by harshad16** [comment]
There was a problem with the long term storage 
I think the long-term storage would soon be set to past 2 days.
if we require this , let formulate the requirement needs.

/triage accepted

**Comment by codificat** [comment]
from today's review:
/assign @Gregory-Pereira 
who is looking at these metrics

**Comment by goern** [comment]
right now I dont see any metrics on the dashboard. is there some update on this?

**Comment by codificat** [comment]
This seems to be fixed right now
/close
