### ISSUE TITLE
Implement the method for the trigger.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#2583]
Based on the solution agreed in https://github.com/thoth-station/thoth-application/issues/2582, implement the method.
If not is concretely decided, follow the alternate solution:
- use argocd notification job to trigger management-api schema update endpoint.

**Comment by VannTen** [comment]
Hum, isn't this a duplicate of the linked issue ?
Looks like we could close and keep just one

**Comment by harshad16** [comment]
i agree this seems like duplicate issue.
closing this.
follow: #2582
