### ISSUE TITLE
[3pt] Security-indicators are failing on prod because PVC provisioning failed

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/thoth-application#2588]
**Describe the bug**

Cluster: balrog
Namespace: thoth-middletier-prod

From Events of `security-indicator-220608114742-3cf2777548285fc3`:

```
running PreBind plugin "VolumeBinding": binding volumes: provisioning failed for PVC "security-indicator-220608114742-3cf2777548285fc3-workdir"
```

**To Reproduce**

Run solvers for new package in management-api (prod).

**Acceptance criteria**
- [ ] Verify the security indicator can be executed with error in prod

**Comment by codificat** [comment]
From today's backlog review meeting: this Needs verification, but other than that it's understood

**Comment by harshad16** [comment]
This issue is not existing anymore and cant be replicated
seems like the issue causes earlier was due to the PVC storage unavailability in the cluster.
closing this issue.
