### ISSUE TITLE
Token for POST user-api https://test.thoth-station.ninja/api/v1/ui/#/Advise/post_advise_python

### ISSUE THREAD

**Issue by shreekarSS** [thoth-station/thoth-application#2591]
I attempted to use the POST user-api https://test.thoth-station.ninja/api/v1/ui/#/Advise/post advise python, which requires a token; where can I obtain the token?

**Comment by goern** [comment]
could you have a look at this Kevin? thx!

/assign @KPostOffice

**Comment by KPostOffice** [comment]
A token is only required for protected fields such as Kebechet metadata. If you need this you can find it by looking at the corresponding secret in OpenShift.

**Comment by goern** [comment]
what is the status on this?

**Comment by shreekarSS** [comment]
> what is the status on this?

I followed @KPostOffice's steps to obtain the secrets in Openshift, it worked.

**Comment by KPostOffice** [comment]
@shreekarSS I'm closing this, but if there is anything that you would like done about this, feel free to reopen and comment.
