### ISSUE TITLE
Sync failed for management-api on ocp4-stage

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/thoth-application#2611]
**Describe the bug**

Sync failed for revision https://github.com/thoth-station/thoth-application/commit/3a9b32eb53e9bfc960ac58d8b45948fdbe84200b because `the server could not find the requested resource` (see the [argocd UI](https://argocd-server-aicoe-argocd.apps.ocp4.prod.psi.redhat.com/applications/ocp4-stage-thoth-management-api?resource=&conditions=false&operation=true)).

**Comment by harshad16** [comment]
![Screenshot from 2022-07-11 21-36-15](https://user-images.githubusercontent.com/14028058/178389284-5dfd5027-7006-483a-b5f1-392d6e9da66f.png)

This is fixed now.
This issue happens when the argocd server is stuck.
a manual click on `sync` is enough to fix this.
