### ISSUE TITLE
Converting Graph-refresh-job to a Kafka producer. 

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/thoth-application#267]
As graph-refresh-job now acts as a Kafka producer and creates messages for the investigator to process, we need to change the graph-refresh-job deployment config to allow it to be a Kafka producer.
Necessary to support - https://github.com/thoth-station/graph-refresh-job/pull/448

**Comment by pacospace** [comment]
Already solved by @saisankargochhayat
