### ISSUE TITLE
The pod for image analysis did not run

### ISSUE THREAD

**Issue by bissenbay** [thoth-station/thoth-application#291]
**Describe the bug**
I issued an image analysis on `User-API` for `quay.io/thoth-station/image-store:cuda-44324038910ae778b3d15bd2ea80148c8ddcb95f310ccabe6f0499003c0425bd` and the pod did not even start.

**To Reproduce**
1. Go to https://test.thoth-station.ninja/api/v1/ui/#/Image%20Analysis/post_analyze
2. Click on 'Try it out'
3. Fill the image field to be `quay.io/thoth-station/image-store:cuda-44324038910ae778b3d15bd2ea80148c8ddcb95f310ccabe6f0499003c0425bd`
4. Click on 'Execute'
5. Go to https://console-openshift-console.apps.ocp.prod.psi.redhat.com/k8s/ns/thoth-test-core/pods
6. Try to find the pod (you won't see it running)

**Expected behavior**
The pod is running for the analysis

**Comment by harshad16** [comment]
Tested this out in the current test system.
![package-extract-pod](https://user-images.githubusercontent.com/14028058/94676250-aa96e600-0338-11eb-828a-d5d2d459b1ef.png)

Pods that full filed the result.
https://console-openshift-console.apps.ocp.prod.psi.redhat.com/k8s/ns/thoth-test-core/pods/package-extract-8bd9dcae-952198383/logs

Closing this issue
Please feel free to reopen.

**Comment by fridex** [comment]
@harshad16 thanks! :+1: :100:
