### ISSUE TITLE
adviser run fails in backend due to quota requirements.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#294]
**Describe the bug**
The applications like adviser and kebechet workflow runs/execute in backend namespace. 
Adviser workflow runs 5 tasks: 
```
advise: 8gi
investigator: .25gi
graph-sync: .25gi
trigger: .25gi
kebechet-run-result: 2gi
```
one workflow of adviser requires approx 11Gi of memory limit. 
As of now the cluster namespace has only 20Gi memory limit , out of which 13Gi is normally available for workflow, after workflow-controller consumption.
which leads to adviser workflow failure in backend-stage.

**To Reproduce**
1. Go to 'https://khemenu.thoth-station.ninja/'
2. Click on 'https://khemenu.thoth-station.ninja/api/v1/ui/#/Advise/post_advise_python'
3. check for the workflow in backend namespace.
4. See error with oc describe on wf id.

**Additional context**
Stage backend namespace needs quota readjustment

**Comment by fridex** [comment]
> investigator: .25gi
> graph-sync: .25gi
> trigger: .25gi

This looks like wrong configuration for these components. They are not that resource hungry.

**Comment by harshad16** [comment]
> > investigator: .25gi
> > graph-sync: .25gi
> > trigger: .25gi
> 
> This looks like wrong configuration for these components. They are not that resource hungry.
> 
> EDIT: Wanted to fix templates, but it looks like these resources are OK. How did you get 25Gi?
These components are 250 Mb which is approx 0.25 Gb, right?
we definitely have to re-adjust the quota of backend namespace and also the resource requirement of adviser workflow.

**Comment by fridex** [comment]
I think this can be closed with the new Argo workflow-controller deployed. I see successful workflows. See https://github.com/thoth-station/integration-tests/issues/36#issuecomment-680857619 for more info on this. Closing, feel free to reopen if the issue persists.
