### ISSUE TITLE
stage-amun fails to sync

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#352]
**Describe the bug**

Check `stage-amun` application - it fails to sync with the following error message:

```
error validating data: [ValidationError(Template.parameters[10]): unknown field "valueFrom" in com.github.openshift.api.template.v1.Parameter, ValidationError(Template.parameters[11]): unknown field "valueFrom" in com.github.openshift.api.template.v1.Parameter, ValidationError(Template.parameters[12]): unknown field "valueFrom" in com.github.openshift.api.template.v1.Parameter]
```

**To Reproduce**
1. Go to argo cd
2. Click on `stage-amun`
3. See the error

**Expected behavior**

`stage-amun` should be healthy and up to date.

**Comment by pacospace** [comment]
The solution is to create a task in workflow helpers that prepared the message to be sent

Openshift template parameters do not take values from CM:

```
- name: AMUN_API_URL
  description: Where the amun api can be found
  displayName: Amun API URL
  valueFrom:
    configMap:
      name: amun
      key: amun-api-url

- name: INFRA_NAMESPACE
  description: thoth infra namespace
  displayName: Infra namespace
  valueFrom:
    configMap:
      name: amun
      key: infra-namespace

- name: INSPECTION_NAMESPACE
  description: Namespace where inspections are run
  displayName: Inspection namespace
  valueFrom:
    configMap:
      name: amun
      key: inspection-namespace
``

Reference:  https://github.com/thoth-station/thoth-application/pull/311/files

**Comment by pacospace** [comment]
Task required currently to solve using Kafka:

- [ ] Create new message in thoth-messaging
- [ ] Create new task in workflow-helpers to obtain inputs for inspection message
- [ ] Add two tasks to inspection, one to parse message inputs and another one to send message

Instead of sending a message why don't we rely on Argo Workflow metrics?

Tasks:
- [ ] Create Argo workflow metric that send metric about inspection status.

It seems more suitable, as we can see in Grafana dashboard what is happening for the inspections running.

WDYT? @KPostOffice @fridex ?

**Comment by pacospace** [comment]
> Task required currently to solve using Kafka:
> 
> * [ ]  Create new message in thoth-messaging
> * [ ]  Create new task in workflow-helpers to obtain inputs for inspection message
> * [ ]  Add two tasks to inspection workflow, one to parse message inputs and another one to send message
> 
> Instead of sending a message why don't we rely on Argo Workflow metrics?
> 
> Tasks:
> 
> * [ ]  Create Argo workflow metric that send metric about inspection status.
> 
> It seems more suitable, as we can see in Grafana dashboard what is happening for the inspections running.
> 
> WDYT? @KPostOffice @fridex ?

Or do we plan to use that Kafka message for something other than reporting?

**Comment by pacospace** [comment]
Created new issue with tasks in https://github.com/thoth-station/thoth-application/issues/398

**Comment by pacospace** [comment]
> > Task required currently to solve using Kafka:
> > 
> > * [ ]   Create new message in thoth-messaging
> > * [ ]   Create new task in workflow-helpers to obtain inputs for inspection message
> > * [ ]   Add two tasks to inspection workflow, one to parse message inputs and another one to send message
> > 
> > Instead of sending a message why don't we rely on Argo Workflow metrics?
> > Tasks:
> > 
> > * [ ]   Create Argo workflow metric that send metric about inspection status.
> > 
> > It seems more suitable, as we can see in Grafana dashboard what is happening for the inspections running.
> > WDYT? @KPostOffice @fridex ?
> 
> Or do we plan to use that Kafka message for something other than reporting?

The new feature requested is send message from Amun with Kafka so that another component can consume that message

**Comment by pacospace** [comment]
Opened feature: https://github.com/thoth-station/thoth-application/issues/398 this can be closed.
