### ISSUE TITLE
Missing role_binding, Was: Error: INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by bissenbay** [thoth-station/thoth-application#37]
**Describe the bug**
Submitting an example inspection job hits internal server error.

**To Reproduce**
1. Go to 'http://amun-api-thoth-test-core.cloud.paas.psi.redhat.com/api/v1/ui/'
2. Click on '/inspect'
3. Click on 'Try it out'
3. Click on 'Execute'
4. Scroll down to see the error message.

**Expected behavior**
A pod running for inspection job in `thoth-test-core` namespace.

**Comment by harshad16** [comment]
This is already fixed by: https://github.com/thoth-station/thoth-application/commit/36b2e87327fc0fdb007116ad5237d322116bf185
