### ISSUE TITLE
[3pt] Pretty URLs for Argo UI

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#407]
**Is your feature request related to a problem? Please describe.**

I would like to access Argo UI to see what's happening in the cluster. Besides having the UI exposed with autogenerated routes by OpenShift, we could follow our "pretty-url" convention for deployments

**Describe the solution you'd like**

Have pretty URLs that are not deployment/cluster specific:

```
workflows.amun.stage.thoth-station.ninja
workflows.middletier.stage.thoth-station.ninja
workflows.backend.stage.thoth-station.ninja
```

**Describe alternatives you've considered**

Keep URLs untouched.

**Acceptance criteria**
- [ ] create the host in the cloud platform.
- [ ]  place them in thoth-application for deployment.
- [ ] verify these host is working.

**Comment by goern** [comment]
can we have to UI in a read-only mode? or, is it r/o by default?

**Comment by fridex** [comment]
> can we have to UI in a read-only mode? or, is it r/o by default?

Is this relevant to this issue or to https://github.com/thoth-station/thoth-application/issues/409 ?

**Comment by harshad16** [comment]
https://github.com/argoproj/argo/blob/master/docs/argo-server.md

**Comment by harshad16** [comment]
This issue is not required anymore.
closing this issue, as the openshift route can be used.
