### ISSUE TITLE
Unknown Key in ceph: couldn't find key public-bucket-name in for consumers

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#408]
**Describe the bug**
The ceph configmap is missing a key **public-bucket-name**, which is required by consumers.
![solver-unknow-key](https://user-images.githubusercontent.com/14028058/93052020-0566e700-f683-11ea-903c-bb35bdf0bfec.png)

https://github.com/thoth-station/thoth-application/blob/68bac5cc768632b9d2f846619b6191e1e89da939/solver/base/argo-workflows/parse-solved-package.yaml#L73

**To Reproduce**
- check any solver run error in thoth-middletier-stage

**Expected behavior**
No issue while executing solvers

**Additional context**
https://github.com/thoth-station/thoth-application/blob/68bac5cc768632b9d2f846619b6191e1e89da939/solver/base/argo-workflows/parse-solved-package.yaml#L73
https://github.com/thoth-station/thoth-application/blob/68bac5cc768632b9d2f846619b6191e1e89da939/core/overlays/stage/configmaps.yaml#L28

**Comment by harshad16** [comment]
Is the value different from the bucket-name ? @pacospace

**Comment by pacospace** [comment]
The value missing is not required for that component, actually. But we have to add in any case that value for SLO-reporter and advise-reporter, currently it is only in test: https://github.com/thoth-station/thoth-application/blob/68bac5cc768632b9d2f846619b6191e1e89da939/core/overlays/test/configmaps.yaml#L34
