### ISSUE TITLE
Modify graph-refresh component to use the new implementation as producer

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#423]
**Is your feature request related to a problem? Please describe.**
See: https://github.com/thoth-station/graph-refresh-job/issues/433

**Comment by saisankargochhayat** [comment]
@pacospace should we close this?

**Comment by pacospace** [comment]
Did we test graph-refresh with investigator? if everything works correctly yes :)

**Comment by pacospace** [comment]
this is a blocker for this issue: https://github.com/thoth-station/storages/issues/2007

**Comment by saisankargochhayat** [comment]
@harshad16 so the same cronjob I will move to stage? :)

**Comment by harshad16** [comment]
> @harshad16 so the same cronjob I will move to stage? :)

@saisankargochhayat , update the cronjob in test to base and in the cronjob of test , just keep suspend as true

**Comment by saisankargochhayat** [comment]
Closed with #500
