### ISSUE TITLE
Amun Template `amun-inspection-workflow-with-cpu` errors on deploy

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#428]
**Describe the bug**
during deployment of `stage-amun` app, the following error pops up:
```
error validating data: [ValidationError(Template.parameters[10]): unknown field "valueFrom" in com.github.openshift.api.template.v1.Parameter, ValidationError(Template.parameters[11]): unknown field "valueFrom" in com.github.openshift.api.template.v1.Parameter, ValidationError(Template.parameters[12]): unknown field "valueFrom" in com.github.openshift.api.template.v1.Parameter]

```

**To Reproduce**
1. sync https://argocd-server-aicoe-argocd.apps.ocp.prod.psi.redhat.com/applications/stage-amun?operation=true

/kind bug
/assign @fridex

**Comment by pacospace** [comment]
We should remove bits in the openshift templates. There is this new issue created: https://github.com/thoth-station/thoth-application/issues/398

Reference issue: https://github.com/thoth-station/thoth-application/issues/352

**Comment by fridex** [comment]
See https://github.com/thoth-station/thoth-application/issues/384 https://github.com/thoth-station/thoth-application/issues/352

We discussed this on the tech call. The solution is to add messaging, add empty defaults to configmap and let it fail if there are no configuration options supplied.
