### ISSUE TITLE
Setup metrics to monitor failed workflows and their rate

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#429]
**Is your feature request related to a problem? Please describe.**

Let's have an alert when workflows fail. This way we can spot error rate of workflows running in the cluster and identify suspicious behavior. This should work with https://github.com/thoth-station/thoth-application/issues/421 - when something is wrong, we got an alert and replay kafka messages to still serve user requests (if an operational issue happens).

**Describe the solution you'd like**

- [ ] monitor workflows in different namespaces and alert when error rate hit certain treshhold for past X minutes
- [ ] monitor cronworkflows to make sure they happen periodically and are not missed

**Comment by pacospace** [comment]
Pre-requisites: 
- [ ] https://github.com/thoth-station/thoth-application/issues/372
- [ ] https://github.com/thoth-station/slo-reporter/issues/79

**Comment by pacospace** [comment]
> /assign @pacospace

Hey @fridex we receive weekly report with the quality of workflows and workflow tasks:
```
Workflow | Succeeded
-- | --
adviser | 17.83 | %
kebechet | 99.452 | %
inspection | nan | %
provenance_checker | 85.714 | %
qeb_hwt | 70.617 | %
revsolver | nan | %
security | 42.881 | %
solver | 98.324 | %
```

We have also a dashboard related to Argo workflows:
https://grafana.datahub.redhat.com/dashboard/db/thoth-kafka-consumers-and-argo-workflows?refresh=30s&panelId=6&fullscreen&orgId=1

We currently not have any cronworkflows active.

**Comment by fridex** [comment]
> > /assign @pacospace
> 
> Hey @fridex we receive weekly report with the quality of workflows and workflow tasks:
> 
> ```
> Workflow | Succeeded
> -- | --
> adviser | 17.83 | %
> kebechet | 99.452 | %
> inspection | nan | %
> provenance_checker | 85.714 | %
> qeb_hwt | 70.617 | %
> revsolver | nan | %
> security | 42.881 | %
> solver | 98.324 | %
> ```
> 
> We have also a dashboard related to Argo workflows:
> https://grafana.datahub.redhat.com/dashboard/db/thoth-kafka-consumers-and-argo-workflows?refresh=30s&panelId=6&fullscreen&orgId=1

:+1: 

> We currently not have any cronworkflows active.

I think we should start moving away from raw crons and start using cronworkflows. The benefit is extensibility (it's not just one job running but the whole workflow) and we should start monitoring on cronworkflow level so that we know cronworkflows happen - we do not miss any periodic task.

**Comment by pacospace** [comment]
> > > /assign @pacospace
> > 
> > 
> > Hey @fridex we receive weekly report with the quality of workflows and workflow tasks:
> > ```
> > Workflow | Succeeded
> > -- | --
> > adviser | 17.83 | %
> > kebechet | 99.452 | %
> > inspection | nan | %
> > provenance_checker | 85.714 | %
> > qeb_hwt | 70.617 | %
> > revsolver | nan | %
> > security | 42.881 | %
> > solver | 98.324 | %
> > ```
> > 
> > 
> > We have also a dashboard related to Argo workflows:
> > https://grafana.datahub.redhat.com/dashboard/db/thoth-kafka-consumers-and-argo-workflows?refresh=30s&panelId=6&fullscreen&orgId=1
> 
> 
> 
> > We currently not have any cronworkflows active.
> 
> I think we should start moving away from raw crons and start using cronworkflows. The benefit is extensibility (it's not just one job running but the whole workflow) and we should start monitoring on cronworkflow level so that we know cronworkflows happen - we do not miss any periodic task.

Created: https://github.com/thoth-station/thoth-application/issues/654

**Comment by fridex** [comment]
> > > > /assign @pacospace
> > > 
> > > 
> > > Hey @fridex we receive weekly report with the quality of workflows and workflow tasks:
> > > ```
> > > Workflow | Succeeded
> > > -- | --
> > > adviser | 17.83 | %
> > > kebechet | 99.452 | %
> > > inspection | nan | %
> > > provenance_checker | 85.714 | %
> > > qeb_hwt | 70.617 | %
> > > revsolver | nan | %
> > > security | 42.881 | %
> > > solver | 98.324 | %
> > > ```
> > > 
> > > 
> > > We have also a dashboard related to Argo workflows:
> > > https://grafana.datahub.redhat.com/dashboard/db/thoth-kafka-consumers-and-argo-workflows?refresh=30s&panelId=6&fullscreen&orgId=1
> > 
> > 
> > > We currently not have any cronworkflows active.
> > 
> > 
> > I think we should start moving away from raw crons and start using cronworkflows. The benefit is extensibility (it's not just one job running but the whole workflow) and we should start monitoring on cronworkflow level so that we know cronworkflows happen - we do not miss any periodic task.
> 
> Created: #654

Cool, thanks :+1:

**Comment by pacospace** [comment]
Related-To: https://github.com/thoth-station/thoth-application/issues/854

**Comment by goern** [comment]
@pacospace push push, can we get this done? @harshad16 can @gregpere join and help?

**Comment by pacospace** [comment]
> @pacospace push push, can we get this done? @harshad16 can @gregpere join and help?

https://github.com/thoth-station/thoth-application/issues/654 all cronjobs need to be converted to cronworkflows to have these alarms.

Moreover, for the alarms on current workflows, we can discuss what is this rate we want to monitor, let's talk today in thoth tech, in any case let's add them here, so we have the overview of the missing ones: https://github.com/thoth-station/thoth-application/issues/854

**Comment by goern** [comment]
@pacospace what is the current state?

**Comment by pacospace** [comment]
> @pacospace what is the current state?

We have these metrics already sent by argo workflows and they are going to be available in grafana dashboard, but we miss all cronworkflow to monitor their status. 

We track the creation of the alarm for these metrics here: https://github.com/thoth-station/thoth-application/issues/854

**Comment by goern** [comment]
@fridex do you think this is implemented?

**Comment by fridex** [comment]
I see opened other subsequent issues that were created out of this one. If tracking will be done in these issues, we can close this.

/close
