### ISSUE TITLE
check if we can delete aicoe project on ocp

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#432]
It looks like https://console-openshift-console.apps.ocp.prod.psi.redhat.com/k8s/ns/aicoe/deployments is not utilized, can we delete this project and move resourced to aicoe-infra-prod?

/assign @harshad16

**Comment by harshad16** [comment]
Was going to utilize it for the kafka instance , we wanted to run in psi cluster.
once that ticket is either closed or completed, we can decide based on that.
Will keep this open.

**Comment by goern** [comment]
ACK

**Comment by harshad16** [comment]
The namespace: **aicoe** in the psi preview is not a namespace owned by aicoe-thoth-devops team.
In the ocp.prod.psi.redhat.com cluster, some of the aicoe-thoth-devops members had admin access to the namespace.
As we dont have the ownership, we shouldn't delete the namespace.
Current we have deployed Kafka service on the namespace, before moving away from the cluster, we would remove our deployments and vacate.
