### ISSUE TITLE
move cronjob from frontend to backend

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#486]
**Is your feature request related to a problem? Please describe.**
Do we need to run the cronjob in frontend?

**Describe the solution you'd like**
move them to backend.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by harshad16** [comment]
It saves resource utilization. 
Backend and middletier are used for heavy execution of user requests.

**Comment by fridex** [comment]
+1 for keeping it in frontend. middleteir is allocated for data aggregation/pre-computing and backend is used for user requests, as @harshad16 stated. maybe some cronjobs could land in infra (based on their semantics).

**Comment by harshad16** [comment]
closing this issue, we can revisit this one if needed.
