### ISSUE TITLE
Splunk sidecar

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#492]
**Is your feature request related to a problem? Please describe.**
In order to get logs picked up by splunk, we need to deploy a sidecar to each deployment/deploymentConfig 

**Describe the solution you'd like**
There is a RH internal document describing the setup for PSI

**Describe alternatives you've considered**
None

**Additional context**
This applies to stage only

**Comment by goern** [comment]
reconfigure gunicorn to error log to file, https://docs.gunicorn.org/en/stable/settings.html#errorlog

create a `add_splunk_sidecar.yaml' that we can json patch-add to each deploymentConfig

create a `splunk-sidecar` imagestreamtag in `overlay/stage/imagestreamtags.yaml`

**Comment by fridex** [comment]
> reconfigure gunicorn to error log to file, https://docs.gunicorn.org/en/stable/settings.html#errorlog
> 
> create a `add_splunk_sidecar.yaml' that we can json patch-add to each deploymentConfig
> 
> create a `splunk-sidecar` imagestreamtag in `overlay/stage/imagestreamtags.yaml`

Alternatively, wrap entrypoint with `app.sh` to tee the output.
