### ISSUE TITLE
Thoth knows when SI workflow cannot run [8pt]

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#507]
As Thoth Developer,

I want Thoth to know when a package cannot be downloaded so that I don't schedule workflow for that package so that the  system know that  SI cannot be collected about that package version index.

1st part:
- [x] Introduce new column in PPV table with default set to false called `is_si_analyzable`.
- [x] Create alembic migration.
- [x] Create method to set `provides_source_distro` in PPV for existing record.
- [x] Modify query to retrieve SI unananalyzed packages taking into account the new column in PPV.
- [x] Release new thoth-storages

2nd part:
- [x] Create new message in thoth-messaging called `UpdateProvidesSourceDistroMessage`
- [x] Release new thoth-messaging

3rd part:
- [x] Investigator can handle `UpdateProvidesSourceDistroMessage` and use method in storage to set `provides_source_distro` to False so that next round no SI workflow run for that
- [x] Release new investigator

4th part:
- [x] Modify the download-package task in SI workflow to output a message so that another task (send-message) can send a message and output a parameter that is used to filter other steps in the workflow
- [x] Release new workflow-helpers
- [x] Modify SI workflow structure to try to download package and output parameter so that other tasks do not run if set to 0 and add new task send-message if output parameter is set to 0

**Comment by fridex** [comment]
BTW the naming is confusing - what the message was supposed to say:

The package was not analyzed in some workflows (such as security indicators) because it did not provide source distribution. It can still be downloadable (e.g. as a wheel file).

**Comment by pacospace** [comment]
> BTW the naming is confusing - what the message was supposed to say:
> 
> The package was not analyzed in some workflows (such as security indicators) because it did not provide source distribution. It can still be downloadable (e.g. as a wheel file).

Sorry I didn't update it here: but in the PR we actually went for `NotDownloadedPackageMessage`: https://github.com/thoth-station/messaging/pull/271#discussion_r496054774

**Comment by pacospace** [comment]
> BTW the naming is confusing - what the message was supposed to say:
> 
> The package was not analyzed in some workflows (such as security indicators) because it did not provide source distribution. It can still be downloadable (e.g. as a wheel file).

Should we change the flag to `is_si_analyzable`?

**Comment by fridex** [comment]
> > BTW the naming is confusing - what the message was supposed to say:
> > The package was not analyzed in some workflows (such as security indicators) because it did not provide source distribution. It can still be downloadable (e.g. as a wheel file).
> 
> Should we change the flag and generalize to `is_si_analyzable`?

IMHO that would be more appropriate given the semantics. :+1:

**Comment by KPostOffice** [comment]
I know it's kind of to late, but I would have liked to have the flag represent what we are actually marking it for, i.e. something like `ProvidesSourceDistro` this is why I used `is_downloadable` which I understand isn't quite right.

**Comment by fridex** [comment]
> I know it's kind of to late, but I would have liked to have the flag represent what we are actually marking it for, i.e. something like `ProvidesSourceDistro` this is why I used `is_downloadable` which I understand isn't quite right.

It's never late. Any other proposed solution?

**Comment by KPostOffice** [comment]
> > I know it's kind of to late, but I would have liked to have the flag represent what we are actually marking it for, i.e. something like `ProvidesSourceDistro` this is why I used `is_downloadable` which I understand isn't quite right.
> 
> It's never late. Any other proposed solution?

`ProvidesSourceDistro` or `IsSourceDownloadable` or `DownloadSourceFails`

I'm partial to the first one, I think it is clear what the message and flag represent so that it can be used outside of the context of security indicators if it is useful

**Comment by fridex** [comment]
> > > I know it's kind of to late, but I would have liked to have the flag represent what we are actually marking it for, i.e. something like `ProvidesSourceDistro` this is why I used `is_downloadable` which I understand isn't quite right.
> > 
> > 
> > It's never late. Any other proposed solution?
> 
> `ProvidesSourceDistro` or `IsSourceDownloadable` or `DownloadSourceFails`
> 
> I'm partial to the first one, I think it is clear what the message and flag represent so that it can be used outside of the context of security indicators if it is useful

I think the original message was in its negated form - stating that the package does not provide source distribution hence it cannot be analyzed by the security indicator workflow. So to my understanding, you want to add a boolean flag to messages?

**Comment by KPostOffice** [comment]
The original was `UpdateIsDownloadableMessage` and the flag on the db was `is_downloadable`

**Comment by fridex** [comment]
> The original was `UpdateIsDownloadableMessage` and the flag on the db was `is_downloadable`

Makes sense. Considering the message is sent also when the security indicator workflow finishes (not only on failures), it can make sure we keep the database in sync :+1:

**Comment by pacospace** [comment]
@KPostOffice do you make changes accordingly? :)

**Comment by KPostOffice** [comment]
will do :)

**Comment by pacospace** [comment]
> will do :)

Thanks Kevin!!
