### ISSUE TITLE
Require two approvals before automerging a pull request

### ISSUE THREAD

**Issue by anishasthana** [thoth-station/thoth-application#527]
We could like to configure automerge to require at least two approvals before merging any PRs to the following repositories:

1. https://github.com/AICoE/Internal-Data-Hub
2. https://github.com/AICoE/idh-manifests

How would we go about configuring this?

**Comment by goern** [comment]
I see, what is the use case for that? why isn't the distinction between reviewers and approvers not good enough? https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md

/kind feature
/kind question

**Comment by anishasthana** [comment]
So we don't want PRs to be gated by specific members of our team for configuration-related items. The idea is we'd have at least two people reviewing every PR and if we get two approves we ship it.

**Comment by goern** [comment]
I think Kubernetes' concept (which we implement here) is to have approvers with ultimate merging-power, the four eyes concept you would like to implement is done via reviewers and approvers. You can configure this per subdirectory. Please have a look at owners.md

**Comment by anishasthana** [comment]
Apologies, I missed this somehow -- we don't want there to necessarily be a distinction between any members of the team for those two repositories.

So if I'm reading what you're saying correctly, we would have two people marked as reviewers for PRs, and once they both give a +1 an owner will be assigned to give the final approval?

Is it possible for the approvers and reviewers list to overlap and still function like this?

**Comment by HumairAK** [comment]
So this is a more of an argument for convenience. The idea of just clicking "approve" and having the bot decide when there's enough approvers to merge lifts the burden off the reviewer/approver, and shifts it to the bot. What we would like basically is this: 

Alex submits a PR: 
- Anish looks at it as a reviewer, clicks approve -- doesn't worry about whether merging criteria has met (this is the bot's job) 
- Maulik looks at it as a reviewer, clicks approve -- again doesn't worry merging criteria 

The Bot then evaluates through each stage whether it can merge, along with the pre-commit/ build-checks etc. 

Currently this merging criteria is 1 approval required. We're simply asking for the option to change this value via some config (like we do with other ci configs in the repo) so that it can be 2 approvals. In other words let the repo owners decide.

**Comment by anishasthana** [comment]
@goern bump

**Comment by harshad16** [comment]
Based on the above comments, I understand the requirement here. 
So as @goern  already stated we are trying to follow the Kubernetes concept of maintaining a `OWNERS` file for defining list of owners and reviewers. 
we could configure adding `lgtm` label based on reviewer review and have it as an additional check for merging. with this the merge would depend upon one `lgtm` and one `approved`. However the distinguishment between reviewers and approvers is needed in this case, a member who is listed as owner and reviewer , would by-pass this check and their approval would be directly considered for merging. 


with the information presented by @HumairAK  and @anishasthana  it feels like, all members need to have both owner's and reviewers' privileges. In that case, the number reviewed `approval` can be managed directly by the GitHub setting. Github provides  adding branch rules, which has a feature for selecting the number of review approval required for merge, this can be configured (for your case it would be 2) 

![reviewer-rule](https://user-images.githubusercontent.com/14028058/101630316-beea1400-3a48-11eb-8ca0-dfc3d4aa33d8.png)

If this feels satisfactory, please try to use it and let us know as well. If not then we would have to develop something for this request. 
As of now, I have this solution, Maybe @goern  has some more ideas.

**Comment by anishasthana** [comment]
Yep I saw this just the other day! in that case, should we disable merging with sesheta?

**Comment by harshad16** [comment]
> Yep I saw this just the other day! in that case, should we disable merging with sesheta?

no, i don't think we should disable bot as, GitHub branch rules would just enforce rules , it would just work as a gatekeeper but won't merge it till i know.

**Comment by harshad16** [comment]
tide merge is by-passing GitHub branch rules https://github.com/AICoE/aicoe-cd/pull/198#issuecomment-742058388.

**Comment by harshad16** [comment]
The solution describes to use the GitHub branch protection works for this case. 
please to this comment. https://github.com/operate-first/apps/issues/81#issuecomment-756853147

**Comment by anishasthana** [comment]
Ah that makes sense. I have fixed the settings now. Should we close this issue for now? We can always re-open if we notice problems
