### ISSUE TITLE
Create stage-thoth-slo-reporter

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#528]

**Comment by harshad16** [comment]
Pull request already in place: https://github.com/AICoE/aicoe-cd/pull/136

**Comment by pacospace** [comment]
> Pull request already in place: [AICoE/aicoe-cd#136](https://github.com/AICoE/aicoe-cd/pull/136)

Thanks Harshad! I opened it for tracking :)

**Comment by harshad16** [comment]
the application is now available and being deployed by argocd: https://argocd-server-aicoe-argocd.apps.ocp.prod.psi.redhat.com/applications/stage-thoth-slo-reporter

**Comment by pacospace** [comment]
Thank you very much @harshad16! We can close the issue then :)
