### ISSUE TITLE
Learn about not SI analyzable python packages using SI analyzers

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#538]
**Is your feature request related to a problem? Please describe.**
As Thoth developer and Thoth manager,

I would like Thoth to learn about not SI analyzable python packages so that:

- Thoth does not reschedule SI analysis for packages with errors;
- Thoth can collect errors and analyze them to provide better advice or propose solutions upstream for packages used for analysis.

**Describe the solution you'd like**
Follow solver-like approach: https://github.com/thoth-station/si-bandit/issues/39#issuecomment-703452516, so that on the syncing side, Thoth learns about these errors.

**Describe alternatives you've considered**

**Additional context**
See: https://github.com/thoth-station/si-bandit/issues/39

**Comment by pacospace** [comment]
I think we can consider this solved, @KPostOffice WDYT?

**Comment by KPostOffice** [comment]
++
