### ISSUE TITLE
Provide topic for hactoberfest

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#542]
**Is your feature request related to a problem? Please describe.**

See https://www.youtube.com/watch?v=FxBv4FMcDgo&ab_channel=DigitalOcean

**Describe the solution you'd like**

All thoth repos have `hacktoberfest` topic.

**Comment by harshad16** [comment]
all active repos are updated with `hacktoberfest` topic label, with help of a [script](https://gist.github.com/harshad16/c87c3d0545376813adc9de064f504bf4).
can be verified by doing a curl or any request to repo topics.
`curl  -H "Accept: application/vnd.github.mercy-preview+json" https://api.github.com/repos/thoth-station/{repo}/topics`

**Comment by fridex** [comment]
@harshad16 very nice, thanks!! :100: :+1:
