### ISSUE TITLE
Port application to Python 3.8

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#545]
**Is your feature request related to a problem? Please describe.**

As of now, we run Thoth components using Python 3.6 running on top of UBI 8 container image. It would be nice to port the application to UBI 8 running Python 3.8.

**Describe the solution you'd like**

Port all the Thoht components to Python 3.8 running UBI 8.

**Thoth components to be migrated**

 - [x] adviser
 - [x] advise-reporter
 - [x] amun
 - [x] buildlog-parser
 - [x] build-watcher
 - [x] cve-update
 - [x] graph-backup-job
 - [x] graph-refresh
 - [x] graph-sync
 - [x] init-job
 - [x] investigator
 - [x] kebechet
 - [x] management-api
 - [x] metrics-exporter
 - [x] mi-scheduler
 - [x] package-extract
 - [x] package-releases
 - [x] package-update
 - [x] qeb-hwt-github-app
 - [x] revsolver
 - [x] security-indicators
 - [x] sefkhet-abwy
 - [x] slo-reporter
 - [x] solver
 - [x] user-api

**Additional tasks**

 - [ ] make sure the application stack runs correctly using Python 3.8
 - [ ] evaluate performance impact on adviser

**Work to be done for each repo**

- [x] clone each repo based on the list above
- [x] adjust Pipfile so that Python 3.8 is used
- [x] trigger relocking so deps are relocked to Python 3.8 and Pipfile.lock is adjusted correspondingly
- [ ] commit changes to each repo, make sure tests pass (unit tests)
- [ ] test application in test environment so we are sure the application works correctly and can be run on Python 3.8 (integration tests)

Each time a component is migrated, a base image needs to be adjusted so that ubi8-py38 is used as a base image. A new release for each component will be required once to py38 transition is done.

**Comment by bissenbay** [comment]
@fridex Do we need to change from `python_version: "3.6"` to `python_version: "3.8"` in all `.thoth.yaml` files for all repos?
```
runtime_environments:
  - name: 'rhel:8'
    operating_system:
      name: rhel
      version: "8.0"
    python_version: "3.8"
    recommendation_type: latest
```

**Comment by fridex** [comment]
> @fridex Do we need to change from `python_version: "3.6"` to `python_version: "3.8"` in all `.thoth.yaml` files for all repos?

Yes :+1:

**Comment by fridex** [comment]
We will probably also need to change the base image (use [s2i-thoht-ubi-8-py38](https://quay.io/repository/thoth-station/s2i-thoth-ubi8-py38)) to build the components. CC @harshad16

**Comment by harshad16** [comment]
yes , we have to update the base image to build the components.
https://github.com/thoth-station/amun-api/pull/590#issuecomment-732707776

**Comment by bissenbay** [comment]
> yes , we have to update the base image to build the components.
> [thoth-station/amun-api#590 (comment)](https://github.com/thoth-station/amun-api/pull/590#issuecomment-732707776)

thanks

**Comment by bissenbay** [comment]
> > @fridex Do we need to change from `python_version: "3.6"` to `python_version: "3.8"` in all `.thoth.yaml` files for all repos?
> 
> Yes

thanks

**Comment by fridex** [comment]
There is also a need to bump python version (aicoe config, thoth config and pipfile) in repositories which hold libraries (common, python, ...) so that we test using Python 3.8.

**Comment by bissenbay** [comment]
> There is also a need to bump python version (aicoe config, thoth config and pipfile) in repositories which hold libraries (common, python, ...) so that we test using Python 3.8.

@fridex could you please add the list of repos that needs to be worked as well please?

**Comment by fridex** [comment]
> @fridex could you please add the list of repos that needs to be worked as well please?

I tried to filer them out based on GitHub API call. Not sure if they are all and if they all have managed Python dependencies (and are not repeated with the listing above):

 - [ ] thoth
 - [ ] storages
 - [ ] graph-sync-job
 - [ ] dependency-monkey
 - [ ] common
 - [ ] analyzer
 - [ ] lab
 - [ ] notebooks
 - [ ] adviser
 - [ ] nepthys
 - [ ] amun-client
 - [ ] amun-hwinfo
 - [ ] python
 - [ ] build-watcher
 - [ ] package-analyzer
 - [ ] invectio
 - [ ] messaging
 - [ ] mi
 - [ ] graph-backup-job

Hope it helps. Let me know otherwise :+1:

**Comment by fridex** [comment]
... and some others that were originally paginated away:

 - [ ] package-update-job
 - [ ] s2i
 - [ ] micropipenv
 - [ ] source-management
 - [ ] fext
 - [ ] revsolver
 - [ ] buildlog-parser
 - [ ] glyph
 - [ ] sync-job
 - [ ] image-pusher
 - [ ] dependency-monkey-zoo
 - [ ] termial-random

**Comment by bissenbay** [comment]
@fridex https://github.com/thoth-station/dependency-monkey-zoo does not contain any `.aicoe-ci.yaml`, '.thoth.yaml`, 'Pipfile', 'Pipfile.lock', so should we skip it?

**Comment by fridex** [comment]
> @fridex https://github.com/thoth-station/dependency-monkey-zoo does not contain any `.aicoe-ci.yaml`, '.thoth.yaml`, 'Pipfile', 'Pipfile.lock', so should we skip it?

Yes, that repo can be skipped :+1:

**Comment by bissenbay** [comment]
> > @fridex https://github.com/thoth-station/dependency-monkey-zoo does not contain any `.aicoe-ci.yaml`, '.thoth.yaml`, 'Pipfile', 'Pipfile.lock', so should we skip it?
> 
> Yes, that repo can be skipped

thanks

**Comment by bissenbay** [comment]
@fridex https://github.com/thoth-station/thoth and https://github.com/thoth-station/notebooks don't have `Pipfile`, `.thoth.yaml` files, so will be skipped.

**Comment by fridex** [comment]
Thanks, @bissenbay for making this happen. Closing as all the parts are done. The remaining part, checking adviser's performance on different python interpreter version can be handled in a different issue.

Thanks! :+1:

**Comment by harshad16** [comment]
Based on the above comment. Closing this issue.
Thank you for all the work @bissenbay
