### ISSUE TITLE
Data Driven Engineering: Increase Adviser Resources (Memory and CPU)

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#559]
Our daily reports analyzing quality of results show that many Adviser Runs are failing due to:
- `Resolver was killed as allocated CPU time was exceeded` - https://thoth-station.ninja/j/cpu_time_exceeded
- `Resolver was killed as allocated memory has been exceeded (OOM)` - https://thoth-station.ninja/j/oom

![Screenshot from 2020-10-12 11-02-47](https://user-images.githubusercontent.com/27498679/95728559-ef494800-0c7b-11eb-8ede-a9b1c8f35299.png)

Let's increase memory for adviser run.

**Comment by fridex** [comment]
This is most probably because of transitive dependencies missing. Resolver is trying to find a resolution but not all transitive dependencies are resolved - hence it cannot find it. Discussed this with @harshad16
