### ISSUE TITLE
Service can respond with 404 once an analysis is submitted

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#568]
**Describe the bug**

With the transition to Kafka and massage queuing, it can happen that a user submits an analysis (e.g. advise) and immidiatelly gets 404 for the given request.

**To Reproduce**
1. Make sure the system is running workload so that the request gets queued
2. Perform `thamos advise` and make sure the request gets queued but not immediately processed
3. See 404 returned by the service and the error reported by thamos

**Expected behavior**

No 404 is returned.

**Additional context**

This issue is caused by the "lost context" - we schedule an advice by sending a message to Kafka which gets queued. At this point, the system does not know whether the given adviser request exists - no kubernetes object is created and no data are available on Ceph.

**Comment by fridex** [comment]
We can store information about the submitted analysis on ceph - in that case, we would create an object that would note down the given request was accepted by the system and is in the pending state (queued). Once we will be checking for results, we could check if the given request is not in the pending state.

**Comment by fridex** [comment]
Ideally, we could restructure how we store results on ceph - instead of having adviser-id referencing directly the given adviser request, it could be used as a prefix for other data. This way we could store also inputs for adviser that would be used by Argo workflows, instead of passing these inputs directly to openshift's env vars:

```
s3://.../<adviser-id>/Pipfile
s3://.../<adviser-id>/Pipifle.lock
s3://.../<adviser-id>/environment.json
s3://.../<adviser-id>/request.json  # Used to check if the given analysis is in "pending state"
s3://.../<adviser-id>/result
s3://.../<adviser-id>/library_usage.json
```

**Comment by bissenbay** [comment]
@fridex @pacospace This is exactly what I experience when I schedule thamos advise in `integration-tests`.
