### ISSUE TITLE
Modify cve-update component to use the new implementation as producer

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#575]
**Is your feature request related to a problem? Please describe.**
See new package release producer: https://github.com/thoth-station/cve-update-job/issues/373

**Additional context**

**Comment by bissenbay** [comment]
@pacospace @harshad16 I think we did change in test in this PR: https://github.com/thoth-station/thoth-application/pull/593, but I'm not sure whether we tested it, can we test it and if this works, let's move changes to `/base`?

**Comment by pacospace** [comment]
> @pacospace @harshad16 I think we did change in test in this PR: #593, but I'm not sure whether we tested it, can we test it and if this works, let's move changes to `/base`?

Let's do it! Thanks @bissenbay!
