### ISSUE TITLE
Expose Thoth version on API endpoints

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#609]
**Is your feature request related to a problem? Please describe.**

See comment in https://github.com/thoth-station/core/pull/247#pullrequestreview-522759294

We should expose version of Thoth in our endpoints (include it in response headers). For this purpose, we should include https://github.com/thoth-station/thoth-application/blob/master/version.py in the build user-api container image.

**Describe the solution you'd like**

Include https://github.com/thoth-station/thoth-application/blob/master/version.py in user-api container image so that user-api can expose Thoth version information.

**Describe alternatives you've considered**

Update this manually, but it is error-prone process.

**Acceptance Criteria**
- git tag value of thoth-application is shown as part of the HTTP response as a header

**References**
- https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/

**Comment by harshad16** [comment]
https://github.com/thoth-station/core/pull/247#pullrequestreview-522759294

**Comment by harshad16** [comment]
Ex:  x-thoth-version: 0.22.1

**Comment by harshad16** [comment]
https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/

**Comment by goern** [comment]
what is the status of this?

**Comment by harshad16** [comment]
plan on providing calender release on the HEADERS of the API endpoint.

**Comment by codificat** [comment]
> plan on providing calender release on the HEADERS of the API endpoint.

I take that as:
/triage accepted
/assign @harshad16

**Comment by goern** [comment]
is this something we still want?! @harshad16
