### ISSUE TITLE
Aggregate API provided by Python packages

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#618]
**Is your feature request related to a problem? Please describe.**

Based on https://github.com/thoth-station/adviser/issues/1545 we might want to gather API provided by Python packages we analyze. This way we aggregate information about symbols that are provided by packages in the Python ecosystem and we will be able to recommend packages that provide desired symbols users need and use.

**Describe the solution you'd like**

- [ ] create a workflow that would aggregate information about API provided by Python packages in the Python ecosystem
- [ ] use invectio to aggregate symbols provided by Python packages
- [ ] store results on Ceph (no need to sync results in the database)
- [ ] create an adapter in thoth-storages that can store and retrieve library symbols 
- [ ] implement a pipeline unit that can be registered when library symbols are available for the given package and the user submits library usage so the unit can filter out packages that do not provide required symbols

**Comment by fridex** [comment]
I'm not sure if results would be relevant and usable given the variety of Python code, dynamic programing code nature. We can convert this to a spike if we want to check this.

**Comment by harshad16** [comment]
closing this as we discused this in the tech talk and found it can be prone to security issues.
