### ISSUE TITLE
Consider moving dependency monkey to another namespace

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#629]
**Is your feature request related to a problem? Please describe.**

As we run background data aggregation in middletier namespace, Dependency Monkey jobs are queued and take some time to execute.

**Describe the solution you'd like**

It might be a good idea to place Dependency Monkey to another namespace so that we can run it and aggregate the data without worrying about too occupied middletier namespace.

**Comment by harshad16** [comment]
we can run them in infra namespace.
any thought on other namespaces?

**Comment by fridex** [comment]
> we can run them in infra namespace.
> any thought on other namespaces?

What about directly amun-inspection namespace? It might not be that nice as there will be created new dependency to create rolebindings for accessing it from management-api but semantically it might be the right place.

**Comment by harshad16** [comment]
Thats a good point, so we can have dependency monkey in amun-inspection for our deployments. 
we can check on the role bindings and run it in the stage environment. 
if that feels too confusing then we can get it into infra namespace, as it contains only metrics-exporter and investigator

**Comment by fridex** [comment]
> if that feels too confusing then we can get it into infra namespace, as it contains only metrics-exporter and investigator

The infra namespace was designed for infrastructure components, I would not put it in there (also, it will require argo workflows being present and such).

**Comment by fridex** [comment]
/label priority/important-soon

Bumping priority of this. As solvers run in deployment which occupy resources, it's basically impossible to reasonably run dependency monkey.

**Comment by goern** [comment]
is this actively being worked on?

/lifecycle stale ?

**Comment by harshad16** [comment]
This one is complete with the pull request attached in the issues.
However, didn't close as we were facing issues at that time
It was fixed and this issues corresponds to the fixes https://github.com/thoth-station/amun-api/issues/611
closing this issue. Thanks.
