### ISSUE TITLE
Monitor pytorch releases automatically

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#632]
**Is your feature request related to a problem? Please describe.**

We would like to automatically monitor releases done by pytorch team.

Pytorch, as of now, does not provide PEP-503 complaint Python package index - see the report at https://github.com/pytorch/pytorch/issues/47670 This has drawbacks as we cannot fit this index structure easily into our current implementation.

**Describe the solution you'd like**

Ideally, have pytorch available on a PEP-503 simple API complaint repository index.

**Describe alternatives you've considered**

Add support for `--find-links` alternative, which is not nice from a monitoring point of view as well as from integration point of view (Python tooling for proper version locking).

**Comment by harshad16** [comment]
@fridex is this what we are looking for in term of pytorch?  
Release on pypi: https://pypi.org/project/torch/
simple repository API : https://pypi.org/simple/torch/

**Comment by fridex** [comment]
It looks like they provide different builds (e.g. CUDA) at https://download.pytorch.org/whl/torch_stable.html. See the "Start locally" selection at https://pytorch.org/get-started/locally/

**Comment by harshad16** [comment]
oh, I see, thanks for pointing to this.

**Comment by goern** [comment]
@harshad16 do you take care of this issue?

**Comment by fridex** [comment]
I'm not sure if there is anything to be done on our side. It looks like pytorch community is already aware of the missing simple API repository - see https://github.com/pytorch/pytorch/issues/25639 Once they provide it, we should just register it in the Thoth's knowledge base and start analyzing/ingesting the data.

**Comment by goern** [comment]
so we need to adjust init-job to add the index?

**Comment by fridex** [comment]
> so we need to adjust init-job to add the index?

Yes, once the pytorch index that conforms to PEP-503 will be available. For our existing deployments, we will need to just register the PEP-503 index via management API.

**Comment by fridex** [comment]
The following pytorch indexes were registered in test, stage and prod:

* https://download.pytorch.org/whl/cu111 (CUDA-11.1 builds)
* https://download.pytorch.org/whl/cpu (CPU builds)

**Comment by fridex** [comment]
Related issue on the pytorch index that prevents from analyzing pytorch releases: https://github.com/pytorch/pytorch/issues/63098
