### ISSUE TITLE
Integrate with Op1st Loki

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#675]
**Is your feature request related to a problem? Please describe.**
As a Thoth Ops,
I want to aggregate all the logs from all the pods,
so that I can browse and search them via a web UI.

**Describe the solution you'd like**
Let's send all the logs to Operate-First Loki instance on MOC

**Describe alternatives you've considered**
n/a

/kind feature
/assign @harshad16 
/assign @4n4nd
/priority important-soon

**Comment by goern** [comment]
seeAlso https://github.com/thoth-station/common/issues/1089

**Comment by tumido** [comment]
cc @4n4nd 

I think implementing this would allow us to also lower the CPU reservation in the Operate First environment. For example - if you can show the CI/Prow logs via Loki, there's no need to leave the finished pods to exist in the cluster anymore - hence freeing up the requested CPU/other resources.

**Comment by harshad16** [comment]
The loki is been setup on the operate-first side , thanks to @4n4nd :tada: 
an also integrated to the dashboard : https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/d/liz0yRCZz/loki-dashboard-quick-search?orgId=1&var-namespace=thoth-frontend-prod&var-pod=user-api-17-nbh29&var-search=level%3Dwarn
we can view Project Thoth components logs in the grafana dashboard

and can query from loki directly via API.
https://www.operate-first.cloud/users/apps/docs/observatorium/loki/README.md#loki-frontend
https://grafana.com/docs/loki/latest/api/#get-lokiapiv1query_range

**Comment by harshad16** [comment]
Already been demoed in a part of operate-first and released to youtube:
https://www.youtube.com/watch?v=ryKqZ4Lwr4Y
