### ISSUE TITLE
Setup Argo UI

### ISSUE THREAD

**Issue by bissenbay** [thoth-station/thoth-application#70]
**Is your feature request related to a problem? Please describe.**
When an inspection job is scheduled, it would be better to look at the workflows in Argo UI.

**Comment by goern** [comment]
What hindered you from doing so?

**Comment by goern** [comment]
ping @bissenbay

**Comment by goern** [comment]
@bissenbay can we close this?

**Comment by bissenbay** [comment]
@goern I think we can close this, WDYT @harshad16 ?

**Comment by harshad16** [comment]
this is already existing for test and for stage it would be available with #73
