### ISSUE TITLE
khemenu is down

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#724]
**Describe the bug**

khemenu seems to be down.

**To Reproduce**
1. Go to https://khemenu.thoth-station.ninja/
2. See "Application is not available" router error

**Expected behavior**

khemenu should be up.

**Comment by harshad16** [comment]
The stage links seem to be working: https://stage.thoth-station.ninja/api/v1/ui/
I think we configure the https://khemenu.thoth-station.ninja/ to serve production service hosted on the CNV cluster. 
which is currently have an issue for the past few weeks, the infra team has sent us a notification about it. 

@goern  can you verify this on route53, and switch the link to the stage.

**Comment by goern** [comment]
NACK, stage is still on an RH-internal OpenShift Cluster

**Comment by harshad16** [comment]
Thanks, @goern for pointing me in the right direction.
There was some issues with the route. Fixed it with https://github.com/thoth-station/thoth-application/commit/a1a79694804460151b4d1db45c526e3952d8cea4
https://khemenu.thoth-station.ninja/api/v1/ui/ is fixed. 
closing the issue.
