### ISSUE TITLE
Provide admin password for PostgreSQL database

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#725]
**Is your feature request related to a problem? Please describe.**

As shown in the example in [1], we need to have the admin password for PostgreSQL databases. Currently, we do not setup the admin password. This could be accomplished by providing `POSTGRESQL_ADMIN_PASSWORD` environment variable to the postgresql container image as described in [2]

**Describe the solution you'd like**

Add environment variable for configuring PostgreSQL password as described in [1].

**Describe alternatives you've considered**

There are no alternatives on how to enable the extension. The admin password is needed to enable the extension.

**Additional context**

[1] https://github.com/sclorg/postgresql-container/pull/394
[2] https://docs.openshift.com/enterprise/3.1/using_images/db_images/postgresql.html#postgresql-changing-passwords

**Comment by harshad16** [comment]
Thanks, @fridex for the detailed description. 
will enable this feature on the test cluster.

**Comment by harshad16** [comment]
The feature is enabled in Test Cluster,
what all components need access to the admin password? based on that we would update the password accessibility to the components. 
@KPostOffice

**Comment by harshad16** [comment]
Based on the discussion with @KPostOffice  

Following actions would be considered

1) CREATE EXTENSION amcheck
2) QUERY USING amcheck

Step (1) one would be done on the cluster setup or db setup.   
Metrics Exporter would be used for step (2), with a metric that we can use to alert when DB corruption is detected.


Next Step:

Test the amcheck in the test environment with metrics-exporter.
If successful, replicate on all the databases in each environment.

**Comment by goern** [comment]
@KPostOffice @harshad16 can we close this?

**Comment by harshad16** [comment]
we have change the privileges instead of using the admin user.
with the change of user to super user , the admin password setup is not required.
we have include it in test for future extension enablement and testing.
More details here: https://github.com/thoth-station/storages/issues/2250#issuecomment-801633584
Also document this with a doc.

closing this issue.
