### ISSUE TITLE
Build postgresql contianer image with pg_stat_statements extension enabled

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#726]
**Is your feature request related to a problem? Please describe.**

To enable `pg_stat_statements` extension, we need to provide additional configuration to postgres as shown in [1] example.

**Describe the solution you'd like**

 To accomplish this, we need to build a posgresql container image as described in [1] and use this container image to deploy postgres. The prerequisite for this to work is to have admin password setup as reported in https://github.com/thoth-station/thoth-application/issues/725

**Additional context**

[1] https://github.com/sclorg/postgresql-container/pull/394
[2] https://github.com/thoth-station/thoth-application/issues/725

**Comment by goern** [comment]
@harshad16 can we close this?

/lifecycle stale

**Comment by harshad16** [comment]
our posgresql image satisfied the requirement and extensions were being easily installed. 
we have also setup the admin user for the postgresql in test https://github.com/thoth-station/thoth-application/blob/28985c1327d6c62e68e3ffd1850e9ce42666e8ea/core/overlays/test/secrets.enc.yaml#L51

This extension is now enabled on all cluster databases.
```
thoth=# \dx
                                    List of installed extensions
        Name        | Version |   Schema   |                        Description                        
--------------------+---------+------------+-----------------------------------------------------------
amcheck            | 1.0     | public     | functions for verifying relation integrity
pg_stat_statements | 1.6     | public     | track execution statistics of all SQL statements executed
plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
(3 rows)
```
