### ISSUE TITLE
Thoth Grafana dashboard json publicly accessible for auto-deployment via ArgoCD

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#738]
**Is your feature request related to a problem? Please describe.**
We keep our Grafana dashboard JSON in the thoth-ops repo which is private due to the other components it contains. 
If we can move the Grafana dashboard JSON to some public repo, then it can be directly used for populating the dashboard on Grafana via ArgoCD. 

Question: where should we move them too? 

**Describe the solution you'd like**
we can keep them under thoth-application as it contains almost all thoth-station deployment requirements.

**Additional context**
This is regarding the CNV production Grafana dashboard.

**Comment by harshad16** [comment]
@pacospace @goern 

/label sig-devops kind/question

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> We keep our Grafana dashboard JSON in the thoth-ops repo which is private due to the other components it contains.
> If we can move the Grafana dashboard JSON to some public repo, then it can be directly used for populating the dashboard on Grafana via ArgoCD.
> 
> Question: where should we move them too?
> 
> **Describe the solution you'd like**
> we can keep them under thoth-application as it contains almost all thoth-station deployment requirements.
> 

hey @harshad16 thanks for the question! 

I totally agree on that, moreover, there is nothing confidential in the data of the dashboard, therefore, we can definitely move them to thoth-application to have everything thoth related there :) 

> **Additional context**
> This is regarding the CNV production Grafana dashboard.

let's just keep in mind that the json dashboard is generalized to all environments, in this way we do not need to maintain many json files, but we just provide a new endpoint related to the metrics exposed and we can switch between environments using a tab.

In any case is pretty simple to delete other endpoints once loaded in Grafana!

Let me know what you think :)

**Comment by harshad16** [comment]
Thanks for your views @pacospace 
I will move the Grafana json to the thoth-application repo. 

> let's just keep in mind that the JSON dashboard is generalized to all environments, in this way we do not need to maintain many JSON files, but we just provide a new endpoint related to the metrics exposed and we can switch between environments using a dropdown list in grafana.

I think they would differ as the name of the data source can change, it is most important for them to populate.
