### ISSUE TITLE
merge pending by thoth-prow even after passing all checks

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#747]
**Describe the bug**
thoth prow is something pending in merging of the pull requests , even though all checks are passed. 
![unmerged](https://user-images.githubusercontent.com/14028058/104637821-4bed4200-5673-11eb-9704-2dbb19a629f3.png)
https://github.com/AICoE/aicoe-cd/pull/212

**To Reproduce**
1. Cant be re-produced explicitly 

**Expected behavior**
merge as soon as all checks are green

**Comment by harshad16** [comment]
Happening for https://github.com/operate-first/apps
Tired to test it with https://github.com/operate-first/apps/pull/347
Error received in logs: `failed to set up context register: contexts aicoe-ci/prow/kustomize-build are defined as required and required if present" `

**Comment by harshad16** [comment]
Testing with: https://github.com/operate-first/apps/pull/349

Tide logs
```
{"branch":"master","component":"tide","controller":"status-update","error":"failed to set up context register: contexts aicoe-ci/prow/kustomize-build are defined as required and required if present","file":"prow/tide/status.go:371","func":"k8s.io/test-infra/prow/tide.(*statusController).setStatuses.func1","level":"error","msg":"getting expected status","org":"operate-first","pr":349,"repo":"apps","severity":"error","sha":"b0bf5837409db496fd76759c43bf4c32800c9073","time":"2021-03-10T20:12:42Z"}
```

**Comment by goern** [comment]
https://github.com/thoth-station/thoth-application/commit/2730b9c91d652022de67bec24c9e30671f8f8507 might fix the problem.

we will keep on observing @HumairAK @tumido

**Comment by harshad16** [comment]
This issue is fixed with all the referenced pull requests.
It was based on a few components update and adjustment of prow config.
closing the issues.
Please free to open new issues if facing any issue with prow.
