### ISSUE TITLE
renew tls certificate

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#759]
Your certificate (or certificates) for the names listed below will expire in 19 days (on 08 Feb 21 09:48 +0000). Please make sure to renew your certificate before then, or visitors to your website will encounter errors.

`tensorflow.pypi.thoth-station.ninja`

/label sig/devops
/priority important-soon
/assign @harshad16 
/label sig/documentation

**Comment by harshad16** [comment]
The certs are updated and applied. 
https://tensorflow.pypi.thoth-station.ninja/ 
closing the issue.
