### ISSUE TITLE
Load tests for user-api

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#774]
**Is your feature request related to a problem? Please describe.**

See discussion in https://github.com/thoth-station/thoth-application/pull/376. We could create load tests for different endpoints to see how our user-api behaves.

**Describe the solution you'd like**

See for example (I haven't read it): https://developers.redhat.com/blog/2015/04/30/how-to-load-test-and-tune-performance-on-your-api/

- [ ] create a short report 
- [ ] load test user-facing API endpoints
- [ ] if possible, create a simple tool that can automate this process to have it available for possible future changes (so we see possible perf degradation on endpoints with changes landing in the project).

**Comment by fridex** [comment]
We should also include testing on the maximum payload size that can go through the system (accepted on user API, propagated to kafka and accepted by OpenShift when scheduling new pods). Relevant: https://github.com/thoth-station/user-api/issues/850

**Comment by codificat** [comment]
Has this been superseded by https://github.com/thoth-station/user-api/issues/1353 ?

**Comment by fridex** [comment]
Yes, I think this one can be closed. Good catch.

/close
