### ISSUE TITLE
image sync for argocli deployment is constantly failing. 

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#779]
**Describe the bug**
The argocli deployment in amun-inspection across prod and ocp4-stage environments is sending out out-of-sync events on argocd. 
Due to which the app in argocd is constantly consuming resource and blocking other apps.

**To Reproduce**
1. Go to 'https://argocd-server-aicoe-argocd.apps.ocp4.prod.psi.redhat.com/applications/ocp4-stage-thoth-amun-inspection'
2. Click on 'argo-server'
3. Scroll down to 'diff'

**Expected behavior**
sync successfully 

**Screenshots**
![argocli-amun](https://user-images.githubusercontent.com/14028058/105378297-accbcb80-5bd9-11eb-8de9-7c4b8a4c6035.png)
![argocli-amun-1](https://user-images.githubusercontent.com/14028058/105378305-afc6bc00-5bd9-11eb-893e-9f622165b8fc.png)

**Additional context**
same application successfully sync in the ocp environment. 
as we deploy argocli in middletier and backend , they seems to be not facing the issue.

**Comment by harshad16** [comment]
also happening with : https://github.com/thoth-station/thoth-application/blob/f0f63f03c9efcc032f3aece707af0df8aede9bb4/sefkhet-abwy/overlays/cnv-prod/new-label-normalizer.yaml#L17

**Comment by goern** [comment]
is this still relevant?

**Comment by harshad16** [comment]
> is this still relevant?

yes it is, we are just using a soft fix with the ignore ,need to find for a better solution.

**Comment by goern** [comment]
can we migrate this issue to op1st/support? looks like an argocd related issue?!

**Comment by goern** [comment]
@harshad16 is this still tbd?

/lifecycle stale

**Comment by harshad16** [comment]
This issue occurs only for deploymentconfigs and cronjobs 
we have decided for now it would be addressed by using the kustomize ignore method
as we image name in cronjob is not change on daily bases , as we utilize imagestream to change tags.
closing this issue.
Thanks for all the thoughts.
