### ISSUE TITLE
Failed to run Amun inspections on ocp cluster in thoth-test-core

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#79]
**Describe the bug**

Running the inspection sample gives an error while creating is:

```

Error from server (Forbidden): error when creating "/tmp/manifest.yaml": imagestreams.image.openshift.io is forbidden: User "system:serviceaccount:thoth-test-core:amun-api" cannot create resource "imagestreams" in API group "image.openshift.io" in the namespace "thoth-test-core"
```

**To Reproduce**
1. Go to ocp and namespace thoth-test-core
2. Try to run Amun inspection (the sample inspection should work)
3. See the error

**Expected behavior**

Amun inspections should run (sufficient privileges should be granted).

**Comment by harshad16** [comment]
while working to fix this issue.
came across another issue.
```
Failed to pull image "kubectl": rpc error: code = Unknown desc = Error reading manifest latest in docker.io/library/kubectl: errors: denied: requested access to the resource is denied unauthorized: authentication required
```
is kubectl image to be also present?

**Comment by fridex** [comment]
> is kubectl image to be also present?

Yes, it's required by amun workflows. It can be found on quay:

https://quay.io/repository/thoth-station/kubectl

It has `kubectl` (or `oc` would be also good) and `jq` for manipulating with JSON. We could rename it and start maintaining in a repo though.

**Comment by harshad16** [comment]
> > is kubectl image to be also present?
> 
> Yes, it's required by amun workflows. It can be found on quay:
> 
> https://quay.io/repository/thoth-station/kubectl
> 
> It has `kubectl` (or `oc` would be also good) and `jq` for manipulating with JSON. We could rename it and start maintaining in a repo though.

awesome :+1:
