### ISSUE TITLE
[Question] approves for individual components ?

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#792]
Shall we put all the individuals that we required to approve deployment of a certain component into an OWNERS file per component? This way Prow would only ask these people for review, and we would cleary see who has no objections to deploy to stage.

We could have each PR to a stage directory start with /hold, and the last of the reviewers is required to /unhold it. This would be a "required but not enforced" review by all component owners.

_Originally posted by @goern in https://github.com/thoth-station/thoth-application/issues/783#issuecomment-766739494_

**Comment by goern** [comment]
@thoth-station/devs how do you all feel about this? to me it seems to be a good step in the direction of 'sig autonomous development'

**Comment by goern** [comment]
Based on the discussion on Tech-Talk, we will do this. @harshad16 and @goern will slowly add OWNER files

**Comment by goern** [comment]
@thoth-station/devs please keep on adding `OWNERS` files, meanwhile, I'll close this...

/close
