### ISSUE TITLE
PSI OCP4 outage root cause points to `thoth-middletier-stage`

### ISSUE THREAD

**Issue by tumido** [thoth-station/thoth-application#797]
**Describe the bug**
I've dug around the PSI OCP4 outage. And I've stumbled upon [the case file to RH support](https://access.redhat.com/support/cases/#/case/02851698). It suggests the `thoth-middletier-stage` may have greatly contributed to the outage due to Argo resources used. See these 2 comments:
- https://access.redhat.com/support/cases/#/case/02851698/discussion?commentId=a0a2K00000Z3i6aQAB
- https://access.redhat.com/support/cases/#/case/02851698/discussion?commentId=a0a2K00000Z3kIhQAJ

This point to a listing issue on Argo workflows because there are too many of them:

```
$ oc describe quota thoth-middletier-stage-quota
Name:                        thoth-middletier-stage-quota
Namespace:                   thoth-middletier-stage
Resource                     Used    Hard
--------                     ----    ----
count/pods                   117     625
count/workflow               0       1k
count/workflows              0       1k
count/workflows.argo.io      0       1k
count/workflows.argoproj.io  235485  1k
limits.cpu                   1500m   56
limits.memory                9192Mi  96Gi
persistentvolumeclaims       0       96
pods                         2       500
requests.storage             0       120Gi
```

**Possible cause**

I've noticed you're running Argo 2.11 in your `thoth-middletier-stage`:
https://github.com/thoth-station/thoth-application/blob/d9888793523cff862b2b70cdeef3d60ed459f3c9/core/overlays/stage/middletier-stage/argo-namespace-install.yaml#L72

And you have the `ttlStrategy` configured as well:
https://github.com/thoth-station/thoth-application/blob/d9888793523cff862b2b70cdeef3d60ed459f3c9/core/overlays/stage/middletier-stage/configmaps.yaml#L14-L17

I think the Argo itself can be blamed for this. There was a bug with Argo 2.11 which prevented the TTL to be propagated properly: https://github.com/argoproj/argo/issues/4106
(We run into the same bug with `aiops-prod-argo` namespace).

This issue was fixed by 2.12.0 Argo release (in [2.12.0-rc1](https://github.com/argoproj/argo/releases/tag/v2.12.0-rc1) to be precise).

I propose you to upgrade your Argo to prevent the amount of `Workflow` resources count growing. I'm not sure why the quota is not properly enforced and the question was raised in the support case as well.

You can reference the IDH manifests for the latest argo:
https://github.com/AICoE/idh-manifests/tree/production/argo

Btw, Argo upstream started to release to Quay recently, you don't have to define your own `ImageStream`s anymore or copy the images over:
https://quay.io/organization/argoproj

**Comment by harshad16** [comment]
Thanks for letting us know. 
we would work on this, we have clearly failed to notice this. :disappointed:

**Comment by tumido** [comment]
I mean.. you shouldn't be able to even break it even if you try. You've just accidentally exposed a weak spot of the system :slightly_smiling_face:

**Comment by harshad16** [comment]
unfortunately, our Prometheus instance also didnt help with this :(

**Comment by pacospace** [comment]
> unfortunately, our Prometheus instance also didnt help with this :(

we do not maintain that instance of Prometheus... and Thanos is not working for days now. 

Maybe we should enforce scheduling limit by investigator https://github.com/thoth-station/investigator/blob/392d7abcb7efde368a385edcba820100d76437b7/thoth/investigator/configuration.py#L48 if the cluster does not has limits. (time to rewatch https://www.youtube.com/watch?v=9wvEwPLcLcA)

**Comment by goern** [comment]
nice work all! If you have a look at the number of people involved in debugging the case, I'm a little bit scared... how would we have performed in the operate-first environment?!

@pacospace having some kind of throttling in investigator might be a good idea, but ultimately the platform should protect us from killing itself. 

Cc @duanrom

**Comment by harshad16** [comment]
yes i agree @pacospace , we can enforce with the schedule limit

**Comment by goern** [comment]
anyway... its a good argument to have a stage environment on Operate-First, and not bring down production clusters ;)

**Comment by harshad16** [comment]
Tasks on the process:
-  Already scaled down our workflow producers
- updated a new version of Argo v2.12.5 which correctly follow ttl (working on verifying it)
- deleting the huge pile of `workflows.argoproj.io` in `thoth-middletier-stage`

**Comment by harshad16** [comment]
All the workflows piled in thoth-middletier-stage is clean
```
hnalla@workstation ~ $ oc describe quota thoth-middletier-stage-quota                               
Name:                        thoth-middletier-stage-quota
Namespace:                   thoth-middletier-stage
Resource                     Used  Hard
--------                     ----  ----
count/pods                   0     625
count/workflows.argoproj.io  115   1k
limits.cpu                   0     56
limits.memory                0     96Gi
persistentvolumeclaims       0     96
pods                         0     500
requests.storage             0     120Gi
```

Next step: 
- Test out the upgraded argo workflows and verify the ttl is working for argoworkflows
- work with the infra team on the limit limitations.
