### ISSUE TITLE
Implement a procedure to delete old data

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#808]
**Is your feature request related to a problem? Please describe.**

To keep the service responsive and available to users, we should implement a mechanism that automatically cleans old data from the database. This way, the database will stay operational, scalable, and ready to ingest more up2date data required. An example can be data produced by solver-fedora-28-py36 solver which are no longer required (based on Fedora EOL release cycle).

**Describe the solution you'd like**

Implement a mechanism that is well tested and can delete old data from the database in a reliable way in deployments.

**Describe alternatives you've considered**

Keep the database as is, but that will introduce scalability and availability issues. Moreover, the service will slow down.

**Additional context**

- [x] identify data that can be removed as they will be becoming obsolete
- [x] implement scheduling routines to start purge workflows - https://github.com/thoth-station/common/pull/1152
- [x] introduce purge workflows - #1208
- [x] implement methods in thoth-storages that will make sure the data are properly deleted and the database indexes freed - https://github.com/thoth-station/storages/pull/2292
- [x] implement a job which is run on a request in deployment, this job should become a new component in a Thoth deployment - https://github.com/thoth-station/purge-job/pull/3
- [x] implement required manifests in thoth-application - https://github.com/thoth-station/thoth-application/pull/1208
- [x] make sure the job works well
- [x] make sure the job can be triggered by Thoth operator or administrator with appropriate privileges
- [x] introduce endpoints on management-api for triggering purge job - https://github.com/thoth-station/management-api/pull/747

We can remove the data from the knowledge graph to keep the application responsive. However, we can still keep the data on Ceph.

**Comment by pacospace** [comment]
Do we want to run it from `management-api`? maybe with `solver` parameter to be provided?

**Comment by fridex** [comment]
> Do we want to run it from `management-api`? maybe with `solver` parameter to be provided?

Yes, a one time async job (similar workflow to graph schema update job) should do the trick.

**Comment by fridex** [comment]
> * [ ]  identify data that can be removed as they will be becoming obsolete

I think we can start with cleaning postgres - container image analyses, solver results and adviser results.
