### ISSUE TITLE
Use labels from proposed Sane Label system

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/thoth-application#810]
**Reference**
Labels proposal document: https://docs.google.com/document/d/1fQyw3J844T5FFeQQ5IfMisYsKAOL1jBl4jtRkFFPiKU/edit#heading=h.piexvf6roiuh

**Acceptance Criteria**

- [ ] Read the doc and select some of the labels suggested in the document
- [ ] Decide which labels are redundant and merge them (the already used and proposed ones)
- [ ] Decide which labels are not reasonable and comment on them in document.
- [ ] Specify selected labels, perhaps reason their selection and also mention them here in this Issue.
- [ ] Make additional suggestions/comments to the document, if needed.   
- [ ] Use labels within bot, see additional context

**Additional Context**
See https://github.com/thoth-station/thoth-application/blob/80a3573596a2496b1ece38bb097c2c00cb821ab9/prow/overlays/cnv-prod/plugins.yaml#L1-L22

**Comment by goern** [comment]
@xtuchyna how do you want to proceed with this? feel free to get it out of the rotten stack and walk us thru it ;)

/triage needs-information

**Comment by xtuchyna** [comment]
/reopen
/remove-lifecycle rotten

Hey @goern @pacospace @fridex what about this becoming an intern project ?!

**Comment by codificat** [comment]
/kind cleanup
/triage accepted
/priority important-soon

There is a parallel effort for the operate-first org, see https://github.com/operate-first/support/issues/478

**Comment by codificat** [comment]
/remove-priority backlog
/remove-kind feature
to keep just one of each

**Comment by codificat** [comment]
and
/remove-kind question

**Comment by VannTen** [comment]
Some general comments after pointing some specific items on the google doc.
(also taking into account the scheme we're applying *now*)


I find the `label_type:label_value` quite good. However, I think we should
strive for minimalism in the number of values per type, in particular for
subjective values; and split type if needed.

`kind` for example feels a bit like a mixed bag for me:
- `bug`, `feature`, `question` -> maps to how we should triage the issue
- `documentation` -> maps to a particular element of the codebase (`test` would
  be in the same bag for example)

Maybe we should have some kind of pool and see what everyone else thinks of some
labels (how often we apply it/use it for querying/what information it brings) ?

**Comment by codificat** [comment]
Quick note to mention that this was discussed in today's tech talk and the conclusion was to work to address specific ambiguities (like the `kind/* mentioned above) while overall continue to adhere to the way [kubernetes uses labels](https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.md#why-these-labels).
