### ISSUE TITLE
Any public user can use "/unhold" on a PR for sesheta

### ISSUE THREAD

**Issue by 4n4nd** [thoth-station/thoth-application#813]
**Describe the bug**
When a PR is put on hold, it can be unholded by any public user who is not in the OWNERS file ([example PR](https://github.com/operate-first/apps/pull/172#issuecomment-769128593))

**To Reproduce**
1. Create a PR  like [this one](https://github.com/operate-first/apps/pull/172#issuecomment-769128593)

**Expected behavior**
nothing should happen (no label changes) to the PR in case of an "/unhold" comment by a user who is not in the OWNERS file

**Comment by goern** [comment]
strange, i'll have a look at it

**Comment by goern** [comment]
it seems that it works as coded: https://github.com/kubernetes/test-infra/blob/master/prow/plugins/hold/hold.go#L106-L113
see also https://kubernetes.io/docs/contribute/review/for-approvers/#prow-commands-for-reviewing

**Comment by goern** [comment]
@4n4nd can this be closed?
