### ISSUE TITLE
prow isnt adding the label `lgtm`

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#814]
**Describe the bug**
prow isnt adding the label `lgtm` based on the lgtm comment 
https://github.com/operate-first/apps/pull/173#issuecomment-769205374

**Comment by goern** [comment]
after https://github.com/thoth-station/thoth-application/commit/4833e9725efada4f651503ca80bb27a40ce4dba6 and restarting hook, deck, tide pods it seems to work.

@HumairAK pls chk

**Comment by HumairAK** [comment]
it adds the label now, can it be set so that the label is added if at minimum 2 people do `/lgtm` ?

**Comment by goern** [comment]
no, ultimately its the responsibility of the approver to look out for 2 lgtm. it seems to be a good practice, to look out for PRs to be approved if at least one lgtm label is present: https://github.com/issues?q=is%3Aopen+is%3Apr+archived%3Afalse+user%3Aoperate-first+label%3Algtm

**Comment by goern** [comment]
can we close this?

**Comment by harshad16** [comment]
yes, i think we can i have seen `lgtm` label being added .
thanks for the fix @goern
