### ISSUE TITLE
Failed to update dependencies via bot due to transitive pre-release dependency

### ISSUE THREAD

**Issue by tumido** [thoth-station/thoth-application#816]
**Describe the bug**
We have a dependency installed via Pipenv. This dependency depends on a package which has only pre-releases. We don't want to specify `allow_prereleases = true` in our `Pipfile` since that would turn pre-release resolution globally for all dependencies and we don't want that.

Notes:
- We have no control over the required transitive dependency version. 
- This dependency without a proper release is not specified in our Pipfile at all, therefore we can't use the "lock to a specific pre-release trick" as described here https://github.com/pypa/pipenv/issues/1760#issuecomment-573910874 

**To Reproduce**
1. Have a `Pipfile` which installs a dependency that depends on a pre-release itself
2. Lock it locally using `pipenv lock --pre`
3. Commit
4. Let bots auto update dependencies - it fails 

In our case (https://github.com/aicoe-aiops/mailing-list-analysis-toolkit/issues/36) the troubled dependencies are:
- `papermill` which is our direct dependency 
- `black` which is a dependency of `papermill`

**Expected behavior**
Auto updater should be able to resolve pre-releases if they were already resolved to a pre-release for packages in `Pipfile.lock` file. This is different to allowing to resolve all pre-releases for all packages (the `allow_prereleases` flag).

**Screenshots**
n/a

**Additional context**
https://github.com/aicoe-aiops/mailing-list-analysis-toolkit/issues/36
https://github.com/pypa/pipenv/issues/1760
https://github.com/pypa/pipenv/issues/965

**Comment by fridex** [comment]
This is something Pipenv community complains about as well. I understand the use of this and the consequences it brings (some software stacks are not resolvable at all). We can open this discussion in Pipenv community. If they provide a "standard way" how to approach this (e.g. in pipfile, specify acceptable pre-releases for a package, similarly as [specifying the index to be used to install the package](https://pipenv-fork.readthedocs.io/en/latest/advanced.html#specifying-package-indexes)) we are happy to include it in our recommendations - it's not that big change on our side.

**Comment by tumido** [comment]
There's this upstream issue, suggesting a per-package pre-release spec Pipfile syntax extension
https://github.com/pypa/pipenv/issues/1760

I've faced the same issue already, but in that case it was our direct dependency so the workaround to locking it to an exact pre-release version worked in that case. However in this case, when it's a transitive dependency I'm clueless... Like.. the same workaround might help for the time being, but it may lead version mismatches if the transitive dependency version requirement is changed... Which would just postpone the same problem, it's not a real solution.

So my ask is, if there's a possibility for the auto-update job to facilitate this. I don't know, maybe a config flag allowing pre-release resolution on packages which are already locked to a pre-release? Or something like that. I know this is far fetched though, but any idea would be welcomed. We certainly want our stacks to be resolvable by the auto-updater so I'm looking for a way how to achieve that. :slightly_smiling_face:

**Comment by fridex** [comment]
> There's this upstream issue, suggesting a per-package pre-release spec Pipfile syntax extension
> [pypa/pipenv#1760](https://github.com/pypa/pipenv/issues/1760)

Proposed https://github.com/pypa/pipenv/pull/4607 based on that. An extension could be created which would act on trasitive packages considered (but I would not bring that to the referenced PEEP).

> So my ask is, if there's a possibility for the auto-update job to facilitate this. I don't know, maybe a config flag allowing pre-release resolution on packages which are already locked to a pre-release? Or something like that. I know this is far-fetched though, but any idea would be welcomed. We certainly want our stacks to be resolvable by the auto-updater so I'm looking for a way how to achieve that.

The auto-update bot uses Pipenv under the hood (as of now), so we rely on Pipenv logic. Hopefully, we will soon switch to Thoth based updates in which case we can support whatever will be standardized by Pipenv/Python community. As we offer ``thamos install``, we can bring solutions possibly faster but users of our recommendations will need to use our tooling (instead of Pipenv).

**Comment by goern** [comment]
Shouldnt the advisor-based update manager of kebechet address this issue?

**Comment by fridex** [comment]
> Shouldnt the advisor-based update manager of kebechet address this issue?

Selectively enable pre-releases for just some packages is not something Pipenv can do. It is possible to turn on enabling pre-relesases globally, for all the packages in the software stack, or turn it off completely. If there would be a standardized way how to enable pre-releases just for some packages in Pipfile (e.g. as described in https://github.com/pypa/pipenv/pull/4607), we can provide such a mechanism. As of now, we are compatible with Pipenv and Pipfile/Pipfile.lock capabilities it offers.

**Comment by fridex** [comment]
BTW we could introduce `[thoth]` section to Pipfile, I guess it would work with Pipenv as it ignores unknown entries in the Pipfile. We could introduce some experimental features there (such as this one).

**Comment by fridex** [comment]
Thoth now supports enabling pre-releases for certain packages, see:

https://thoth-station.ninja/docs/developers/adviser/experimental_features.html#selectively-enabling-pre-releases

I will close this one, feel free to report any issues if any spotted. Thanks for the report 👍🏻 

/close
