### ISSUE TITLE
deploy SLO reporter to op1st

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#817]
**Is your feature request related to a problem? Please describe.**
deploy slo reporter to op1st env `cnv-prod`, disable it for stage (or limit recipients to aicoe-thoth)

/sig devops
/sig slo
/assign @pacospace

**Comment by pacospace** [comment]
It should be deployed: https://github.com/operate-first/argocd-apps/blob/main/overlays/moc/thoth/prod/prod-thoth-slo-reporter.yaml, not sure why it is missing in `thoth-infra-prod`, cc @harshad16

**Comment by pacospace** [comment]
> It should be deployed: https://github.com/operate-first/argocd-apps/blob/main/overlays/moc/thoth/prod/prod-thoth-slo-reporter.yaml, not sure why it is missing in `thoth-infra-prod`, cc @harshad16

Found is missing in the kustomize file.

**Comment by pacospace** [comment]
> > It should be deployed: https://github.com/operate-first/argocd-apps/blob/main/overlays/moc/thoth/prod/prod-thoth-slo-reporter.yaml, not sure why it is missing in `thoth-infra-prod`, cc @harshad16
> 
> Found is missing in the kustomize file.

Opened PR, but the version we want in production is v0.8.2 not before!, should we just change that component for prod? Or do we need a new date release before moving all to production?

**Comment by goern** [comment]
> > > It should be deployed: https://github.com/operate-first/argocd-apps/blob/main/overlays/moc/thoth/prod/prod-thoth-slo-reporter.yaml, not sure why it is missing in `thoth-infra-prod`, cc @harshad16
> > 
> > 
> > Found is missing in the kustomize file.
> 
> Opened PR, but the version we want in production is `v0.8.2` not before!, should we just change that component for prod? Or do we need a new date release before moving all to production?

I think with #819 being merged the question is answered?!

**Comment by pacospace** [comment]
> > > > It should be deployed: https://github.com/operate-first/argocd-apps/blob/main/overlays/moc/thoth/prod/prod-thoth-slo-reporter.yaml, not sure why it is missing in `thoth-infra-prod`, cc @harshad16
> > > 
> > > 
> > > Found is missing in the kustomize file.
> > 
> > 
> > Opened PR, but the version we want in production is `v0.8.2` not before!, should we just change that component for prod? Or do we need a new date release before moving all to production?
> 
> I think with #819 being merged the question is answered?!

That was one step required to make sure we have correct version and CM.

Second step: https://github.com/operate-first/argocd-apps/pull/59

**Comment by harshad16** [comment]
The slo-reporter is successfully deployed in the op1st cluster.
https://argocd-server-argocd.apps.cnv.massopen.cloud/applications/prod-thoth-slo-reporter?conditions=false

Please close the issue, if this feels satisfactory :)

**Comment by pacospace** [comment]
> The slo-reporter is successfully deployed in the op1st cluster.
> https://argocd-server-argocd.apps.cnv.massopen.cloud/applications/prod-thoth-slo-reporter?conditions=false
> 
> Please close the issue, if this feels satisfactory :)

Thanks @harshad16 , I still cannot see applications in Argo CD!

**Comment by pacospace** [comment]
There is one bug we never encountered in test/stage: https://github.com/thoth-station/slo-reporter/issues/188

**Comment by pacospace** [comment]
> There is one bug we never encountered in test/stage: [thoth-station/slo-reporter#188](https://github.com/thoth-station/slo-reporter/issues/188). I will work on it

Bug has been solved with new release and in prod is running correctly. There is a non critical issue, that it's not priority but I will try to add that as well, so we don't have that issue anymore.

**Comment by pacospace** [comment]
This might be the next thing to have: https://github.com/thoth-station/slo-reporter/issues/197

**Comment by harshad16** [comment]
> Bug has been solved with new release and in prod is running correctly. There is a non critical issue, that it's not priority but I will try to add that as well, so we don't have that issue anymore.

The apps is in the place https://console-openshift-console.apps.cnv.massopen.cloud/k8s/ns/thoth-infra-prod/cronjobs/slo-reporter

@pacospace if this feels good enough , can we close this issue?

**Comment by pacospace** [comment]
> > Bug has been solved with new release and in prod is running correctly. There is a non critical issue, that it's not priority but I will try to add that as well, so we don't have that issue anymore.
> 
> The apps is in the place https://console-openshift-console.apps.cnv.massopen.cloud/k8s/ns/thoth-infra-prod/cronjobs/slo-reporter
> 
> @pacospace if this feels good enough , can we close this issue?

Yes we can close it definitely, thanks @harshad16 !
