### ISSUE TITLE
Unknown packages in the provenance check should trigger analysis of missing packages

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#818]
**Is your feature request related to a problem? Please describe.**

If a user uses a package that was not previously analyzed, provenance checks fail with knowledge about packages being not available to users. Thoth does not learn about new packages that are requested in by provenance checks.

**Describe the solution you'd like**

Follow a scenario similar to the one we have in adviser workflow - schedule analysis of the given unknown package.

**Comment by goern** [comment]
@KPostOffice @pacospace is this something that one of you could take on?

/priority critical-urgent
/sig knowledge-graph

**Comment by pacospace** [comment]
> @KPostOffice @pacospace is this something that one of you could take on?
> 
> /priority critical-urgent
> /sig knowledge-graph

I will take care!

**Comment by pacospace** [comment]
- [ ] create method to `parse_provenance_checker_output` in workflow helpers and return messages to be sent
- [ ] Extend provenance checker Argo workflow with two new steps: parse output and send messages

OPTIONAL:
- [ ] Adjust provenance checker sync to store unsolved packages?

**Comment by pacospace** [comment]
From provenance report the packages that will be triggered for solver workflows run are the ones identified from id: `MISSING-PACKAGE`

example:

```
      {
        "id": "MISSING-PACKAGE",
        "justification": "Source index 'pypi-org' explicitly assigned to package 'pytest-cov' but there was not found any record for the given package",
        "package_locked": {
          "pytest-cov": {
            "hashes": [
              "sha256:359952d9d39b9f822d9d29324483e7ba04a3a17dd7d05aa6beb7ea01e359e5f7",
              "sha256:bdb9fdb0b85a7cc825269a4c56b48ccaa5c7e365054b6038772c32ddcdc969da"
            ],
            "index": "pypi-org",
            "version": "==2.11.1"
          }
        },
        "package_name": "pytest-cov",
        "package_version": "==2.11.1",
        "source": {
          "name": "pypi-org",
          "url": "https://pypi.org/simple",
          "verify_ssl": true
        },
        "sources": {
          "https://pypi.org/simple": [],
          "https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple": [],
          "https://tensorflow.pypi.thoth-station.ninja/index/rhel7.5/AVX2/simple": [],
          "https://tensorflow.pypi.thoth-station.ninja/index/rhel7.6/AVX2/simple": [],
          "https://tensorflow.pypi.thoth-station.ninja/index/rhel7.7/AVX2/simple": []
        },
        "type": "ERROR"
      },
```

**Comment by pacospace** [comment]
@fridex  in case of provenance checker we do not consider the runtime environment, so when a missing package is found, all solvers available should be scheduled for that package, ack?

**Comment by pacospace** [comment]
> * [x]  create method to `parse_provenance_checker_output` in workflow helpers and return messages to be sent
> * [ ]  new release of workflow-helpers
> * [x]  Extend provenance checker Argo workflow with two new steps: parse output and send messages
> 
> OPTIONAL:
> 
> * [ ]  Adjust provenance checker sync to store unsolved packages? As we do in adviser workflow or should we remove it from adviser workflow as redundant?

@fridex wdyt about last optional task?

**Comment by fridex** [comment]
I think it might be good to have it but does not seem to be required.
