### ISSUE TITLE
Implement a procedure to install new solvers/thoth s2i

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#825]
**Is your feature request related to a problem? Please describe.**

Similar to https://github.com/thoth-station/thoth-application/issues/808, we should create a procedure that will guide thoth operators on how to install new solvers and thoth s2i so that a thoth deployment is up2date and no parts are forgotten in the installation procedure.

**Describe the solution you'd like**

Create a step-by-step tutorial on how to build, install and register new solvers to Thoth. This way Thoth will be able to produce recommendations specific to runtime environments analyzed and available to users.

**Comment by goern** [comment]
Shall we have on YAML file that declares which solvers should be in the solvers config map and which need to be present in the database? trying to recall from the last tech talk session, do we need that?!

**Comment by fridex** [comment]
> Shall we have on YAML file that declares which solvers should be in the solvers config map and which need to be present in the database? trying to recall from the last tech talk session, do we need that?!

I think we should have an alert on solver CM vs solver database misconfiguration. Otherwise, the system will not handle requests as expected in some corner cases - see https://github.com/thoth-station/metrics-exporter/issues/586 https://github.com/thoth-station/storages/pull/2197#issuecomment-769795197

**Comment by fridex** [comment]
TODO: document "last" package extract result available on User API endpoints.
