### ISSUE TITLE
remove old adviser messages from kafka topic

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#855]
**Is your feature request related to a problem? Please describe.**
If we monitor the kafka topic for adviser requests, we could expire/delete messages older than 2 days, as we assume that these messages do not deliver any value to the user anymore. we should have a grafana dashboard showing the deleted messages, as we consider them 'service not delivered to user'.

/kind feature
/sig user-experience

@fridex @KPostOffice

**Comment by fridex** [comment]
Ideally, this should be set to the same value as in case of cache expiration on user-api side:

https://github.com/thoth-station/user-api/blob/37a4d9c78858258b84da1d96e3e5cc4f77066f32/thoth/user_api/configuration.py#L37-L38

User API caches requests and links them to the same analysis id to avoid scheduling the same workload multiple times. The message expiration should be set to the same value as user-api's cache expiration to make sure users schedule workload again (if messages were deleted) or the cache does not link to a non-existing request. If we cannot link these two on the application level (e.g. have a configmap entry for this to parametrize both), we should have an alarm on this.

The message expiration/cache expiration (could be called request expiration?) should be probably exposed as a metric anyway so we observe how the deployment is configured.

**Comment by KPostOffice** [comment]
This has to be set by `odh` this isn't configuration that `librdkafka`/`confluent-kafka` can set.

Something like this:
```bash
$ bin/kafka-configs.sh --zookeeper localhost:2181  --entity-type topics --entity-name my-topic --alter --add-config retention.ms=128000
```

**Comment by KPostOffice** [comment]
I know how to do this I just don't know of a good place to put it. This should be one and done, once we set the configuration we should only have to set it again if the configuration changes or if Kafka goes down and can't be recovered.  It might be okay to just put it in a CronWorkflow and add a new task in workflow helpers which uses confluent-kafka-python AdminClient to set configuration every morning just in case either of these cases occured.

**Comment by goern** [comment]
topic retention time needs to be set to the cache time user-api, see https://github.com/thoth-station/thoth-application/blob/master/user-api/base/configmap.yaml#L9

/triage accepted
/priority important-soon
/assign @kpostoffice

**Comment by KPostOffice** [comment]
https://github.com/operate-first/apps/pull/768
