### ISSUE TITLE
Correlate OpenShift metrics with Thoth metrics

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#856]
As Thoth Operator and Maintainer,

I want to have a look at metrics that immediately show me issues and set alarms for them. We have Thoth metrics and we can correlate them with OpenShift once to have a complete overview.

List of new metrics to be shown in Grafana

OpenShift Metrics:
- [ ] CPU Usage user-api
- [ ] CPU Usage postgres
- [ ] TBD

Thoth Metrics:
- [ ] TBD

based on these metrics, we can have more alarms: https://github.com/thoth-station/thoth-application/issues/854

**Acceptance Criteria**
- [ ] A set of Alerts created in Prometheus that open GitHub Issues

**Comment by pacospace** [comment]
Follow Hema suggestions from Operate First, on how to expose them in production. Not sure about stage actually

**Comment by harshad16** [comment]
Metrics: https://console-openshift-console.apps.ocp4.prod.psi.redhat.com/dev-monitoring/ns/thoth-frontend-stage

**Comment by pacospace** [comment]
Related-To: https://github.com/thoth-station/thoth-application/issues/854

**Comment by pacospace** [comment]
Related-To: https://github.com/operate-first/support/issues/288
