### ISSUE TITLE
rename this repo^H^H^H^Hproject to `Thoth Services`?

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#864]
shall we rename this repo to `thoth services`, it shall container all things related to

* deployment of the services
* operation of the services
* (usage )questions wrt the service

WDYT

**Comment by fridex** [comment]
I'm fine with renaming the repo. :+1:

**Comment by goern** [comment]
I was actually thinking about the https://github.com/orgs/thoth-station/projects/16 to be renamed

**Comment by harshad16** [comment]
sounds good to me, lets change the name of the project.

**Comment by harshad16** [comment]
Update the name of the Thoth-deployment project board to Thoth-Services.
along with moving the overall issue from thoth-core board to this and updated the description.
