### ISSUE TITLE
Thoth's resolver experimental features - selective pre-releases

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#884]
Now at: https://github.com/thoth-station/thoth-application/issues/884

**Thoth's resolver experimental features - selective pre-releases**

* area: sig/adviser
* related: https://github.com/thoth-station/thoth-application/issues/816
* thoth-adviser needs to be bumped to v0.24.1
* user-api needs to be bumped to v0.18.0
* thamos needs to be bumped to 1.11.0
* docs: https://thoth-station.ninja/docs/developers/adviser/experimental_features.html

With this change, we are able to resolve software stacks that have only some of the dependencies marked as pre-releases. As this feature is not available in any Python resolver, we proposed [PEEP-0007](https://github.com/pypa/pipenv/pull/4607/files) to Pipenv community and designed our downstream approach on how to tackle this issue. Basically, users can selectively mark some of the dependencies to be pre-releases in the dependency graph and keep the rest of the packages as releases. This is crucial to resolve software stacks that have some of the dependencies pre-releases or, having an ability to state only some of the dependencies to be pre-releases to test application with (e.g. tensorflow==2.4.0rc0 but the rest of the packages are releases). See [documentation for more info](https://thoth-station.ninja/docs/developers/adviser/experimental_features.html). This feature request was brought by AIOps where they were not able to resolve software stacks - [see the linked issue](https://github.com/thoth-station/thoth-application/issues/816).

Will update this comment if anything more is needed to deliver this feature.

**Comment by fridex** [comment]
This is already implemented and available in test/stage/prod deployments. Closing.

**Comment by fridex** [comment]
https://www.youtube.com/watch?v=w78ycZubmjw
