### ISSUE TITLE
Thamos s2i integration

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#885]
**Thamos s2i integration**

* area: sig/user-experience
* new `thamos s2i` command which integrates with Thoth's s2i workflow
* thamos needs to be bumped to at least [v1.9.0](https://github.com/thoth-station/thamos/pull/721)
* [Thoth S2I procedure](https://github.com/thoth-station/thoth-application/blob/master/thoth_s2i_procedure.md) needs to be met to deliver this feature
* TODO: finish porting Thoth s2i to AICoE build process and register them on Management API endpoints

Will update this comment if anything more is needed to deliver this feature.

**Comment by fridex** [comment]
I would close this, it is already done.
