### ISSUE TITLE
[SPIKE] Possible Cachito integration

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#889]
**Is your feature request related to a problem? Please describe.**

As discussed, we could have a look if we can integrate with Cachito and help it with dependency resolution.

The main issue I see on the Thoth side, as of now is, that we resolve software for runtime environments. Cachito, on the other side, needs also information about build dependencies (`setup_requires`). I think we already have build-time dependencies in solver results, but we do not work with them and the resolver does not take them into account.

CC @goern @harshad16 @sub-mod 

EDIT: setup_requires is something we do not want to support, maybe rather [PEP-518](https://www.python.org/dev/peps/pep-0518/#build-system-table)

**Comment by goern** [comment]
/close
lets reopen if we need it
