### ISSUE TITLE
Advise workflow fails if software stack fails to be propagated via env variables

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#902]
**Describe the bug**

When asking for an advise with a large stack, advise workflow does not start at all. It looks like the main reason is Pipfile.lock stored in an environment variable.

**To Reproduce**
1. Clone https://github.com/thoth-station/elyra-aidevsecops-tutorial/
2. Run `thamos advise` and let the user stack be submitted
3. See an error

**Expected behavior**

The advise should be computed.

**Additional context**

As we store the advise request on Ceph, we can extract inputs to adviser from the request. This way it does not need to be propagated via environment variables.

**Comment by goern** [comment]
cant we transfer the info via a message's content?

**Comment by fridex** [comment]
> cant we transfer the info via a message's content?

 Messages content is translated to environment variables now.

We store the request payload with Pipfile/Pipfile.lock and library usage on ceph:

https://github.com/thoth-station/user-api/blob/b0b72ace062598172d29b07d22d6d74a459570c1/thoth/user_api/api_v1.py#L381-L386

so we could provide them to the adviser container using Argo's input artifacts. This should be scalable and straightforward to implement with the current implementation - just point adviser container to the downloaded artifacts instead of passing the payload directly via env vars.

**Comment by fridex** [comment]
/assign @harshad16 

I guess it is not necessary to include this in the current release cycle. Up to you, the work should be done.
