### ISSUE TITLE
can not understand annotations in imagestreamtags and how argocd behaves...

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#911]
**Describe the bug**
please have a look at https://argocd-server-argocd.apps.cnv.massopen.cloud/applications/ci-prow-prod?node=image.openshift.io%2FImageStream%2Fopf-ci-prow%2Fcrier%2F0 

I can not understand what the problem here is, it seems to be argocd?!

/assign @tumido

**Comment by tumido** [comment]
May be related to https://github.com/AICoE/aicoe-cd/issues/230

Is this new thing for the app or was the error present for longer time?

cc @HumairAK
