### ISSUE TITLE
qeb-hwt secret generation seems broken

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#915]
**Describe the bug**
```
checking ./qeb-hwt-github-app/overlays/stage
Error: no matches for OriginalId ~G_v1_Secret|~X|qeb-hwt-secret; no matches for CurrentId ~G_v1_Secret|~X|qeb-hwt-secret; failed to find unique target for patch ~G_v1_Secret|qeb-hwt-secret
```

**To Reproduce**
1. run ` IS_AICOE_CI=1 ./test-kustomize-build`

/sig devops

**Comment by goern** [comment]
@harshad16 is this done?

**Comment by harshad16** [comment]
This is fixed .
we had updated the secrets in qebhwt.
Reference: https://github.com/thoth-station/thoth-application/commit/84c68f07ccd9fd716c84353614d9b0b81fba272c
closing the issue, re-open if anyone faces the same issue.
