### ISSUE TITLE
Run production slo-reporter in stage?

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#930]
slo-reporter which sends out emails based on the metrics of thoth-station, uses sendgrid to send out the email from the production cluster. The integration-test has a similar setup of sending out emails, the idea of integration-tests for production is to execute them from stage cluster, as the production endpoints are public and can be reachable, in this way integration-tests doesnt need to utilize the sendgrid like stmp service.
Maybe we can have the similar kinda setup for slo-reporter for production? Execute it in the staging cluster.

**Comment by harshad16** [comment]
@pacospace

**Comment by pacospace** [comment]
Hey @harshad16, apparently in cnv-prod it is not working as well even with sendinblue :/ I would consider this a better solution at this point, so we can use same logic used for slo-reporter stage and talk to the public endpoints as per integrations-tests

- [ ] create slo-reporter-prod cronjob in stage
