### ISSUE TITLE
Check NumPy's NEP38: Using SIMD optimization instructions for performance

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#955]
**Is your feature request related to a problem? Please describe.**

See accepted [NumPy NEP38](https://numpy.org/neps/nep-0038-SIMD-optimizations.html) which should be available in [NumPy starting 1.20.0](https://numpy.org/doc/stable/release/1.20.0-notes.html#enable-multi-platform-simd-compiler-optimizations). Long story short, NumPy can benefit in performance when SIMD instructions are available.

**Describe the solution you'd like**

- [ ] check if we need to build numpy and host it on our index to benefit from SIMD instruction set used 
  - [ ] is there some community index we could reuse and register in thoth for monitoring?
- [ ] evaluate performance improvement by running Amun inspections
- [ ] create and publish notebook to analyse Amun inspections
- [ ] recommend using optimized numpy if SIMD instructions are present to profit from the performance improvements

**Comment by goern** [comment]
/remove-triage needs-information
/priority backlog

This one needs us to host our own build of numpy, so pulp deployment in op1st is requried
